### ISSUE TITLE
Querying with params from $route

### ISSUE THREAD

**Issue by FranzSkuffka** [vuejs/vuefire#10]
I came to realise that if I pass a function to `firebase` like I would pass to `data` in one of my 
components, it does not get called. I want to pass a route parameter to my query `innovation`.

```coffee
# editor.vue
  firebase: ->
    console.log 'evaluating' # not logging
    data = 
      innovation: db.innovation @$route.params.innovation_slug

# alternative editor.vue: this is effectively binding innovation to the data source
  firebase:
    innovation: db.innovations() # query working, but route not available
```

```coffee
# db.coffee
module.exports = ->
  url = 'project-2654865812003744343.firebaseio.com'

  firebase =
    innovation: (slug) =>
      ref = new Firebase url
      ref.child('innovations').orderByChild('name').equalTo(slug)

    innovations: =>
      ref = new Firebase url
      ref.child 'innovations'

  return firebase
```
I also tried binding the data sources in the `ready` hook.

```coffee
# editor.vue
  ready: ->
    @$bindAsObject('innovation', db.innovation(@$route.params.innovation_slug)) # not binding
```

Am I doing something wrong? Do you have a recommended approach or a working example?

**Comment by FranzSkuffka** [comment]
I managed binding it.

**Comment by jwngr** [comment]
Sounds like you resolved this problem. If you did, please provide the solution you ended up with so that future devs can benefit from your answer.

**Comment by FranzSkuffka** [comment]
Here's my solution.
https://github.com/FranzSkuffka/innovant/blob/firebase-wip/assets/libs/vuefire.js#L177

It's just a hacky quickfix, but that's where the change is needed. Possibly you want to incorporate it in a different way.

Here is how it is used:
https://github.com/FranzSkuffka/innovant/blob/firebase-wip/app/components/editor.vue#L58

I will have to make sure that it does not interact with the other problems I opened issues for.

**Comment by FranzSkuffka** [comment]
Should I file a PR?

**Comment by balthild** [comment]
Same issue.

```javascript
export default {
    firebase: {
        articles: source: db.ref('/data/article').orderByChild('id').equalTo(this.$route.params.id)
        // Uncaught TypeError: Cannot read property 'params' of undefined
    }
}
```

**Comment by FranzSkuffka** [comment]
@balthild how does using npm relate to incorporating a fix?
You can just extract the file from your package.json and save it somewhere else...


@jwngr this is not a question, but bug I think.
Are you planning to fix this?

**Comment by posva** [comment]
@FranzSkuffka #25 Fix this. I'll merge it this week and release a new version with the feature 😄

**Comment by FranzSkuffka** [comment]
@posva thanks very much for the heads up :)

**Comment by balthild** [comment]
@FranzSkuffka Well, I just want to keep all dependencies managed by `npm` exclusively...

@posva Thanks!
