### ISSUE TITLE
Getting urls from firebase storage

### ISSUE THREAD

**Issue by dmattia** [vuejs/vuefire#100]
My firebase schema looks like this:

    {
      items: {
        <id#1>: {
          image_loc: ...,
        },
        <id#2>: {
          image_loc: ...,
        },
      }
    }

It would be nice if a feature could be added that could transform relative urls into the actual urls found by:

    firebase.storage().ref(<relative_url>).getDownloadURL()

**Comment by posva** [comment]
This is something you may ask for in firebase repo 😅
