### ISSUE TITLE
Global Binding

### ISSUE THREAD

**Issue by SKFrozenCloud** [vuejs/vuefire#1006]
### What problem is this solving

I want to be able to dispatch bind once then if another page dispatches bind again it won't unbind -> bind -> refetch whole db.
Check if state is already bound to not refetch whole DB each time I call bind (because I call it in another page in Nuxt JS).

### Proposed solution

An option for the `bindFirestoreRef()` / `bindFirebaseRef` function that checks if already bound -> does nothing, otherwise bind as normal.

### Describe alternatives you've considered

Some API method that returns if provided key has already been bounded. Then I can just write an if statement when binding.

**Comment by posva** [comment]
Note to myself: document how to have global bindings by using pinia

**Comment by posva** [comment]
Documented at https://vuefire.vuejs.org/cookbook/subscriptions-external.html
