### ISSUE TITLE
Firebase v4.0?

### ISSUE THREAD

**Issue by RafaelPlantard** [vuejs/vuefire#102]
Any way to use with `<script src="https://www.gstatic.com/firebasejs/4.0.0/firebase.js"></script>`?

**Comment by posva** [comment]
Doesn't it work? I checked the changelog and it seemed like breaking changes were ok for vuefire but I may have missed something

**Comment by Mark-L6n** [comment]
FYI, the npm version needs updating for Firebase v4.0.  Running `npm install firebase vuefire --save` gave warning 
`npm WARN vuefire@1.4.2 requires a peer of firebase@^2.4.1 || 3.x.x but none was installed.`
since `firebase@4.0.0` was installed.

**Comment by posva** [comment]
yeah, it's just a warning 😛. I'll have to change that, but I want to try out it works nicely first

**Comment by posva** [comment]
Fixed in latest release
