### ISSUE TITLE
Sometimes a single call to bindFirestoreRef causes the state to be set twice

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vuefire#1025]
### Reproduction

https://codesandbox.io/s/nameless-flower-b6puw?file=/src/App.vue

https://user-images.githubusercontent.com/533954/108911447-2c0c4f00-761f-11eb-96cb-8dbd088efc86.mov

### Steps to reproduce the behavior

1. Go to https://codesandbox.io/s/nameless-flower-b6puw?file=/src/App.vue
2. Open the console
3. Keep on clicking on *"Get ${num} todos" buttons*

### Expected behavior

Messages are logged in the console:

Example expected output:
```
Action called {limit: 30}
Todos getter recompute. results count: 30

Action called {limit: 10}
Todos getter recompute. results count: 10

Action called {limit: 30}
Todos getter recompute. results count: 30

Action called {limit: 20}
Todos getter recompute. results count: 20

Action called {limit: 20}
Todos getter recompute. results count: 20

// and so on
```

### Actual behavior

**Sometimes** after the `bindTodosRef` action is called, the `todos` getter recomputes twice. You need to be patient and keep on clicking on  *"Get ${num} todos" buttons* until it happens.

Example output:

```
Action called {limit: 30}
Todos getter recompute. results count: 30

Action called {limit: 10}
Todos getter recompute. results count: 10 <--  getter recomputed twice with the same date
Todos getter recompute. results count: 10

Action called {limit: 30}
Todos getter recompute. results count: 30

Action called {limit: 20}
Todos getter recompute. results count: 12  <-- getter recomputed twice - first execution resolves with just a partial date
Todos getter recompute. results count: 20

Action called {limit: 20}
Todos getter recompute. results count: 20
```

### Additional information

I spent a while on debugging this issue and went through `vuexfire` source code. I'm not 100% sure but it seems to me that the issue is related to how `onSnapshot` works. `onSnapshot` callback runs (at least) twice: first in returns from-cache data, then, after a fraction of a second, it's called with the "real" Firestore data.

``` js
ref.onSnapshot((snap) => {
  console.log(snap.metadata.fromCache);  // returns `true` on the first call and `false` on subsequent calls.
})
```

So, I have a feeling that the reason why the getter recomputes twice is that first recomputation takes place on from-cache data read and the second one happens when the "real" data is read from the actual database.

I suppose that the reason for the number of documents being different for the first and for the second call is that local cache not always contains all the documents that the query is expected to receive. The first call returns all the cached documents that match the query criteria and the second call returns the actual documents from the remote database.

### Issues caused by this bug

Normally, because of Vue reactive nature, this bug doesn't cause any issues because on the second call the data is always correct, so the component that relies on that getter will simply re-render with new data (a user might not even notice the redraw), but it might be problematic in the following scenarios:
- **If, instead of relying on a getter, we read the result of the action call**.  in such a case we might receive cached date instead of the actual data. 
- **If the amount of data is significant**. In such a case component rendering might be expensive. 2 recalculations of a getter cause the data to be render twice instead of once. This may have an impact on performance.

In the app we're working on we're experiencing both issues.

**Comment by posva** [comment]
You need to pass `reset: false` alongside `wait: true`. This is the default in v3
