### ISSUE TITLE
Manipulate data before rendering

### ISSUE THREAD

**Issue by holmesadrianh** [vuejs/vuefire#1028]
Hi there,

I would like to manipulate the data before rendering. The following seems to render the data in realtime, which is ideal, however, I would like to group the returned data in very specific ways:

`firestore() {
    const userId = firebase.auth().currentUser.uid;
    return {
      data: db.collection("users").doc(userId).collection("entries"),
    };
  },`

Is there a way to manipulate the returned data before rendering?

**Comment by posva** [comment]
See https://vuefire.vuejs.org/api/vuefire.html#firestoreplugin
