### ISSUE TITLE
Suggestion: Add a README comment warning people away from vue-fire

### ISSUE THREAD

**Issue by crrobinson14** [vuejs/vuefire#103]
I just went on a goose chase trying to get VueFire working in a project. I was getting all kinds of strange errors with no references to them in open/closed issues here, S/O, etc. It turns out I had installed the `vue-fire` NPM, a module with a nearly identical name but a very different approach and hasn't been maintained in 3+ years.

I suggest adding a brief comment/callout in the README about this module and the fact that they're not the same. There are some old blog posts and such that reference this other module and I suppose I won't be the last person who gets confused by them!

**Comment by posva** [comment]
I created an issue in their repo to mark it as deprecated when installing it 🙂 
Thanks for letting me know
