### ISSUE TITLE
Vuexfire doesn´t update state

### ISSUE THREAD

**Issue by TomHeckl** [vuejs/vuefire#1033]
I have some problems with vuexfire updating the binded state-var.
I can see the changes in the database at the VUEX console in the Target-Array. It is up to date, but the changes are not provided to the state-var.
What´s wrong with my code?
`
const vuexfire_store = new Vuex.Store({
	strict: true,
    state: 
    {
		fahrschueler: [],
    },
	modules: {
		
	},
    mutations: Vuexfire.vuexfireMutations,

	actions: {
		bindStudents: Vuexfire.firestoreAction(context => {
			  // return the promise returned by `bindFirestoreRef`
			  return context.bindFirestoreRef('fahrschueler', db.collection('Fahrschueler'))
			}) 
	},
    getters :{
      get_students(state) {
      	return state.fahrschueler;
    
	  }
	}
});`

**Comment by vuvgaG** [comment]
same
