### ISSUE TITLE
Storage reference error: Error in created hook: "TypeError: source.on is not a function"

### ISSUE THREAD

**Issue by ivangrimaldo** [vuejs/vuefire#104]
Hi everyone, I create a reference storage: 

```
var fireApp = firebase.initializeApp(config);
var storage = fireApp.storage();

new Vue({
  firebase: {
    storage: storage.ref('gallery');
  }
});
```
But the script stops with the next error:

vue@2.3.3:440 [Vue warn]: Error in created hook: "TypeError: source.on is not a function"

A couple of questions:

1.- Did I made some mistake in my declarations?
2.- Does vuefire support storage references?

Thanks, guys have a nice day.

**Comment by posva** [comment]
Hey! No, it doesn't support storage references, you don't need to bind it to Vue, you can use Firebase directly 🙂

**Comment by ivangrimaldo** [comment]
thank you @posva :)
