### ISSUE TITLE
Using a variable ref, where/when to call?

### ISSUE THREAD

**Issue by yipcma** [vuejs/vuefire#105]
Currently I set a static db.ref with a string, however, i'd like to fetch that string from a user DB so different users have a different db.ref. How should I best do this? where/when should i make the db call and set that ref-string? I currently put the watcher in created().

Thanks a lot in advance.

**Comment by posva** [comment]
You can use `$bindAsArray` to dynamically bind refs. Don't forget to unbind first! There's more info in the readme

**Comment by yipcma** [comment]
Thank you very much for the quick response. May I ask for a clarification?
- Where (created? mounted?) should i fetch the userId to make the ref and bindAsArray? 
- How about the refs in the watchers (set in watch) as they would not have been initialized?

Thank you again for helping out.

**Comment by yipcma** [comment]
very interesting, so i put the dynamic binding, followed by setting up watchers, in a callback in created(), but mounted and everything else keeps going without waiting for my async function to complete, leading to my computed values (based on the dynamic ref) to throw error. I'm curious how best I structure my various things and where to put them:

- an async call to fetch userId
- dynamic binding to user = dbref + /userId
- setting up watcher for 'user'
- computed values based on values in 'user'

Thanks a ton for your help.

**Comment by yipcma** [comment]
issue solved, basically do everything (fetch id, $bindAsArray, $watch) in created without using ref.once.

**Comment by posva** [comment]
if you're using them in the created hook, you can also use the function format of the firebase option 🙂

**Comment by yipcma** [comment]
the problem is with my async call which is hard to know when it will get done... and i don't know when firebase(){} gets done either...
