### ISSUE TITLE
Join Operation

### ISSUE THREAD

**Issue by nratifainah** [vuejs/vuefire#107]
Hi, 

Im wondering is it possible to do "join" operation with vuefire?

for example 
Books : {
book-1: {
title: Book Title #1
authorID: 1 
}.
book-2:{
title: Book Title #2
authorID: 1 
}
}

Author: {
1 : {
name: Author 1
},
2: {
name: Author 2
}
}

**Comment by posva** [comment]
It's actually unrelated to vuefire. These video series may help: https://www.youtube.com/watch?v=sKFLI5FOOHs

**Comment by nratifainah** [comment]
I mean is there any way to bind data with "join"? If I want to get list of books with author.

I can get list of books with this code, but I can not get author name:
this.$bindAsArray('allBooks', firebase.database().ref('books/')

**Comment by posva** [comment]
No, there's no way of doing this directly with vuefire 🙁

**Comment by nratifainah** [comment]
noted, thank you for your reply :)
