### ISSUE TITLE
Retrieving individual node values based on key?

### ISSUE THREAD

**Issue by juanfabrega** [vuejs/vuefire#108]
Hi,

I'm pretty new to Vue and Firebase, yet until now I'd had no major pain points thanks to the excellent documentation throughout. Lately I have struggled retrieving firebase data, see below.

In all of my components I've been able to pull my dataset without issue but ONLY when retrieving a full array of items and iterating with v-for. I understand how and why this works, since I'm getting an array returned, and all key-value pairs match in the individual objects. 

In a different component I'm looking to actually pull individual values from each of the nodes, rather than a complete array, but I've yet to do that successfully. 

My data looks like this:
```
group: {
    { subgroup1: {
        property1: 'string',
        property2: num,
        property3: bool
        }
    },
    { subgroup1: {
        property1: 'string',
        property2: num,
        property3: bool
        }
    }
}
```

My component code looks like this:
  ```
import` db from '../db'

  const subgroupRef = db.ref('group/subgroup1');

  export default {
    name: 'MyComponent',
    firebase: {
      subgroup: subgroupRef
    },
```

My expectation was to be able to pull values of specific keys within my template with a simple {{ subgroup.property1 }} declaration but whenever I do this nothing comes back in the front-end, and the console.log for this.subgroup.property1 returns undefined.

I know the data is coming back because when I do a console.log for this.subgroup I get an array of objects with all the key-value pairs as expected. I'm just wondering how to best bind them or retrieve them individually in the front-end. 

I have read all the docs, but like I said I'm fairly new to this and couldn't find a clear answer for my self, so I would greatly appreciate any help. I'm sure I'm neglecting something super simple, but I'm really struggling to figure out what that is.

Thanks so much!

**Comment by posva** [comment]
Hi!

You have to use `asObject: true` when passing the ref to the `firebase` property if you want to get the items as an object instead of an array.
If you want to select a specific child by using its key in firebase, you can use `ref.child(key)`

**Comment by juanfabrega** [comment]
Thanks so much, this worked perfectly.
