### ISSUE TITLE
Vue3 / Firebase 8 support

### ISSUE THREAD

**Issue by gqoew** [vuejs/vuefire#1088]
Hello 👋 

First, let me thank you for building this amazing library. Vuefire is great

I see in the README file that you are working on the support for Vue 3 / Composition API and Firebase 8.
Can you provide us with more details on a potential release date?

Thanks!

**Comment by jaytonic** [comment]
I've the same issue, I've to start soon a new project where the backend has to be firebase, I wish I could use composition API. Any idea this will released?

**Comment by mhirsch** [comment]
`npm` is now reporting vulnerabilities in the Firebase 7 dependency chain

```
# Run  npm install firebase@8.6.5  to resolve 28 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Uncontrolled Resource Consumption                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ @firebase/util                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ firebase                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ firebase > @firebase/analytics > @firebase/installations >   │
│               │ @firebase/component > @firebase/util                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1717                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

Is there a place to track the status of Firebase 8 support? Is it possible to split it from Vue 3, if that's the issue? Changes from Firebase 7 to 8 are not huge. Mostly around module type.

**Comment by jaytonic** [comment]
@mhirsch and @gqoew Checking the commit history, I'm a bit concerned that vuefire seems to be unmaintained since the end of 2020 😭

**Comment by posva** [comment]
The v3 of Vuefire should work with Vue 2/3 (Composition API) and Firebase 8: https://github.com/vuejs/vuefire/tree/v3

I wish I could give this package more time but the truth is I've never received funding from any company using Vuefire, nor Firebase/Google so I currently prioritize the other packages I help with: Vue, Vue Router, vitepress, pinia, etc
I will likely be able to work more on Vuefire during July or August.

**Comment by jaytonic** [comment]
@posva I'm sorry, I'm quite new to this ecosystem, but is this something I can use through NPM? Or it's some kind of manual install?

**Comment by posva** [comment]
You can use it with `npm install vuefire@next`. You will need to check the examples as I haven't been able to update the docs yet https://github.com/vuejs/vuefire/blob/v3/examples/firestore.html

**Comment by mhirsch** [comment]
Seems a little harsh to mark my comment as spam -- there's dependency rot on the main published version of the package. How is pointing that out spam?

**Comment by fmikaelian** [comment]
> You can use it with `npm install vuefire@next`. You will need to check the examples as I haven't been able to update the docs yet https://github.com/vuejs/vuefire/blob/v3/examples/firestore.html

Hi @posva 

Thank you for updating us on this, I understand your situation

Let us know if it evolves this summer 

Best

**Comment by web2033** [comment]
Maybe skip v8 and go with v9 then?
https://firebase.google.com/docs/web/modular-upgrade

The fully modularized version 9 has these advantages over earlier versions:

- Version 9 enables a dramatically reduced app size. It adopts the modern JavaScript Module format, allowing for "tree shaking" practices in which you import only the artifacts your app needs. Depending on your app, tree-shaking with version 9 can result in 80% less kilobytes than a comparable app built using version 8.
- Version 9 will continue to benefit from ongoing feature development, while version 8 will be frozen at a point in the future.

**Comment by ramsrib** [comment]
v9 doesn't support [firebase-ui](https://github.com/firebase/firebaseui-web/issues/837) yet, so that might be a blocker.
