### ISSUE TITLE
AsObject not binding as actual object

### ISSUE THREAD

**Issue by FranzSkuffka** [vuejs/vuefire#11]
When I bind as an object, I will still have to iterate through the object to access my values.

**Comment by jwngr** [comment]
Can you explain what exactly you mean here? Please include some example code.

**Comment by FranzSkuffka** [comment]
The following line is necessary:
https://github.com/FranzSkuffka/innovant/blob/firebase-wip/app/components/editor.vue#L3

Currently, whether I use the `asObject` option in a firebase binding does not make any difference in the template. When I inspect (`log`) my `innovation` data, I either get `[{myDataObject}]` or `{'key':{myDataObject}}`. What I want is just `{myDataObject}` as I expected when enabling the `asObject` option.

**Comment by jwngr** [comment]
I may need to defer to @yyx990803 on this one, but one thing that strikes me as odd is the fact that you are re-using the same variable for the iterator and iteratee in your `v-for`. Instead of:

`.hack(v-for='innovation in innovation')`

you probably want something like:

`.hack(v-for='key in innovation')`

That way, you won't have a conflict over what `innovation` actually refers to.

**Comment by FranzSkuffka** [comment]
Thank you for the hint. I think shadowing the variable with same name made it more readable.

**Comment by posva** [comment]
Hi @FranzSkuffka, I hope you've already dealt with the issue 😄 
Looking at your code firebase is a function instead of a plain object. Have you tried that along with the `asObject` option set to `true`?

**Comment by FranzSkuffka** [comment]
No, I have not resolved it yet. I tried that though. Because here firebase is used in a subcomponent, the data attribute needs to be a function. If I have misapplied this to the firebase plugin that's my fault. I did not work on it any further because I was merely playing around and the project requirements did not include a remote DB.

**Comment by posva** [comment]
Then I suppose we can close this issue. It have been inactive way too long anyway 😛
