### ISSUE TITLE
Best way to do subsequent calls 

### ISSUE THREAD

**Issue by whicher** [vuejs/vuefire#110]
Hi there,

This is more like a question rather than an issue. I have a firebase node which holds the index containing post ids and i have a node holding actual posts keyed by this post id. So for each index I first fetch the corresponding post ids and then I need to fetch the actual post info from another node.

Flow is something like this:

ref: `/index/cat_pics`
result: `[1,2,3]`

ref: `/posts/1`
result: `{id:'', title:''}`

ref: `/posts/2`
result: `{id:'', title:''}`

ref: `/posts/3`
result: `{id:'', title:''}`

I've already been able to fetch ids in their readyCallback I can programmatically generate post refs. How can I push them to html?

```javascript
firebase: {
    ids: {
      source: ref,
      readyCallback: function () {
      }
}
```

What is the best way to do this?

**Comment by posva** [comment]
Using the readyCallback should work but if you don't need to save the whole list of posts you can get all the posts and then fetch from other nodes by binding again object (`$bindAsObject`). To render it in html, use something like a v-for, it depends on your data. You can take a look at the example folder for more help
