### ISSUE TITLE
How to instantiate a binding with a dynamic path (e.g. using a prop value)

### ISSUE THREAD

**Issue by mismith** [vuejs/vuefire#112]
I know I can use the function syntax to instantiate my `$firebaseRefs` using `this` values, e.g.:
```
export default {
  props: {
    user: Object,
  },
  firebase() {
    return {
      invites: firebase.database().ref(`users/${this.user.uid}/invites`),
    };
  },
};
```
But what if the `user` prop, in this case, is asynchronous, and won't be loaded when this component is mounted? (i.e. `this.user.uid === undefined`, causing this `ref()` call to fail)

I tried using a watcher within `created()`, but this also fails since it doesn't fire (the second time) when changing routes. e.g.:
```
export default {
  props: {
    user: Object,
  },
  created() {
    this.$watch('user', (user) => {
      if (user && user.uid) {
        this.$bindAsArray('invites', firebase.database().ref(`users/${user.uid}/invites`));
      }
    });
  },
};
```

Thoughts? This is a very common problem I run into—since what firebase paths in a production app are ever simple fully-read-accessible (e.g. just `/users`, which is trivial to bind with `vuefire`)?

**Comment by posva** [comment]
I don't see why it doesn't work for you but using a watch should work out. I recommend you to try the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Providing a small fiddle or playground could will also make it easier for people to help you 🙂

**Comment by mismith** [comment]
You were right, the `created()` method did work, the watcher just wasn't firing on the first load since `{immediate: true}` wasn't set on the watcher. 
For other's sake, here's what it should have been:
```
export default {
  props: {
    user: Object,
  },
  created() {
    this.$watch('user', (user) => {
      if (user && user.uid) {
        this.$bindAsArray('invites', firebase.database().ref(`users/${user.uid}/invites`));
      }
    }, {
      immediate: true,
    });
  },
};
```

**Comment by mismith** [comment]
Also, in a very related concern: do you (@posva et al) see any value in supporting Promises within the `source` option of `vuefire`? That would essentially do what I want in a much cleaner way, but I'm wondering if this is an anti-pattern somehow. It seems like it would save a ton of boilerplate since I wouldn't haven't to manually `$bindAsArray`/`Object`

e.g.
```
export default {
  ...
  firebase: {
    anArray: {
      source: doAsyncFetch().then(data => firebase.database().ref(`/path/with/${data}`))
    },
  },
}
```

**Comment by posva** [comment]
I don't think it adds much value because the point of doing `$bind*` is handling any other case, thus Promises as well

**Comment by mismith** [comment]
True, but isn't the point of VueFire to reduce the overhead/boilerplate required to use Firebase within Vue?

Maybe I'm missing something more important: what is the best way to handle dynamically linking firebase refs? As far as I can tell, the built-in behaviour is only really useful for accessing public top-level collections, which, as I mentioned above, I can't really see many use cases for in an actual production app. Or am I misunderstanding?

**Comment by posva** [comment]
> True, but isn't the point of VueFire to reduce the overhead/boilerplate required to use Firebase within Vue?

Yes, to a certain extent.
There's no best way 😅 
Some people will create a HOC to handle promises as props, others will do as you, in the `created` hook
