### ISSUE TITLE
`firestoreBind` creates a `value` property

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vuefire#1123]
### Reproduction

``` js
import Firebase from 'firebase';
import { firestoreBind } from 'vuefire';
import { defineStore } from 'pinia'

defineStore({
  id: 'user',

  state: () => ({
    user: {},
  }),

  getters: {
    userProfile(state) {
      console.log(state.user);
      /** Logs:
       *
       * {
       *   value: {
       *     // user data
       *   }
       * }
       *
       */

      /** Expected:
       *
       * {
       *   // user data
       * }
       *
       */

      return this.state.user;
    },
  },

  actions: {
    init(userId) {
      const userDocRef = Firebase.firestore().collection('users').doc(userId)
      return firestoreBind(this.user, userDocRef);
    },
  },
});
```

### Steps to reproduce the behavior

1. Use `firestoreBind()` to bind a document to a store property.
2. The document is bound as expected

### Expected behavior

The document should be bound directly to the property passed as a first parameter of the `firestoreBind` function

### Actual behavior

A new `value` property is created under the property to which the document was bound.

### Additional information

I'm not 100% sure if this is a bug. I thought that `state` is already a reactive object so there's no need to create nested reactive refs when binding Firestore documents, but I suppose that `firestoreBind()` is not able to recognize that `this` is already a reactive object so it creates a new `ref` under `this.user`. Am I right?

Or maybe I'm just not using it properly with Pinia?

**Comment by posva** [comment]
You need to do `firestoreBind(toRef(this.$state, 'user'), userDocRef)`

**Comment by wujekbogdan** [comment]
Thanks! So we can close this ticket - it's clearly not a bug.
