### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by luzdealba** [vuejs/vuefire#1136]
### What problem is this solving

I find myself checking this repo from time to time to check if either support for Vue 3 has been released, or for related updates (maybe there's a roadmap somewhere and I missed it, if so please point me in the right direction).

### Proposed solution

I know I can follow releases but that still doesn't tell me how long (approximately) for that given release, which is something we occasionally need in order in order to plan ahead.

A simple wiki article or even a short section on the README should do it.

### Thanks!

Thanks many for the good work  🙏  I hope this didn't sound pushy, it's not meant that way; however long the wait is okay, it'd just be good to know  :)

**Comment by posva** [comment]
Hello, I'm glad you like Vuefire. Currently, Vue 3 support is on the `next` branch. I haven't been able to dedicate any more time to it because I'm busy with other libraries in Vue Ecosystem like the router, vue, pinia, etc, and the rest of my time on freelance gigs to live. After more than 4 years of maintaining Vuefire, I haven't received much financial support for it. A sponsor of the project (ideally one or multiple companies using this in production and not just individuals) would definitely help me to keep the library up to date with all the changes in Firebase. It would also allow them to get some visibility and prioritized help with issues.

Right now, I really don't know when I will be able to spend more time on the project. I know I will do it next time I want to build something using the new version of Firebase but that could be weeks or months because it happens in my free time.

**Comment by luzdealba** [comment]
Hey @posva , I get it--btw, many thanks for the update.

**Comment by nhendriksen** [comment]
> After more than 4 years of maintaining Vuefire, I haven't received much financial support for it. A sponsor of the project (ideally one or multiple companies using this in production and not just individuals) would definitely help me to keep the library up to date with all the changes in Firebase. It would also allow them to get some visibility and prioritized help with issues.
> 
> Right now, I really don't know when I will be able to spend more time on the project. I know I will do it next time I want to build something using the new version of Firebase but that could be weeks or months because it happens in my free time.

Hi - great respect for your support to the Vue ecosystem. What level of sponsorship do you need to dedicate more time to Vue3 + Firebase 9 and keep up with future releases? 

Best regards, Nikolaj

**Comment by tohagan** [comment]
Bonjour Eduardo (@posva) ...  I've started to develop a library to fill the shoes of VueFire / VuexFire for Vue3 / Firestore v9 with support for Pinia. It's a complete rethink / rewrite for TypeScript & Vue 3. I plan to support the same features (and a few more). It's currently in a private GitHub project until the testing is all working. Still needs lots docs & demos. I was keen to add an acknowledgement of your contribution to the README.

I've really developed this out of my own urgent project needs and I don't really wish to "compete" ... so I'm wondering if you'd like to join me as a contributor in this project to act as an advisor / code reviewer or really in any way you'd feel comfortable with that was not too taxing on your other projects.  I'm hoping this might perhaps take a concern off your shoulders, remove any doubt that we're competing and keep you involved and clearly credited!  It also might help best support Vue / Firebase communities by providing a much needed upgrade path.

I had a look at a few other related projects on GitHub but none were really close to the full features of  VueFire / VuexFire - especially not subscribing nested `DocumentReference` and `CollectionReference` . I've been keen to ensure that upgraders can find all the same good oil. 

You can chat to me via Twitter: 
- https://twitter.com/tony_ohagan

Here's a bit more about me 
- https://www.linkedin.com/in/tonyohagan/
- https://stackoverflow.com/users/365261/tony-ohagan

**Comment by liquidvisual** [comment]
@tohagan This sounds great! Not having a V3 compatible Vuexfire makes it difficult to migrate our project. I was considering using [Vue Use](https://vueuse.org/firebase/useFirestore/) in the short term, but I'm not even sure if it'll easily plug into Pinia? Best of luck with your library! 🔥

**Comment by tohagan** [comment]
Initial MVP would be Firestore only, covers VueFire/VuexFire features in one library, type-safe objects (TypeScript) if you care, tree-shaking and a few nice performance improvements.

**Comment by wujekbogdan** [comment]
Is `vuefire` discontinued? 

We're going to migrate to our application from Vuex to Pinia and I'm not sure what's the best way to implement Firestore bindings. Shall I use `vuefire@next` [as I used it here](https://github.com/vuejs/vuefire/issues/1123) having in mind that the official release is going to happen at some point or shall I rather go for [`@vueuse/firebase`](https://vueuse.org/firebase/usefirestore/#share-across-instances) or a custom implementation based on the official Firestore SDK?

**Comment by luzdealba** [comment]
> (...) or shall I rather go for [`@vueuse/firebase`](https://vueuse.org/firebase/usefirestore/#share-across-instances) (...)?

I've found that for all intends and purposes (essentially getting real time updates from documents and entire collections) the reactive bindings provided by [useFirestore](https://vueuse.org/firebase/usefirestore/) work like a breeze.  They're both, Vue 2 and Vue 3 compatible with the very same package ([@vueuse/firebase](https://www.npmjs.com/package/@vueuse/firebase), which is [actively mantained](https://github.com/vueuse/vueuse/commits/main).

**Comment by liquidvisual** [comment]
@wujekbogdan What lib did you end up going with? Also how did you go with integrating with Pinia?

**Comment by wujekbogdan** [comment]
We're still using Vuex in that project where we planned Pinia migration, but If I were to choose a solution I would probably go for `@vueuse/firebase` as it's the only actively maintained package that provides Firestore bindings for Vue.

But that's just a feeling, I didn't test it enough to have a strong opinion.

**Comment by Hibrix-net** [comment]
> We're still using Vuex in that project where we planned Pinia migration, but If I were to choose a solution I would probably go for `@vueuse/firebase` as it's the only actively maintained package that provides Firestore bindings for Vue.
> 
> But that's just a feeling, I didn't test it enough to have a strong opinion.

Probably not as actively maintained as @vueuse/firebase but this will avoid the refactors if you are already on Vuexfire: https://github.com/vuejs/vuefire/issues/999#issuecomment-1019281684

I use it and it works like a charm.

**Comment by ptc-tonyo** [comment]
The problem with `@vueuse/firebase` is that for queries and collections, it replaces the entire bound array for every snapshot update. This can kill your rendering performance as the array size grows.  See [useFirestore/index.ts line 94](https://github.com/vueuse/vueuse/blob/ec3383cd9e1de3b1955ed71d1c114145f6638e7d/packages/firebase/useFirestore/index.ts#L94). In contrast, VueFire/VuexFire and my new API use incremental caching.

**Comment by liquidvisual** [comment]
@ptc-tonyo Is the @next branch no longer available for use? My app relies on big Firebase collections so VueUse would probably kill the performance. I'm thinking of moving to React just because nothing is available right now for Vue 3 :(

**Comment by Hibrix-net** [comment]
> @ptc-tonyo Is the @next branch no longer available for use? My app relies on big Firebase collections so VueUse would probably kill the performance. I'm thinking of moving to React just because nothing is available right now for Vue 3 :(

There is something available, but not official, just see my comment from above.

**Comment by liquidvisual** [comment]
@Hibrix-net Cheers, I'll use that for now

**Comment by Hibrix-net** [comment]
> @Hibrix-net Cheers, I'll use that for now

I'm glad you'll use it. Believe me, this saved my life for now.

**Comment by tohagan** [comment]
I'm sorry my lib is still in development for now. I'm chipping away at it on my own time and won't release until it's fairly stable.

**Comment by posva** [comment]
Thanks everybody for the feedback 🙏.
Sorry @tohagan I didn't get back to you, I just couldn't find the time but I'm glad you build your own version.

I'm currently migrating the library and I hope to start releasing alphas soon. You can follow the advancement at https://github.com/vuejs/vuefire/issues/1241
