### ISSUE TITLE
maxRefDepth applying to new items

### ISSUE THREAD

**Issue by sammypanda** [vuejs/vuefire#1162]
### What problem is this solving

When getting refs as objects using maxRefDepth, new refs that are added to an array are not treated the same. Instead are just stored as a string that can be used to fetch the reference.

### Proposed solution

Have maxRefDepth also automatically convert the expected ref fields for newly added items.

### Describe alternatives you've considered

I've considered triggering the bind again so that it updates the newly added item, but this isn't ideal and refreshes everything else. I've also thought about using the id of the newly added item when it's created to bind it manually. But i'm not sure how to implement that, or if it would work with collection binding and unbinding- mainly the problem is this wouldn't work for other clients; only the one that is responsible for creating the ref item.

**Comment by posva** [comment]
This should work so if you are still seeing this problem with the latest vuefire@next, please open a new issue with a reproduction or try reproducing it in the playground of the `main` branch
