### ISSUE TITLE
Support binding to array for nested states

### ISSUE THREAD

**Issue by kraeki** [vuejs/vuefire#1172]
### What problem is this solving
It allows to decide whether a a firebase field is bound as object or array also for nested states. 

Today vuexfire will bind as object if the vuex state is initialiezed with `{}`. If its initialized with `[]`, then vuexfire will bind the firebase reference as array. The problem is that this works only for top level states. With this issue it would be great to get the same behaviour for nested states.

Workaround: 
- Bind as object `{}` then implement a getter to transform the object into an array `[]`.
- Change ids of your firebase realtime database to numbers. This way vuexfire will bind as array `[]`

**Comment by posva** [comment]
Do you have some code samples? I'm not sure if is needed on the current version of VueFire
