### ISSUE TITLE
`id` field added by the default `serialize` function is not enumerable

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vuefire#1191]
### Reproduction

- Bind a document or a collection with
- Do not use a custom `serialize` function

### Expected behavior

- `id` field is added to each document if it does not exist in Firestore.
- `id` field is enumerable.

### Actual behavior

`id` field is added but it's not enumerable.

Because of this if we do:

``` js
const myData = {
  ...data, // where `data` is a bound document
}
```
then `myData.id === undefined`

### Additional information

It happens because of the following code:

``` js
export function createSnapshot(doc: firebase.firestore.DocumentSnapshot): TODO {
  return Object.defineProperty(doc.data() || {}, 'id', { value: doc.id })
}
```

which should be:

``` js
export function createSnapshot(doc: firebase.firestore.DocumentSnapshot): TODO {
  return Object.defineProperty(doc.data() || {}, 'id', { value: doc.id, enumerable: true })
}
```

because `enumerable` is `false` by default.

**Comment by wujekbogdan** [comment]
I've just found that this is not a bug - it's intentional. Let's not close this PR though - please treat it as a feature request for the docs. It would be great if this information was clear in the docs.

**Comment by posva** [comment]
Feel free to open a PR to the docs 👍
