### ISSUE TITLE
Remote DB does not get updated on edit

### ISSUE THREAD

**Issue by FranzSkuffka** [vuejs/vuefire#12]
The remote changes are mirrored locally, but not the other way around.

**Comment by jwngr** [comment]
This is not actionable without a code repro. Please create an [mcve](http://stackoverflow.com/help/mcve) using Plunkr or JSFiddle which shows the issue. Until then, I'm going to close this as non-actionable. Feel free to re-open once you've got an mcve.

**Comment by FranzSkuffka** [comment]
Excuse me, I was hoping for a quick hint that could resolve my issue. Here's the clarification:

Application Prototype:
http://database-administrator-fish-77350.netlify.com/

Observed behavior:
- insert of new entry is working; clicking _new innovation_ results in an update of the remote database. [Implementation](https://github.com/FranzSkuffka/innovant/blob/firebase-wip/app/components/overview.vue#L29)

- when launching the edit view for an entry (note that the query receives a route param; related to other issue), the data gets pulled and bound to the data object. When we change the data the reactive model is updated but not persisted in the remote database.

**Comment by FranzSkuffka** [comment]
BTW I want to re-ope this issue.

**Comment by jwngr** [comment]
Hey @FranzSkuffka - Unfortunately we don't have time to debug a full application. If I had to bet, you have an issue with your application code. You can probably figure out the bug by removing some code and creating an [mcve](http://stackoverflow.com/help/mcve) on something like JSFiddle or Plunkr. If you do that and the issue still repros, we will re-open this issue again.
