### ISSUE TITLE
the context in cancelCallback is not vm

### ISSUE THREAD

**Issue by jkiimm** [vuejs/vuefire#120]
Hi, @posva. I've faced the error below:

```
Uncaught TypeError: Cannot set property 'serverError' of null
    at cancelCallback (eval at <anonymous> (app.bundle.js:4921), <anonymous>:206:28)
    ...
```

`serverError` is just a flag variable from component data. So, I check out the source and guess it might be trouble [`cancelCallback` is not handled with `cancelCallback.bind(vm)`](https://github.com/vuejs/vuefire/blob/master/src/vuefire.js#L136-L156). Whereas [`readyCallback` is binded with `vm`](https://github.com/vuejs/vuefire/blob/master/src/vuefire.js#L104) and working fine. Is it intended?

**Comment by posva** [comment]
It wasn't thought that way in the first place. I guess we didn't realise because is so common to use arrow functions inside of the methods that `this` is automatically bound to `this`.
I'm happy to take a PR for that (https://github.com/vuejs/vuefire/blob/master/src/vuefire.js#L99-L101) with the corresponding test of course 🙂

**Comment by jkiimm** [comment]
Yep, it is so common to use arrow functions nowadays. But I think it is little confusing `readyCallback` and `cancelCallback` context are different.

I have trouble reproducing a test that calls `cancelCallback`. According [the document](https://firebase.google.com/docs/reference/js/firebase.database.Query#on), The callback is called when a client does not have permission. But I have no access to the firebase db rules.

I have to implement the test by using sinon? Or occur actual permission error?

**Comment by posva** [comment]
Don't worry about the test, I don't even access myself to the database
