### ISSUE TITLE
Chat example with auth.

### ISSUE THREAD

**Issue by allenhwkim** [vuejs/vuefire#123]
Hi, thanks for the great work.

I have worked chat example with Google auth. enabled.
http://plnkr.co/edit/uc8CAE?p=preview

If this code is fine, I want to make PR to be stored to `examples/chat-app/auth.html`

**Comment by posva** [comment]
Hey, that's a nice initiative. I quickly tested it and it's not working though.
I think examples are quite simple to demonstrate vuefire features, but authentication goes beyond vuefire's scope. It really is about Firebase, so I think it's not necessary to add such example to vuefire
