### ISSUE TITLE
Is this project dead? When can we expect a WORKING release with Vue 3 support?

### ISSUE THREAD

**Issue by khteh** [vuejs/vuefire#1231]
@posva You just keep closing many of these issues here and you know that `vuefire@next` does NOT work because we can NOT install it with Vue 3! All active branches are `dependenbots`. The rest are stale branches.

https://github.com/vuejs/vuefire/issues/1072
https://github.com/vuejs/vuefire/issues/1225
https://github.com/vuejs/vuefire/issues/1230
https://github.com/vuejs/vuefire/issues/898

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vuefire/issues/1230

**Comment by posva** [comment]
Don't open a spam issue again or we will have to block you.
