### ISSUE TITLE
$bindAsObject and $bindAsArray as promises

### ISSUE THREAD

**Issue by natezerk** [vuejs/vuefire#125]
It would be much nicer instead of using ready and cancel callbacks to implement these methods as promises. This would also allow better chaining for multiple calls using `Promise.all`

**Comment by posva** [comment]
That's true, I could add the ready callback as a promise. I have to check what is currently supported as browsers to make sure it doesn't break anything.
However, the `cancelCallback` can happen multiple times, so there will probably not be any rejection

**Comment by posva** [comment]
FYI this already works for Firestore

**Comment by posva** [comment]
This is now implemented for RTDB too and will be released in next version
