### ISSUE TITLE
useCurrentUser() called before the VueFireAuth module was added to the VueFire plugin

### ISSUE THREAD

**Issue by Strift** [vuejs/vuefire#1260]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-hj5ssm?file=package.json,nuxt.config.ts,app.vue

### Steps to reproduce the bug

1. Open the Stackblitz
2. Update firebase config in `nuxt.config.ts`
3. Start dev server 

### Expected behavior

App running

### Actual behavior

Error

```
[VueFire] useCurrentUser() called before the VueFireAuth module was added to the VueFire plugin. This will fail in production.
```

### Additional information

Thanks for the package. Super happy to see Nuxt 3 integration is planned.

Apologies if the errors are due to my usage of it. 

I did try and search a lot before opening this issue, but I did not manage to find a solution. I "hope" it is indeed a bug and I'm not bothering you for nothing.

Cheers,

**Comment by posva** [comment]
This is because it wasn’t implemented yet 😅
It will be on the next release on the next few days

**Comment by noook** [comment]
It is still happening in `3.0.1` on a fresh project
