### ISSUE TITLE
Referenced documents do not have id

### ISSUE THREAD

**Issue by donatas-luciunas** [vuejs/vuefire#1263]
### Reproduction

N / A

### Steps to reproduce the bug

Use `useDocument` for a document that has at least one reference

### Expected behavior

Referenced document has `id` property

### Actual behavior

Referenced document does not have `id` property

### Additional information

I guess the fix should be somewhere here https://github.com/vuejs/vuefire/blob/ae85a41a4614c7b4b3526c79aebfb8ac8d6853fd/src/firestore/bind.ts#L123

A default converter should be added for `refs` here.

**Comment by michaelpelletier** [comment]
Thanks for posting this! I'd posted on the Vue Discord last night hoping to get an answer as to what I was doing wrong that useDocument was giving me the _content_ of the referenced items but not the actual ID.

**Comment by posva** [comment]
Note that if you only want the id, you can use `maxRefDepth: 0`

**Comment by michaelpelletier** [comment]
Yeah, I want both, though. The use case I was describing on the Discord is something like this:

> I have a `student` who has a collection of `current courses` that they are enrolled in this semester. On the student's Dashboad, for each of those courses, I can display the information like the course `title` or when it meets or who the professor is, but because I can't access the ID, I couldn't build a link to actually view that course's page.

**Comment by donatas-luciunas** [comment]
I recommend to fix it this way
This line https://github.com/vuejs/vuefire/blob/ae85a41a4614c7b4b3526c79aebfb8ac8d6853fd/src/firestore/utils.ts#L101 should be changed to 
```
refs[refSubKey] = ref.withConverter(firestoreDefaultConverter);
```

**Comment by posva** [comment]
yeah, that would be one way. I think we could also have an option for this that allows to use any custom converter and that by default uses the default converter. What do you think?

**Comment by donatas-luciunas** [comment]
Sorry, I mean `globalFirestoreOptions.converter` ([source](https://vuefire.vuejs.org/guide/global-options.html)) instead of `firestoreDefaultConverter`.
This way as you say a developer could provide a custom converter.

Providing custom converter per dependency could also be nice. In my head a solution could be additional `useDocument` options property `mask` that follows retrieved document structure while also providing instructions how to expand it, for example
```
{
  "converter": commentConverter,
  "$user": {
    "converter": userConverter,
    "$roles": {}  // instructs to expand with default converter
  }
}
```
Not mentioned fields should not be expanded. I use $ prefix for actual document fields.
This would also solve https://github.com/vuejs/vuefire/issues/281
This seems to me as a separate feature.

**Comment by posva** [comment]
The converter will likely be passed as an argument to be able to use local options.

I think that instead, allowing both the converter object and a function that returns a converter based on the ref or null to skip it could also enable this behavior in a more concise syntax:

```ts
useDocument(..., {
  refConverter: customConverter
})

useDocument(..., {
  refConverter: (docRef) => docRef.id.includes(...) ? null : customConverter
})
```

**Comment by donatas-luciunas** [comment]
Sure, that could work as well.

Could you please implement the use of `globalFirestoreOptions.converter` separately? This seems to be a quick fix. This is a blocker for me to migrate from v2 to v3 😬

**Comment by posva** [comment]
Unfortunately it will have to wait a bit. Use https://www.npmjs.com/package/patch-package and locally patch the package in the meantime, it should be pretty straightforward. v2 didn't have this behavior either

**Comment by posva** [comment]
Unfortunately it will have to wait a bit. Use https://www.npmjs.com/package/patch-package and locally patch the package in the meantime, it should be pretty straightforward. v2 didn't have this behavior either

**Comment by michaelpelletier** [comment]
Just popping back to say patch-package with donatas-luciunas's original suggestion worked like a dream.

**Comment by digitalkaoz** [comment]
hey @posva or @donatas-luciunas i just popped in with the same problem, i simply cant get the id in my resolved reference:

```ts
const coll = collection("projects").withConverter(globalFirestoreOptions.converter)
```

should be enough i guess, to have all subsequent calls to `useDocument` or `useCollection` resolve the ids as long as they are using the `coll` above?!

what am i missing here?

**Comment by digitalkaoz** [comment]
nvm, i found it (as it says in the doc, the `id` property is not enumerable)
