### ISSUE TITLE
Bind snapshot values to model

### ISSUE THREAD

**Issue by abiaad** [vuejs/vuefire#128]
Hello,

I'm stuck on a basic feature. 
I have a snapshot query like : 

`db.ref('items').orderByChild('subItems/' + key).equalTo(true).on('value', function (snap) {}`

I get results and create an array with them but I can't figure out how to update my model (and front-end part). I tried without success : 

`this.$bindAsArray('items', arrayOfItems) // arrayOfItems filled inside snapshot callback` 

What's wrong with my reasoning ? 

Thanks

**Comment by posva** [comment]
`this.$bindAsArray('items', db.ref('items'))`

Check the readme for more examples
