### ISSUE TITLE
@firebase/@app-types should not be installed

### ISSUE THREAD

**Issue by ottopaulsen** [vuejs/vuefire#1291]
### Reproduction

npm install @firebase/@app-types

### Steps to reproduce the bug

Run
```
npm install @firebase/@app-types
```

### Expected behavior

Install success

### Actual behavior

```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@firebase/" of package "@firebase/@app-types": name can only contain URL-friendly characters.
```

### Additional information

The doc for the `@firebase/app-types` package says:

> This package is not intended for direct usage, and should only be used via the officially supported [firebase](https://www.npmjs.com/package/firebase) package.

I assume the package should not be installed, so in that case the bug is in the [documentation](https://vuefire.vuejs.org/nuxt/getting-started.html#installation).

**Comment by arnaldoperez** [comment]
yet, in the nuxt.config.ts file, the types for the "vuefire" property are not detected in ts

**Comment by posva** [comment]
There was a typo in the installation notice. If it's not supposed to be installed, it shouldn't be listed as a peer dependency, but that has to be requested on firebase 😅
