### ISSUE TITLE
Items of binded list with $databaseBind() don`t have ".key" property but have "id"

### ISSUE THREAD

**Issue by Todosiienko** [vuejs/vuefire#1296]
### Reproduction

https://codesandbox.io/s/exciting-pare-1eit57?file=/src/App.vue

### Steps to reproduce the bug

Install vuefire latest version, firebase 9.15; 
Init reactive data and bind it to real time database with $databaseBind.

### Expected behavior

After data was successfuly binded every item of list should have property ".key"

### Actual behavior

After data was successfuly binded every item of list have property "id"

### Additional information

According this article https://v2.vuefire.vuejs.org/vuefire/binding-subscriptions.html#programmatic-binding, rtdb is using ".key" property, and firestore is using "id" property, but in my case list items have "id" instead of ".key"

**Comment by posva** [comment]
You are looking at the old version of the docs. Remove the v2 prefix

**Comment by Todosiienko** [comment]
Hello Eduardo, thanks for the quick response. I mentioned v2 docs because i
didn`t see any mentions about ".key/id" in v3 docs and i thought it just
still relevant for the latest version. Can you tell me please is it correct
that items of  binded list with real time database don`t have anymore
".key" property and always will have only "id" ? Thanks.

сб, 4 февр. 2023 г. в 19:01, Eduardo San Martin Morote <
***@***.***>:
