### ISSUE TITLE
useCurrentUser() composable not defined

### ISSUE THREAD

**Issue by jclaessens97** [vuejs/vuefire#1299]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-1wgfs6?file=auth.global.ts,package.json,nuxt.config.ts,app.vue

### Steps to reproduce the bug

1. npm install
2. check `middleware/auth.global.ts`

### Expected behavior

I should be able to use `getCurrentUser` as stated in the [docs](https://vuefire.vuejs.org/nuxt/auth.html)

### Actual behavior

getCurrentUser is `undefined`

**Comment by AKodkod** [comment]
I think the reason is missing `auth: true` in the config.

```typescript
export default defineNuxtConfig({
  modules: ['nuxt-vuefire'],
  vuefire: {
    auth: true, 👈 
    config: {
      apiKey: '',
      authDomain: '',
      projectId: '',
    },
  },
});
```

**Comment by wgbn** [comment]
Because the same thing happens to me, getCurrentUser() always returns **undefined** on the **server** (SSR).
And in my case the config has the `auth: true`

**Comment by javi-code** [comment]
> Because the same thing happens to me, getCurrentUser() always returns **undefined** on the **server** (SSR). And in my case the config has the `auth: true`

I have the same problem, the server does not return the user with the session
