### ISSUE TITLE
Support Firestore

### ISSUE THREAD

**Issue by laurentpayot** [vuejs/vuefire#131]
Breaking (pun intended) news: https://firebase.google.com/docs/firestore/rtdb-vs-firestore

Looks like a vuefire fork is needed…

**Comment by posva** [comment]
We'll see if I need to create another package, I hope I don't :)
This is something I'll look into

**Comment by kylestev** [comment]
I don't see any references to it being deprecated. Where is it stated that the realtime database is going away?

**Comment by posva** [comment]
No, it's not deprecated. Firestore is in beta

**Comment by ssijak** [comment]
They are 2 separate products, firebase real-time database is not going away.

**Comment by laurentpayot** [comment]
> use Cloud Firestore for your new projects.

and

> Expect to see new query types, more robust security rules, and improvements to performance among the advanced features planned for Cloud Firestore.

They don't say anything about future improvements of Realtime Database. For me there is a high probability for the Realtime Database to be shut down within a couple of years. I hope not, but I think so.

**Comment by ssijak** [comment]
They said in the hacker news story (https://news.ycombinator.com/item?id=15393396) that they are separate products for separate use cases and that they will support both.

**Comment by laurentpayot** [comment]
Thanks for the link @ssijak 
This comment by Firease founder is reassuring: https://news.ycombinator.com/item?id=15395343
> Regarding deprecation: you can be comfortable continuing to build on the Realtime Database. We don't intend to deprecate either database, since both are useful in different situations, depending on what you're building. We recommend using the Realtime Database for a number of usecases[1]
We're not posting a "Realtime Database will be supported for X years" statement because many may interpret this as "the Realtime Database is deprecating in X years", which isn't the case.

**Comment by posva** [comment]
Firebase real-time database already works nicely when disconnected

**Comment by neovive** [comment]
From a few of the interviews circulating the web, it does seem like Firestore will become the "preferred" database for new users. There's no mention of Real-Time DB deprecation, but the emphasis is clearly shifting to Firestore going forward.

**Comment by zevdg** [comment]
@neovive That's pretty clear just from the link in the first post.  Here's the relevant bit.

> **If you're comfortable with a product in beta, use Cloud Firestore for your new projects.** Cloud Firestore offers additional functionality, performance, and scalability on an infrastructure designed to support more powerful features in future releases.

That tone seems to indicate that once cloud firestore is out of beta, they'll be recommending it for all new projects.

**Comment by trickstival** [comment]
can't wait for a firestore support

**Comment by jpicornell** [comment]
Hey everyone!

I've started using Firestore recently and I can't wait for vuefire to have support on this amazing product. I've seen not so many changes have to be done. Maybe it's useful to have separated fields on a component to support both:
```javascript
...
firebase: {
  myCollection: db.ref('/my-collection'),
},
firestore: {
  myCollection: db.ref('/my-firestore-collection'),
},
...
```

Is there anybody willing to implement it?

**Comment by laurentpayot** [comment]
Actually the Firebase _ecosystem_ is (will be) using Firestore as its prefered _database_, the other "legacy" _database_ being the Real Time Database (**RTDB**).

So as Firebase is no more mainly a database but a collection of tools (whatever database, auth, hosting, etc.), maybe we should use the following notation:

```javascript
...
rtdb: {
  myCollection: db.ref('/my-rtdb-collection'),
},
firestore: {
  myCollection: db.ref('/my-firestore-collection'),
},
...
```

**Comment by laurentpayot** [comment]
And while waiting for Vuefire to support Firestore the native solution is less convenient but quite easy:
https://firebase.google.com/docs/firestore/query-data/listen
Simply detach listeners at the `beforeDestroy` hook.

**Comment by posva** [comment]
It's as simple as before, didn't took me long to get something working but I found a bug that I reported.
I'm not a fan of having both things at the same time. If Firestore is meant to be the successor of Firebase realtime database, I prefer having different versions. In the worst case you can always both packages.

**Comment by laurentpayot** [comment]
@posva +1 for different versions.

**Comment by trickstival** [comment]
+2 for different versions.

**Comment by Yatima-Kagurazaka** [comment]
IMHO it isn't upward compatibility completely.
RTDB's latency is less than Firestore's.
They also strongly said, "We'll support both." 

But all in all, we can think it is a successor.

**Comment by Yatima-Kagurazaka** [comment]
Here it is:
https://github.com/gdg-tangier/vue-firestore

**Comment by posva** [comment]
@Yatima-Kagurazaka It's nice you found a temporary solution but please don't promote it here. Right now I cannot code much for personal reasons, but I'll publish an official version as soon as I can

**Comment by Yatima-Kagurazaka** [comment]
I'm sorry.
I put it here for reference to develop vuefire better than expected.
I won't do like this.

**Comment by donPuerto** [comment]
What's the update for  firestore on vuefire? ;)

**Comment by posva** [comment]
I'll get an alpha release in the coming weeks with the basics features and probably a stable version with the full set before 2018

Sorry for not getting it done sooner but I was just super busy with personal matters and I'm still not at full capacity 😄

**Comment by posva** [comment]
Closing in favour of #145
