### ISSUE TITLE
Read protected by security rules documents in SSR

### ISSUE THREAD

**Issue by niklv** [vuejs/vuefire#1310]
### What problem is this solving

Currently it rejects with%
```
[nitro] [dev] [unhandledRejection] [FirebaseError: Missing or insufficient permissions.] {                                                                                                                                                                         11:55:59
  code: 'permission-denied',
  customData: undefined,
  toString: [Function (anonymous)]
}

```

### Proposed solution

Somehow init firebase-js-sdk auth in SSR with provided from client idToken?

**Comment by niklv** [comment]
@posva 
1. Protect some collection with firestore security rules (for example `/content/{contentId}`). Make it available for logged in users only.
2. From Vue app auth anonymous user
3. If you request collection `/content/{contentId}` from frontend it will be available.
4. If you request collection inside SSR it will throw error `FirebaseError: Missing or insufficient permissions.`

If this is not clear I can try create repoduction repo for you.

**Comment by niklv** [comment]
@posva yes, I check it
Auth validation works well in SSR. I need to query with user auth protected collections in SSR, this is what this issue is about

**Comment by LoicNuom** [comment]
I have the same issue, always getting the error during SSR
`
[nitro] [dev] [unhandledRejection] [FirebaseError: Missing or insufficient permissions.] {                       
  code: 'permission-denied',
  customData: undefined,
  toString: [Function (anonymous)]                                                                                   
}
`

I'm using Nuxt 3, I have setup the service account and I'm getting the authentication fine but I'm not able to query protected documents.


If it's not possible defines what to do when an error happens? right not it is just stoping the page rendering

**Comment by LoicNuom** [comment]
@posva  I was able to reproduce the issue on your demo repository: https://github.com/posva/vuefire-nuxt-example

Navigating to `/firestore-secure-doc` works fine:
![image](https://user-images.githubusercontent.com/71375865/227187897-4c2c2f04-ab3d-4662-a514-740408d48f05.png)

but reloading the page creates an error:
![image](https://user-images.githubusercontent.com/71375865/227188297-e89c70d1-e037-48a4-bb36-6b7043bc4950.png)
![image](https://user-images.githubusercontent.com/71375865/227188478-c93b0a77-8134-43e8-b610-a3163ee4c751.png)

I have tried multiple versions of `nuxt-vuefire` between `0.0.19` and `0.1.6` with the same results

**Comment by chrisspiegl** [comment]
Hi, I have run into a similar issue. Have you tested this in different browsers?
I had this happening in Chrome in an Incognito window.
When I was using Chrome in a normal window it works.
In Firefox and Safari I don't remember but I feel like it was different in one of them.

So maybe test that and see if any version works?

**Comment by niklv** [comment]
@chrisspiegl it is ssr backend issue.
Not related to browser version. It depends on browser firebase auth token exist or not and how it handles inside ssr.

**Comment by LoicNuom** [comment]
@chrisspiegl tried and Chrome and Firefox without success. It only works in Safari because for some reason `useCurrentUser()` always return undefined during SSR on Safari.

I have a fix, but it is not really elegant:

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/71375865/227714290-9c1ab886-a2e4-447f-9fe1-e76b32f72ee0.png">

**Comment by niklv** [comment]
@LoicNuom it is dangerous, cause it bypass security rules. You read document via `firebase-admin` in your workaround.

**Comment by LoicNuom** [comment]
Yes that's why I said it wasn't an elegant solution. 
But because the code is ran on a server, I don't think we can use the client SDK to and pretend to be a specific user

**Comment by niklv** [comment]
@LoicNuom actually you can, the only problem is intialization client sdk on server with client idToken, that you receive via cookie.
If firebase auth not used (aka user not logged in) and security rules allow access to all user, all works fine.
Error `FirebaseError: Missing or insufficient permissions` recevies in SSR from firebase client sdk.
Also check support table:
https://firebase.google.com/docs/web/environments-js-sdk#other_environments

**Comment by LoicNuom** [comment]
Yes, the issue is that requests made using the client SDK on the server are not authenticated. And I don't think there is a simple way to authenticate those requests as a specific user.

**Comment by robokozo** [comment]
Just ran into this myself. I'm wondering how I can work around this temporarily. Any ideas?

**Comment by niklv** [comment]
@posva there are repo link there in thread above, please change issue label

**Comment by posva** [comment]
No need to ping me: I'm currently busy with other stuff and I will check again in end-may

**Comment by Maxino22** [comment]
Just ran into this error... any fixes now??

**Comment by michael-strain** [comment]
@niklv What do your firebase rules look like?  If your client is properly authenticated, it shouldn't throw a Firebase permissions error unless the firebase rules are blocking access.

**Comment by niklv** [comment]
@michael-strain My firestore rules allow document read only for authenticated users. The issue happen inside SSR. On client side all works fine.

**Comment by niklv** [comment]
@posva is there any chance that you will check this issue?

**Comment by Maxino22** [comment]
Hey, I also noticed I was getting missing service account files locally...  let me update and test... Thanks

**Comment by posva** [comment]
I think I found the issue: the firestore instance is not using the correct application instance that is connected to the logged in user
