### ISSUE TITLE
docs improvement

### ISSUE THREAD

**Issue by sangemi** [vuejs/vuefire#1316]
### Reproduction

..

### Steps to reproduce the bug

It should be added "firebase" package at the https://vuefire.vuejs.org/nuxt/getting-started.html, for the beginner.

npm install vuefire nuxt-vuefire
>>
npm install vuefire nuxt-vuefire firebase

### Expected behavior

..

### Actual behavior

..

**Comment by posva** [comment]
You can directly open a PR for this kind of suggestions 😄
