### ISSUE TITLE
Add useFirebaseFunctions() composable

### ISSUE THREAD

**Issue by BenJackGill** [vuejs/vuefire#1327]
### What problem is this solving

Many of the Firebase services can be accessed using [VueFire composables](https://vuefire.vuejs.org/guide/firebase-composables.html).

For example:

```TypeScript
<script setup>
import {
  useFirebaseApp,
  useFirebaseAuth,
  useDatabase,
  useFirestore,
  useFirebaseStorage,
} from 'vuefire'

const firebaseApp = useFirebaseApp()
const auth = useFirebaseAuth()
const database = useDatabase()
const firestore = useFirestore()
const storage = useFirebaseStorage()
</script>
```

But it is currently missing Firebase Functions from the list.

### Proposed solution

I propose that `useFirebaseFunctions()` also be added as a composable so that we can easily access Firebase Functions in the client like this:

```TypeScript
<template>
 ...
</template>

<script setup>
import { useFirebaseFunctions } from "vuefire";
import { httpsCallable } from "firebase/functions";

const someCloudFunction = httpsCallable(useFirebaseFunctions(), "someCloudFunction");
</script>
```

Firebase Functions are an integral part of the Firebase platfrom. They're heavily used by those that develop with Firebase.

Adding this composable would bring the Firebase Functions service inline with other VueFire composables such as `useFirebaseApp()`, `useFirebaseAuth()`, `useFirestore()`, etc and provide a consistent way of accessing these Firebase services from with the app.

**Comment by posva** [comment]
We might add this in the future if there is any value to it but right now it looks like what you want is:

```ts
import { useFirebaseApp } from 'vuefire'
import {getFunctions } from 'firebase/functions'

export function useFirebaseFunctions() {
  return getFunctions(useFirebaseApp())
}
```

**Comment by BenJackGill** [comment]
@posva Was this closed in error? https://github.com/vuejs/vuefire/commit/d0249dfcd2dda27d006198728b91d87715d50f8f is for `useFirebaseMessaging` not `useFirebaseFunctions`. But I'm not good with Github so I could be reading this wrong.

**Comment by posva** [comment]
It wasn’t an error

**Comment by strid3r21** [comment]
@BenJackGill did you ever get this working on your end? this is something im needing to get working as well.

**Comment by BenJackGill** [comment]
@strid3r21 no I did not and I don't think they are adding it. The current advice is to make your own wrapper like this https://github.com/vuejs/vuefire/issues/1327?notification_referrer_id=NT_kwDOAB8tebI1OTA1NDg3MTcxOjIwNDMyNTc#issuecomment-1619155317.
