### ISSUE TITLE
Session controller and cookie minting not registered when configuring service account as an object

### ISSUE THREAD

**Issue by noook** [vuejs/vuefire#1330]
### Reproduction

(I can't make a reproduction yet, Nuxt crashes when loading `nuxt-vuefire` as a module, I'll open a [separate issue](https://github.com/vuejs/vuefire/issues/1331))

### Steps to reproduce the bug

1. Configure vuefire, with admin service account as an object
2. Run the server
3. The following code is not executed, resulting in `/api/__session` and `'auth/plugin-mint-cookie.client` not being registered https://github.com/vuejs/vuefire/blob/90be27a3cf9f4718e9ecaf1df273b18b3995c918/packages/nuxt/src/module.ts#L127-L135

### Expected behavior

When configuring the service account with an object instead of a file path, I should have the same behaviour.

The logic to handle the object as service account credentials is already handled here: https://github.com/vuejs/vuefire/blob/86c276edff2a56d5528b1c37beac2c6a422540dc/packages/nuxt/src/runtime/admin/plugin.server.ts#L53-L58

### Actual behavior

The handler and plugin are not registered even though the admin service account is configured

### Additional information

A PR is already ready for that: https://github.com/vuejs/vuefire/pull/1319

**Comment by 35C4n0r** [comment]
I am also facing the same issue, on passing serviceAccount as
```
serviceAccount: {
    projectId: "...",
    privateKey: "..."
    clientEmail: "...",
}
```

I still get the warning that SSR is enabled but admin config has not been passed.
Any idea when the related PR can be merged ?

**Comment by posva** [comment]
This should be fixed now but it's necessary to pass an environment variable [See the changelog](https://github.com/vuejs/vuefire/blob/main/packages/nuxt/CHANGELOG.md#020-2023-07-07)
