### ISSUE TITLE
Cannot reference one `useDocument()` in another `useDocument()`

### ISSUE THREAD

**Issue by BenJackGill** [vuejs/vuefire#1333]
### Reproduction

N/A

### Steps to reproduce the bug

I'm trying to use the result of one `useDocument()` in another `useDocument()`.

As per [the docs](https://vuefire.vuejs.org/guide/realtime-data.html#declarative-realtime-data), I assume I need a computed ref for this:

```TypeScript
// "user" is now reactive 
const user = useDocument(
  doc(firestore, "users/ZtNQ1reVmofCgnzAXadU81L1MYh1")
);

// "auditSource" should be reactive too
const auditSource = computed(() =>
  doc(collection(firestore, "audits"), user.value?.currentAuditId)
);

// Therefore "audit" should be in sync with the data source
const audit = useDocument(auditSource);
```

But using the above code gives me this console error: `FirebaseError: Function doc() cannot be called with an empty path.`

### Expected behavior

The `audit` document should be updated once `user.value?.currentAuditId` is loaded.

### Actual behavior

Console error: `FirebaseError: Function doc() cannot be called with an empty path.`

**Comment by posva** [comment]
The error you see comes from Firebase. You need

```ts
const auditSource = computed(() =>
  user.value && doc(collection(firestore, "audits"), user.value.currentAuditId)
);
```
