### ISSUE TITLE
Not compatible with lru-cache >= 9.0.0

### ISSUE THREAD

**Issue by mklueh** [vuejs/vuefire#1348]
### Reproduction

https://github.com/vuejs/vuefire/discussions/1346

### Steps to reproduce the bug

Having lru-cache > 9.0.0 in your project will break this module

### Expected behavior

...

### Actual behavior

Previous issue has been moved to discussions for whatever reason, see https://github.com/vuejs/vuefire/discussions/1346

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vuefire/discussions/1346

**Comment by posva** [comment]
Please do not create duplicates like this, it really wastes my time as a maintainer. I sometimes need more time to reply but I eventually get back to people 🙂 .
