### ISSUE TITLE
Error: VueFire: unbind failed - beforeDestroy 

### ISSUE THREAD

**Issue by JohnRSim** [vuejs/vuefire#135]
When I destroy the following component - 
```javascript
export default {
  name: 'Blocks',
  firebase: {},
  data() {
    return {
      transactions: []
    };
  },
  mounted() {
    this.$firebaseRefs.transactions = db.ref('block/1/10/input');
  },
  beforeDestroy() {
    console.log('destroy');
  },
};
```
I am getting the following errors - 
[Vue warn]: Error in beforeDestroy hook: "Error: VueFire: unbind failed: "transactions" is not bound to a Firebase reference."

 Error: VueFire: unbind failed: "transactions" is not bound to a Firebase reference.

**Comment by posva** [comment]
`this.$firebaseRefs` is read-only, it gets populated when doing a bind of a ref

**Comment by JohnRSim** [comment]
it's binding fine - but it's not unbinding when the component is destroyed.
I bind when the component is mounted but as soon as I destroy the component I get the error.

I can't seem to unbind before the component is destroyed?

**Comment by posva** [comment]
You have to use the `firebase` option or any of the  `$bind*` functions
