### ISSUE TITLE
where to ask for help

### ISSUE THREAD

**Issue by ricky11** [vuejs/vuefire#136]
where do i ask for help using vuefire?

i have created a drop down list which is populated from firebase (this part works) now i want the child fields to populate based on the parent drop down list.. im unsure how i would need to do it. I am unsure how to get the index of the firebase array that is selected, and then display other records that are in the same collection.

this is what i have so far.

<select v-model="vendorName">
  <option disabled value="">Select Vendor</option>
  <option v-for="(supplier, Objkey) in suppliersRef" v-bind:key="supplier.key" @click="vendorName()">{{supplier.companyName}}</option>
</select>

watch: {
    vendorName: function() {
     //psuedo code 
//unsure how to use the selected dropdown as a index or get the array position and assign the related fields to the data as:
this.contactName =
this.email =
this.address =
      
  }

Thanks.

**Comment by posva** [comment]
vuefire being a very tiny layer, you probably want to ask questions about Firebase, which can be done in StackOverflow, the vuejs forum or the chat.
If you have a question about vuefire because docs are unclear, you can open an issue, or even better a Pull request to improve them 🙂

**Comment by ricky11** [comment]
Well noted. Thanks.
