### ISSUE TITLE
Await support

### ISSUE THREAD

**Issue by szulcus** [vuejs/vuefire#1367]
### What problem is this solving

It would be great if the module supports await like `useAxios` from `VueUse` does: https://vueuse.org/integrations/useAxios/.

### Proposed solution

It would be easier to write:
```ts
const { data: bookData } = await useDocument<ApiVocabulary>(doc(collection(firestore, 'books'), route.params.bookSlug));
// Operations on `bookData`
```
than:
```ts
const { promise: bookPromise } = useDocument<ApiVocabulary>(doc(collection(firestore, 'books'), route.params.bookSlug));
const bookData = await bookPromise.value;
// Operations on `bookData`
```

### Describe alternatives you've considered

https://github.com/vueuse/vueuse/tree/main/packages/integrations/useAxios

**Comment by posva** [comment]
It’s already possible with the promise: https://vuefire.vuejs.org/guide/realtime-data.html#subscription-state

**Comment by szulcus** [comment]
@posva It is possible, but very unintuitive, as I wrote above 😕

**Comment by mrleblanc101** [comment]
@posva It is not documented anywhere that you need to destructure a promise from the collection and wait the `promise.value` with useCollection anywhere in the doc.
I've had to dig deep into the type definition to understand.
I also tried 
```
await useCollection(...)
``` 
instead of 
```
const {promise} = useCollections(...)
await promise.value();
```
