### ISSUE TITLE
Unique key value not appearing in the object

### ISSUE THREAD

**Issue by adarshsosale** [vuejs/vuefire#137]
I am trying to create a dynamic link to a page using the key as the URL ID. I've gone through the documentation, but I'm unable to solve the problem. Most likely, my understanding on this is wrong. Please help!

My reference is set up as

    let db = app.database();
    const postsRef = db.ref('posts');
and I'm importing the global refs into my app page like so -

    firebase: {
      posts: {
        source: postsRef,
        asObject: true,
        readyCallback: function () {
          console.log(postsRef)
        }
      },
    },

and iterating over the posts object like so - 

    <div v-for="post in posts">
      <a :href="'post/' + post.key"></a>
    </div>

My database is structured like so - 
[DB Structure][1]

What would be the best way to use the key considering that I might want to retrieve at the posts page, preferably without using URL Params? When I log the postsRef object, I see that the parent value is null and the key value is "posts". I want the key value to retrieve the unique ID of the element in the for loop.

  [1]: https://i.stack.imgur.com/VAkdz.png

**Comment by posva** [comment]
Remove `asObject: true,` and it should be good: you want it as an array
The key is accessible as `['.key']` btw
