### ISSUE TITLE
Refresh token if expired

### ISSUE THREAD

**Issue by luc122c** [vuejs/vuefire#1376]
### What problem is this solving

Currently, when Firebase reports an expired token (`auth/id-token-expired`), [vuefire simply logs the error](https://github.com/vuejs/vuefire/blob/f7a925115ca1782b2d7fc0cd081fdff5240a06ce/packages/nuxt/src/runtime/admin/plugin-auth-user.server.ts#L34). 

### Proposed solution

When the server component encounters this error, it could pass a message to the frontend to refresh the token. This can be achived with [`getIdToken($user, true)`](https://firebase.google.com/docs/reference/js/auth.md#getidtoken).

### Describe alternatives you've considered

Logging out and in again also clears the issue.

**Comment by posva** [comment]
Can you dive a bit more in the proposed solution?

**Comment by luc122c** [comment]
Sure. Althrough I'm not sure on the mechanism that Vuefire uses, the docs suggest that during SSR, data is serialised and then hydrated on the client side. 

My suggestion would be that if the token has expired, send some additional metadata using the same mechanism, then check for this on the client side. If it is detected by the client plugin, call `getIdToken` to refresh the token and update the cookie.

**Comment by posva** [comment]
I did a few changes to avoid the page to crash when the token expires. I think the firebase js sdk automatically refreshes the token (I tested this locally). Is there anything left to do?

**Comment by luc122c** [comment]
As long as the refreshed token gets updated in the cookie, then all should be good :) Thank you!
