### ISSUE TITLE
Using with nuxt 3.5 not giving auto complete.

### ISSUE THREAD

**Issue by Rohithgilla12** [vuejs/vuefire#1379]
### Reproduction

Reproduction

### Steps to reproduce the bug

- Create a nuxt app
- `yarn add vuefire nuxt-vuefire firebase-admin @firebase/app-types`

When trying to add the `vuefire` in the `nuxt.config.ts` file, It's popping with this error.
![image](https://github.com/vuejs/vuefire/assets/19389850/69456219-7008-43bf-a876-0a54f4f7bdc9)

### Expected behavior

No red swiggly lines 😄 

### Actual behavior

https://ts-error-translator.vercel.app/?error=CoTwDgpgBAlgdgZwC4EM5JijB7OsFQQAeAxhAgjAG4QA2IUAJhBGFGo1GNhTAEb1YcAGbwYSCADogA

### Additional information

But the app works in general.

**Comment by posva** [comment]
Please report this to the Nuxt team. Note it might have been already reported with terms like "Plugin instantiation is excessively deep"
