### ISSUE TITLE
asObject: true is not binding

### ISSUE THREAD

**Issue by janswist** [vuejs/vuefire#138]
When I update data in database my dropdown list doesn't get updated (downloads only once):
![image](https://user-images.githubusercontent.com/5583954/32133683-99560736-bbdd-11e7-8dc8-bb582cd26f80.png)

What I try to achieve is `.on('value', function(){...})` thing.

I found that in VueFire source:
![image](https://user-images.githubusercontent.com/5583954/32133883-026cd012-bbe1-11e7-9e45-b70626c0c347.png)
and that:
![image](https://user-images.githubusercontent.com/5583954/32133990-c4e38df0-bbe3-11e7-8f64-5c6ac24b0fac.png)

So it should behave like I thought it would, but even when I delete `readCallback` data still behave as `once`.

**Comment by posva** [comment]
Can you provide a simple repro in a fiddle please?

**Comment by janswist** [comment]
Here is the simple repro:
[](https://jsfiddle.net/ovy8bs0u/1/)
but in that form it works. I start to understand that `readyCallback` is not fired after each change on the server and that may cause this problem. Is there a way to make `readyCallback` listen for changes as well?

**Comment by posva** [comment]
If you want an array, you should not use the `asObject` btw.
Can you described reproduction steps as well as expecetd result please?

**Comment by janswist** [comment]
Here is the updated fork: https://jsfiddle.net/xgtrjsz9/1/

Now it's working, but don't know how to implement it to my dropdown function:
````
firebase.database().ref('places/' + placeId + "/schedules").on('value', function(snapshot2) {				

		var holder = document.getElementById('dropdownOptionList');
		$('#dropdownOptionList').empty();
		//show list of available schedules for specified place
		snapshot2.forEach(function(childSnapshot) {					
			
			scheduleId = childSnapshot.key;																
			
			var li = document.createElement('li');
			var a = document.createElement('a');
			a.setAttribute('href', '#');
			a.setAttribute('data-src', 'https://terminarz-28eeb.firebaseio.com/reservations.json?orderBy=\"scheduleId\"&equalTo=\"' + childSnapshot.key + '\"');
			a.setAttribute('data-id', childSnapshot.key);
			a.appendChild(document.createTextNode(childSnapshot.val()));
			
			li.appendChild(a);
			holder.appendChild(li);					
			
		});					
		
		activateDropdown();				
	});		
````

**Comment by posva** [comment]
Well, once you got your data bound, it's just Vue 🙂 
The only difference is that the data may change because of another client changing it but you don't even have to worry about it because vuefire handles the update for you
