### ISSUE TITLE
Chaining for multiple calls

### ISSUE THREAD

**Issue by johnyluyte** [vuejs/vuefire#140]
Hello, I usually use `async/await` or `Promise.all` to chain multiple async calls when interacting with firebase.

But as discussed in https://github.com/vuejs/vuefire/issues/125, the callback function is not Promise yet. 

So currently I'm chaining multiple calls like this:

```
this.$bindAsObject(
  "myObj",
  fb.ref(`myPath`),
  null,
  () => {
    // myObj Ready Callback

    this.$bindAsObject(
      "myObj2",
      fb.ref(`myPath2`),
      null,
      () => {
        // myObj2 Ready Callback
        // console.log(`all calls done`)
      }
    );

  }
);
```

I would like to know if I'm doing this right? Or are there better ways to chain for multiple calls? 

Thanks.

**Comment by posva** [comment]
Until Promise support is added (which, to be honest, is not a priority because I prefer to focus in Firestore right now), you have to either do that or wrap yourself the `$bind*` functions:

```js
// after vuefire is installed
const bindAsObject = Vue.prototype.$bindAsObject
Vue.prototype.$bindAsObject = function bindAsObject (key, ref, cancelCallback) {
     return new Promise(resolve => {
          bindAsObject(key, ref, cancelCallback, resolve)
    })
}
```
⚠️ not tested
