### ISSUE TITLE
500 Error: "Invalid value used as weak map key" when using latest vuefire/nuxtfire releases (v 3.1.15)

### ISSUE THREAD

**Issue by dosstx** [vuejs/vuefire#1410]
### Reproduction

https://codesandbox.io/p/sandbox/github/posva/nuxt--vuefire-repro-template/tree/main

### Steps to reproduce the bug

Using the latest vuefire and nuxt-vuefire releases (3.1.15 and 0.2.16) , I get the following error when viewing the app in the browser:

### 500
Invalid value used as weak map key

```
at ./node_modules/.pnpm/nuxt-vuefire@0.2.16_rd3jegnpemhlxr77rbrlplecpe/node_modules/nuxt-vuefire/dist/runtime/emulators/storage.plugin.mjs:23:22
at ./virtual:nuxt:/project/sandbox/.nuxt/plugins/server.mjs:52:89
at Module.executeAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:111:19)
at setup (./virtual:nuxt:/project/sandbox/.nuxt/plugins/server.mjs:52:65)
at ./node_modules/.pnpm/nuxt@3.6.5_@types+node@18.17.5/node_modules/nuxt/dist/app/nuxt.js:112:60
at fn (./node_modules/.pnpm/nuxt@3.6.5_@types+node@18.17.5/node_modules/nuxt/dist/app/nuxt.js:156:44)
at Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:68:55)
at ./node_modules/.pnpm/nuxt@3.6.5_@types+node@18.17.5/node_modules/nuxt/dist/app/nuxt.js:158:56
at Object.runWithContext (./node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3855:18)
```

This is also reproduceable when using the `nuxt template` link. 

**Downgrading Vuefire and Nuxt-vuefire to the previous version fixes this issue.** 

### Expected behavior

I expect to the see the default Nuxt welcome page. Instead, I see the 500 error above.

### Actual behavior

I get the 500 server error mentined above.

### Additional information

Although I can't reproduce it on codesandbox, on my localhost, if I downgrade the vuefire/nuxtfire versions to a previous version, the error is gone.

**Comment by Eronne** [comment]
Same on my side.

Downgraded to `"nuxt-vuefire": "^0.2.6"` & `"vuefire": "^3.1.7"` to be working.

**Comment by dosstx** [comment]
Interesting. I wonder if that is somehow related to same thing we are seeing here: https://github.com/vuejs/vuefire/issues/1408

**Comment by typefox09** [comment]
I'm getting the same error in the same circumstance, however, I noticed the error only occurs when there is no logged in user (incognito mode). When refreshing the page with an authenticated firebase user, everything works as normal?


`Invalid value used as weak map key

at getGlobalScope (./node_modules/vuefire/dist/shared/vuefire.d8c83e54.mjs:85:14)
at Module.VueFireAuthServer (./node_modules/vuefire/dist/server/index.mjs:149:16)
at ./node_modules/nuxt-vuefire/dist/runtime/auth/plugin.server.mjs:46:25
at ./virtual:nuxt:/Users/typefox09/Desktop/marketlyfe/marketlyfe-ssr/.nuxt/plugins/server.mjs:48:89
at Module.executeAsync (./node_modules/unctx/dist/index.mjs:111:19)
at setup (./virtual:nuxt:/Users/typefox09/Desktop/marketlyfe/marketlyfe-ssr/.nuxt/plugins/server.mjs:48:65)
at ./node_modules/nuxt/dist/app/nuxt.js:112:60
at fn (./node_modules/nuxt/dist/app/nuxt.js:156:44)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)`

**Comment by typefox09** [comment]
Found the issue. It occured in the handling of the anonnymous session where there was no logged in user. If there was no cached version the code would work, however there was no else block for when there is a cached version

plugin.server.mjs

```
export default defineNuxtPlugin((nuxtApp) => {
  const appConfig = useAppConfig();
  const decodedToken = nuxtApp[
    // we cannot use a symbol to index
    DECODED_ID_TOKEN_SYMBOL
  ];
  const uid = decodedToken?.uid;
  let firebaseApp;
  if (uid) {
    firebaseApp = appCache.get(uid);
    if (!firebaseApp) {
      const randomId = Math.random().toString(36).slice(2);
      const appName = `auth:${uid}:${randomId}`;
      logger.debug("\u{1F464} creating new app", appName);
      firebaseApp = initializeApp(appConfig.firebaseConfig, appName);
      appCache.set(uid, firebaseApp);
    } else {
      logger.debug("\u{1F464} reusing authenticated app", firebaseApp.name);
    }
  } else {
    if (!appCache.has("")) {
      appCache.set("", firebaseApp = initializeApp(appConfig.firebaseConfig));
    } else {
      firebaseApp = appCache.get(""); // retrieve the cached app (this is the fix)
    }
    logger.debug("\u{1F978} anonymous session");
  }
  return {
    provide: {
      firebaseApp
    }
  };
});
```

**Comment by posva** [comment]
Thanks for all the information! I released a patch, let me know if things are still broken

**Comment by posva** [comment]
@Eronne Googling those errors should help. Here are some extra resources:

- https://github.com/posva/nuxt--vuefire-example-blaze-plan
- https://firebase.google.com/docs/auth/admin/create-custom-tokens#iam_api_not_enabled

**Comment by Eronne** [comment]
Thanks @posva for the reactivity and the details! 🙏🏼

I was applying the Service Account Token Creator role to the wrong service account... I thought it had to be applied on the service account provided with the `service-account.json` file.

**Comment by posva** [comment]
It happened to me too 😅

**Comment by dosstx** [comment]
It works for me now, thanks!
