### ISSUE TITLE
Ability to manually unsubscribe to databaseList & disconnect the websocket connection

### ISSUE THREAD

**Issue by crunchwrap89** [vuejs/vuefire#1415]
### What problem is this solving

Currently vuefire handles the unsubscribe from lists automatically when the app gets destroyed.

I want to use vuefire for a game where i need to be able to control when to stop listening to a specific list and when to disconnect the current ws connection.

### Proposed solution

Add ability to manually unsubscribe and/or disconnect from the open WS connection on demand.

**Comment by posva** [comment]
This is already possible with the destructured return of useDocument(). I think it’s named stop

**Comment by crunchwrap89** [comment]
@posva 

Okay but why doesnt my websocket connection get disconnected when i stop listening to the database list?

Here's a snippet:

```
    const db = useDatabase();
    const {promise, stop} = useDatabaseList<PlayerState>(dbRef(db, `activePlayers/MAP-${mapId}`));
    const allPlayersState =  await promise.value

    const myPlayerState = dbRef(db, `activePlayers/MAP-${mapId}/${playerId}`);
    const connectedRef = dbRef(db, '.info/connected');

    onValue(connectedRef, snap => {
      if (snap.val() === true) {
        onDisconnect(myPlayerState).remove().then();
      }
    });

onBeforeUnmount(() => {
stop(true)
})

```

Currently i am only getting disconnected from the socket on a full page reload, not on route change. Any ideas on what i am missing?

**Comment by crunchwrap89** [comment]
@posva 
But i think something is not right here..

These rows activates the WS connection and starts listening for changes to the list:
```
  const {promise, stop} = useDatabaseList<PlayerState>(dbRef(db, `activePlayers/MAP-${mapId}`));
  const allPlayersState =  await promise.value
```

This row stops listening to the changes of the list, but it does not stop the WS connection? 
```
stop(true)
````

Because otherwise the "onDisconnect" would trigger. But its currently not being triggered untill the app gets destroyed.
So how would i go about doing that with the vuefire package?

**Comment by posva** [comment]
Maybe Firebase keeps the connection open
