### ISSUE TITLE
unable to deploy to firebase hosting after update

### ISSUE THREAD

**Issue by crunchwrap89** [vuejs/vuefire#1420]
### Reproduction

--

### Steps to reproduce the bug

after updating firebase, nuxt, and nuxt-vuefire packages all to latest version i am unable to deploy.

nuxt build finishes fine without errors and i can run it locally, but when running "npx firebase-tools deploy" or "npx firebase deploy" i get below error msg:

```
shutdown requested via /__/quitquitquit

Error: An unexpected error has occurred.

```
I have been able to deploy without issues before updating

### Expected behavior

Ability to deploy

### Actual behavior

Error,, see attached screenshots.

![error](https://github.com/vuejs/vuefire/assets/19464526/8095e413-a0b8-450c-9cab-740e3601db60)

**Comment by posva** [comment]
I can’t check without a repro

**Comment by posva** [comment]
https://github.com/vuejs/vuefire/issues/1421
