### ISSUE TITLE
Allow alternative way to set the GOOGLE_APPLICATION_CREDENTIAL without json file

### ISSUE THREAD

**Issue by websiddu** [vuejs/vuefire#1435]
### What problem is this solving

Currently the only way you can add SSR support is by adding the `GOOGLE_APPLICATION_CREDENTIALS=service-account.json` 

However server less platforms like vercel or railway don't have way to upload the .json file in the server. 

### Proposed solution

Allow alternative way to set the GOOGLE_APPLICATION_CREDENTIAL without JSON FILE https://github.com/vercel/vercel/issues/749#issuecomment-715009494

**Comment by posva** [comment]
I think you figured it out but it does support it already: https://vuefire.vuejs.org/nuxt/environment-variables.html#Admin-SDK
