### ISSUE TITLE
Documentation Request: How to use emulators the correct way

### ISSUE THREAD

**Issue by crunchwrap89** [vuejs/vuefire#1440]
### What problem is this solving

Currently there is no documentation for how to handle the emulators in dev environment correctly.

When starting the dev environment i get a warning saying:

```
WARNING: You are using the Auth Emulator, which is intended for local testing only. Do not use with production credentials.
```

i can surpress this with:

```
    emulators: {
      auth: {
        options: {
          disableWarnings: true,
        },
      },
    },
```

But i guess that is not safe.

If i replace my domain in the .env variables to localhost, it will not work.
So i am not sure how to get this working?

### Proposed solution

add documentation regarding emulators in the website:
https://vuefire.vuejs.org/nuxt/getting-started.html#Installation

**Comment by posva** [comment]
Regarding making it work, I recommend you to give a look at https://vuefire.vuejs.org/nuxt/deployment.html. I added explanations to both examples. You don't have to use the emulators of course and they are always disabled in production

**Comment by rublev** [comment]
> Regarding making it work, I recommend you to give a look at https://vuefire.vuejs.org/nuxt/deployment.html. I added explanations to both examples. You don't have to use the emulators of course and they are always disabled in production

Hi. I've spent days trying to get local firebase emulator working with vuefire + vue (NOT nuxt).
