### ISSUE TITLE
Uncaught TypeError: doc.data is not a function

### ISSUE THREAD

**Issue by CaiJimmy** [vuejs/vuefire#146]
Hi 👋,

Seems like the new version does not support yet Firestore's where syntax? When I try to bind a collection with `.where()` query, a error jumps out:

![image](https://user-images.githubusercontent.com/5889006/32978977-dd4f00bc-cc4c-11e7-93a8-7f2b833aa152.png)

Code Used: 
```
        this.ref.posts = firebase.firestore().collection('posts').where('author', '==', 'USERIDHERE');
        this.$bind('posts', this.ref.posts);
```

While this works well: 
```
        this.ref.posts = firebase.firestore().collection('posts');
        this.$bind('posts', this.ref.posts);
```

Is this a VueFire alpha bug?

----------------

`.orderBy()` has the same issue.

**Comment by posva** [comment]
Hello, thanks for reporting it! It looks like a bug. I didn't test where queries
