### ISSUE TITLE
Vue does not work at all if use firebase: function() {}

### ISSUE THREAD

**Issue by lockevn** [vuejs/vuefire#147]
Please see this [jsfiddle](https://jsfiddle.net/lockevn/rv6khe3o/), use exactly what vuefire says in the readme.

This section will make Vue stop working. Remove it, Vue works again.
```
firebase: function(){
    // var vm = this;	// vue
    // vm.test;
    return { users: usersRef };
    }
  }
```

**Comment by posva** [comment]
You just have an extra `}` on your code (check the syntax error on the console)
