### ISSUE TITLE
typescript type definition not consistence: useDocument return null reference if document does not exist

### ISSUE THREAD

**Issue by tlserver** [vuejs/vuefire#1477]
### Reproduction

[codeSandbox](https://codesandbox.io/p/github/tlserver/vuefire-repro-template/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqqdxtqx0006356hh7w2dtwc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqqdxtqx0002356hh3xai8pq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqqdxtqx0004356hui6zgpx7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqqdxtqx0005356hhmdpwvxt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqqdxtqx0002356hh3xai8pq%2522%253A%257B%2522id%2522%253A%2522clqqdxtqx0002356hh3xai8pq%2522%252C%2522activeTabId%2522%253A%2522clqqegm3b00nt356h8n0z8c75%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqqdxtqx0001356hl0dpxr33%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clqqegm3b00nt356h8n0z8c75%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clqqdxtqx0005356hhmdpwvxt%2522%253A%257B%2522id%2522%253A%2522clqqdxtqx0005356hhmdpwvxt%2522%252C%2522activeTabId%2522%253A%2522clqqe5lrg00l5356hf04sevs0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clqqe5lrg00l5356hf04sevs0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqqdxtqx0004356hui6zgpx7%2522%253A%257B%2522id%2522%253A%2522clqqdxtqx0004356hui6zgpx7%2522%252C%2522activeTabId%2522%253A%2522clqqdxv2j005q356hgv7of0re%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqqdxtqx0003356h0mjbcyyh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqqdxupy0012egho600192pz%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqqdxv2j005q356hgv7of0re%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clqqe0ew20046356hsitv31m2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce the bug

No step required. `count: null` is displayed on startup.

### Expected behavior

In https://github.com/vuejs/vuefire/blob/main/src/firestore/index.ts#L75-L104
```ts
export function useDocument<
  // explicit generic as unknown to allow arbitrary types like numbers or strings
  R extends DocumentReference<unknown>
>(
  documentRef: MaybeRefOrGetter<_Nullable<R>>,
  options?: UseDocumentOptions<_InferReferenceType<R>>
): _RefFirestore<_InferReferenceType<R> | undefined> // this one can't be null or should be specified in the converter

/**
 * Creates a reactive collection (usually an array) of documents from a collection ref or a query from Firestore.
 * Accepts a generic to **enforce the type** of the returned Ref. Note you can (and probably should) use
 * `.withConverter()` to have stricter type safe version of a collection reference.
 *
 * @param collectionRef - query or collection
 * @param options - optional options
 */
export function useDocument<T>(
  documentRef: MaybeRefOrGetter<_Nullable<DocumentReference>>,
  options?: UseDocumentOptions<T>
): _RefFirestore<VueFirestoreDocumentData<T> | undefined>

export function useDocument<T>(
  documentRef: MaybeRefOrGetter<_Nullable<DocumentReference<unknown>>>,
  options?: UseDocumentOptions<T>
): _RefFirestore<VueFirestoreDocumentData<T> | undefined> {
  // no unwrapRef to have a simpler type
  return _useFirestoreRef(documentRef, options) as _RefFirestore<
    VueFirestoreDocumentData<T>
  >
}
```
The return type of useDocument should be `_RefFirestore<VueFirestoreDocumentData<T> | null | undefined>` but not `_RefFirestore<VueFirestoreDocumentData<T> | undefined>`, since it return a null reference if document does not exist.

This code, `doc.value !== null`, should be valid and have no warning.

### Actual behavior

IDE warn at `doc.value !== null`

**Comment by posva** [comment]
FYI `VueFirestoreDocumentData` already includes `null`. This is likely related to your converter not being correctly typed. If it can return `null`, it should be a possibility in `withConverter<T>`. If typed correctly, it works:

![Screenshot 2024-01-03 at 10 40 59](https://github.com/vuejs/vuefire/assets/664177/c90299ca-c1a1-4d1f-93bf-0449d0e4b25c)


BTW, your codesandbox is read only, when opening issues make sure to share writable playgrounds
