### ISSUE TITLE
Error when installing v3.1.20. - simple-git-hooks not recognized as a command

### ISSUE THREAD

**Issue by ingljoOpt** [vuejs/vuefire#1480]
### Reproduction

Minimum reproduction steps below

### Steps to reproduce the bug

Start a clean folder.

npm init
npm install vufire

### Expected behavior

vuefire is installed in node_modules

### Actual behavior

npm ERR! path C:\tmp\testvuefire\node_modules\vuefire
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c simple-git-hooks
npm ERR! 'simple-git-hooks' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

### Additional information

A workaround might be to install simple-git-hooks and save to dev-dependencies, but then it is not possible to commit without having pnpm installed too.

Got error message when committing to git:
".git/hooks/pre-commit: line 2: pnpm: command not found"

**Comment by Smrtnyk** [comment]
same here

**Comment by thesleeper** [comment]
facing the same issue. was fine yesterday 2 days ago?

**Comment by chihebnabil** [comment]
In my case had to update npm and Node on my server

```
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
source ~/.nvm/nvm.sh
nvm install --lts
nvm use --lts
npm --version
```

**Comment by posva** [comment]
Update to the latest and it should be good
