### ISSUE TITLE
`databaseDefaultSerializer` exported incorrecly

### ISSUE THREAD

**Issue by tlserver** [vuejs/vuefire#1481]
### Reproduction

Please find the reproduction example in this [codesandbox](https://codesandbox.io/p/github/tlserver/vuefire-repro-template/i1481?file=%2Fsrc%2FApp.vue%3A51%2C4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr03trtw0008356hjwpsiptx%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr03trtv0002356h5o49aezb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr03trtv0005356h5lg07ugz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr03trtv0007356hegt74te5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr03trtv0002356h5o49aezb%2522%253A%257B%2522id%2522%253A%2522clr03trtv0002356h5o49aezb%2522%252C%2522activeTabId%2522%253A%2522clr04jgjr0002356h2ge6tazc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr03trtv0001356hz8tdchgd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clr04fnk900fz356h5fqscmqk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr04jgjr0002356h2ge6tazc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A51%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A51%252C%2522endColumn%2522%253A4%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clr03trtv0007356hegt74te5%2522%253A%257B%2522id%2522%253A%2522clr03trtv0007356hegt74te5%2522%252C%2522activeTabId%2522%253A%2522clr04igin00sn356h2mguqgsa%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clr04igin00sn356h2mguqgsa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr03trtv0005356h5lg07ugz%2522%253A%257B%2522id%2522%253A%2522clr03trtv0005356h5lg07ugz%2522%252C%2522activeTabId%2522%253A%2522clr04ip7a00xu356himzp4c9v%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clr04ip7a00xu356himzp4c9v%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Unfortunately, there is no option to make it writable to the public. To edit, please sign in and fork the sandbox.

### Steps to reproduce the bug

1. Add the following import statement to your code:
   ```ts
   import { databaseDefaultSerializer } from "vuefire";
   ```
2. It fails on page loaded.

### Expected behavior

The import statement should successfully import the `createRecordFromDatabaseSnapshot()` function because, in `dist/index.d.mts:21` (version 3.1.21, which may vary in other versions), it is defined and exported as `databaseDefaultSerializer`:

```ts
// line 21
declare function createRecordFromDatabaseSnapshot(/* ... */): /* ... */;

// line 726
export { /* ... */, createRecordFromDatabaseSnapshot as databaseDefaultSerializer, /* ... */ };
```

### Actual behavior

An error is thrown with the following message:

```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/vuefire.js?v=05c98cd7' does not provide an export named 'databaseDefaultSerializer'
```

This error message does not appear in the CodeSandbox console but is shown in the browser console.
![image](https://github.com/vuejs/vuefire/assets/8895426/94162d7b-3298-47dd-8d31-f7a78e21bf80)

### Additional Information

A search for `databaseDefaultSerializer` in `dist/index.mjs` returns no matches. It appears that the aliasing of `createRecordFromDatabaseSnapshot` as `databaseDefaultSerializer` is mistakenly placed within a type export block in [src/index.ts:24-30](https://github.com/vuejs/vuefire/blob/main/src/index.ts#L24-L30):

```ts
export type {
  DatabaseSnapshotSerializer,
  _RefDatabase,
  VueDatabaseDocumentData,
  VueDatabaseQueryData,
  createRecordFromDatabaseSnapshot as databaseDefaultSerializer,
} from './database/utils'
```
Should it not be included in a regular export instead?

```ts
export {
  createRecordFromDatabaseSnapshot as databaseDefaultSerializer,
} from './database/utils'
  ```

**Comment by posva** [comment]
Yes, it shouldn’t be a type 😅
Feel free to open the PR since you already found the fix
