### ISSUE TITLE
Use multiple firestore databases

### ISSUE THREAD

**Issue by aronsuarez** [vuejs/vuefire#1486]
### What problem is this solving

Firestore supports multiple databases, it would be nice to use `useFirestore()` with multiple databases.

### Proposed solution

Add a second parameter for databaseId

**Comment by posva** [comment]
It seems that this feature is at least partially in beta (https://firebase.google.com/docs/reference/js/firestore_). For the time being you should be able to create your own `useFirestore()` with more parameters. It should be a one line function like the one in the repo.

**Comment by andresvlaeminck** [comment]
I would also love to see this feature implemented
