### ISSUE TITLE
Needs refresh in order to render updated firebase values

### ISSUE THREAD

**Issue by itsnwa** [vuejs/vuefire#149]
I have a firebase array that gets modified in my app, the change is reflected in firebase, but in order to see the updates in my app, the user has to refresh the page. Any suggestions?

**Edit:** Also, if I manually change the column value in firebase, the change updates immediately in my app.

To illustrate:

![kapture 2017-12-29 at 18 35 20](https://user-images.githubusercontent.com/19958806/34443119-43b0a5be-ecc7-11e7-91cd-0b35d81c1bad.gif)

```js
firebase() {
   const userId = this.currentUser.uid
   return {
      user: db.ref('users/' + userId + '/'),
      notes: db.ref('users/' + userId + '/notes'),
      tasks: db.ref('users/' + userId + '/tasks'),
      taskCounter: {
         source: db.ref('users/' + userId + '/taskCounter'),
         asObject: true
      }
   }
},
```

How I update the array on change:

```js
changeTask(task, column) {
   this.$firebaseRefs.tasks.orderByChild('id').equalTo(task.id).once('value').then( (snapshot) => {

      const key = Object.keys(snapshot.val())[0]
      const data = {
         text: task.text,
         column: column
      }

      // Update firebase entry with new data
      const updates = data

      this.$firebaseRefs.tasks.child(key).update(updates)

   })
}
```

"html":

```html
<router-link
   v-for="task in tasks"
   v-if="task.column === 'done'"
   tag="li"
   active-class="active"
   :to="{ name: 'task', params: {key: task.id} }"
   :key="task.id"
>
   <span v-text="task.text"></span>
</router-link>
```

**Comment by posva** [comment]
Maybe it comes from the drag & drop library you're using. If it modifies the dom it may mess up with Vue updating it at the same time.

BTW, you can access the id of documents with `.key`: `this.$firebaseRefs.tasks.child(task['.key']).update(updates)`
