### ISSUE TITLE
two-way binding

### ISSUE THREAD

**Issue by tomermes** [vuejs/vuefire#15]
I'm trying to achieve two-way data-binding with vue and firebase.

So that using:
`
firebase: {
				  events: (new Firebase('https://myfirebase.firebaseio.com/events'))
			  },
`

and in the html:
`<li v-for="obj in events">
				<input v-model="obj.id" /><input v-model="obj.event_name" />
			</li>`

will allow me to update firebase directly from the inputs.
Is it currently possible with this project?
how would you implement it?

**Comment by yyx990803** [comment]
This is currently not supported, you will have to manually use a `@input` listener and call a method to update your Firebase ref.
