### ISSUE TITLE
ssrKey: false not working in useDocument

### ISSUE THREAD

**Issue by daviddomkar** [vuejs/vuefire#1504]
### Reproduction

Just set ssrKey to false - it will type warn and also still call onServerPrefetch

### Steps to reproduce the bug

Just set ssrKey to false - it will type warn and also still call onServerPrefetch

### Expected behavior

I would expect setting ssrKey to false disables onServerPrefetch and have correct typings.

### Actual behavior

setting ssrKey to false type warns and also still calls onServerPrefetch

### Additional information

I followed the documentation here: https://vuefire.vuejs.org/guide/ssr.html#Exclude-from-hydration from the behavior and the code in this repo it seems that the feature is not yet implemented?

**Comment by posva** [comment]
It's not implemented yet so in the meantime, I removed it from docs. If you want to implement it, feel free to submit a PR though
