### ISSUE TITLE
firebase sensitive data (.env) appear when view page source

### ISSUE THREAD

**Issue by mazahagenggong** [vuejs/vuefire#1531]
### Reproduction

https://nuxt-website-ma-zaha-1.vercel.app/

### Steps to reproduce the bug

view page source

### Expected behavior

when view page source, firebase data in .env appears in the script

### Actual behavior

Sensitive data in the .env should not be seen by other people

### Additional information

how do I solve it so that the data in .env doesn't appear when view page source?

**Comment by posva** [comment]
This is a nuxt question. Ask in their discussions
