### ISSUE TITLE
Add the Nuxt VueFire example repos to the docs.

### ISSUE THREAD

**Issue by BenJackGill** [vuejs/vuefire#1535]
### What problem is this solving

I was having a lot of problems with SSR and App Check. Took me a few days to stumble upon these fantastic example repos which solved the problem for me:

- https://github.com/posva/nuxt--vuefire-example-blaze-plan
- https://github.com/posva/nuxt--vuefire-example-spark-plan

### Proposed solution

I suggest you prominently feature these repos at the top of the in the [Nuxt Getting Started](https://vuefire.vuejs.org/nuxt/getting-started.html) doc section to ensure other people can easily find this valuable resource.

**Comment by posva** [comment]
They are actually in the deployment page since the complexity comes from deploying more than developing. We could add them to the top too.
