### ISSUE TITLE
Error($bindAsObject is not a function) occurred

### ISSUE THREAD

**Issue by taishikato** [vuejs/vuefire#156]
Hi.
I wanna use firestore in my web app and I found [this](https://github.com/vuejs/vuefire/issues/145).
So I did 
```bash
npm i vuefire@next
```
and I got this error↓
```
TypeError: _this.$bindAsObject is not a function
```

`bindAsObject` function was working well before I installed vuefire@next.

How can I solve this problem??

Thank you!

**Comment by posva** [comment]
You don't need to specify anymore if it's a collection or a document 🙂 , so it's just `$bind`: https://github.com/vuejs/vuefire/blob/firestore/examples/index.html#L113

**Comment by taishikato** [comment]
Thank you 😄
