### ISSUE TITLE
How do I pass data from one reference to another?

### ISSUE THREAD

**Issue by notflip** [vuejs/vuefire#159]
Hi,

I would like to pass data from newUser to my Users table when pressing a button. I think I'm close but the following isn't working

    export default {
        firebase: {
            users: db.ref('users'),
            newuser: db.ref('newuser').limitToLast(1)
        },
        methods: {
            saveUser() {

                this.$firebaseRefs.users.push({
                    id: this.$firebaseRefs.newuser.id
                });
            }
        }
    }

Any help is welcome! Thank you

**Comment by posva** [comment]
If you're looking for the `id`, it's named `.key`. But what you're looking for is more how to create an id before adding the user 🤔. I think I saw that in Firebase documentation but don't have the link at hand.
Closing since we use issues for features and bug 🙂
