### ISSUE TITLE
Uncaught TypeError: _firebase2.default is not a constructor

### ISSUE THREAD

**Issue by Pixelime** [vuejs/vuefire#16]
Hello,
I am trying to run the following simple line of code in my _main.js_ file:
`var Users = new Firebase('https://vue-demo.firebaseIO.com/users');`
and I get this weird error:
`Uncaught TypeError: _firebase2.default is not a constructor`

Any idea? it's driving me crazy! :(

FYI, I am using Vue js, vue fire and firebase all installed through npm. 
Thanks!

**Comment by weislanes** [comment]
Might you be using Firebase 3.x.x with this version of Vuefire? 

This version of vuefire is currently for Firebase 2.x. The code to make it compatible with Firebase 3.x.x hasn't been merged yet. 

So check that.

**Comment by jwngr** [comment]
You should be able to use the Firebase `3.x.x` SDK with the just-released VueFire `1.1.0`.

**Comment by weislanes** [comment]
@jwngr  Awesome. Do we have to build it ourselves or will the vuefire.js and vuefire.min.js files in the dist be updated as well?

**Comment by jwngr** [comment]
Installation instructions are [here](https://cdn.jsdelivr.net/vuefire/1.1.0/vuefire.min.js). Looks like @yyx990803 still needs to add the latest release to the CDN and create a new release for it [here](https://github.com/vuejs/vuefire/releases). In the meantime, you can get it via the `npm install` method.

**Comment by weislanes** [comment]
Got it! Thanks for your help.
