### ISSUE TITLE
Don't show .key value when looping an array

### ISSUE THREAD

**Issue by notflip** [vuejs/vuefire#162]
Thanks for the great plugin, to begin with! 

I'm having an issue where when I loop over a nested array. It's also showing the .key in my list

    { "-L59MgW3MEo3i1Mu9xME": { "shots": "1", "timestamp": 1518444923016 }, "-L59MjCCZcH5ni9SfwUr": { "shots": 1, "timestamp": 1518444934033 }, ".key": "046a9d02f54880" }

Any idea how I can remove that from the list?

**Comment by posva** [comment]
I'm glad you like it!
You need to remove it for the moment. It is enumerable for the realtime database but it isn't for Firestore. See https://github.com/vuejs/vuefire/issues/72#issuecomment-300498541
There's a PR for this at https://github.com/vuejs/vuefire/pull/121 

Please, use the search feature on Github issues 😛
