### ISSUE TITLE
How to listen to certain refs? 

### ISSUE THREAD

**Issue by notflip** [vuejs/vuefire#163]
For example, is it possible to run a custom function every time the value of a ref changes? I don't see this in the docs. Thank you!

**Comment by posva** [comment]
just watch the value
Please, ask questions in the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Issues are for bug reports and feature requests 🙂

**Comment by notflip** [comment]
I still haven't found an answer. What do you mean with "just watch it". 
**I'm trying to increase a number every time something changes.**. Is it possible to watch for changes in a certain ref? Don't see it in the docs.. Thank you

**Comment by notflip** [comment]
Is this supposed to work?

        firebase: {
            users: db.ref('users')
        },
        watch: {
            users() {
                console.log('updated');
            }
        },
