### ISSUE TITLE
Minimal Firestore not working

### ISSUE THREAD

**Issue by weavermedia** [vuejs/vuefire#166]
I'm using vuefire2.0.0-alpha.6 and can't get a minimal implementation of Firestore working. Am I doing something wrong or is this just alpha behavior?

https://codepen.io/weavermedia/pen/RQQRZJ

Uncomment the `created ()` block to confirm that there is data available in the collection.

**Comment by posva** [comment]
You don't need that block. You're just missing using Vuefire and the `firestore` property

```js
const db = firebase.firestore();

Vue.use(Vuefire.default)

var app = new Vue({
  el: '#app',
  data: {
    message: 'Vuefire & Firestore',
    items: []
  },

  firestore: {
    items: db.collection('items')
  }
})
```

Take a look at the xample: https://github.com/vuejs/vuefire/blob/firestore/examples/index.html

**Comment by weavermedia** [comment]
Sweet! Thanks 👍
