### ISSUE TITLE
Firebase rules issues (data retrieved even if Client doesn't have permission to access data)

### ISSUE THREAD

**Issue by kevinmarrec** [vuejs/vuefire#168]
Here is my code (my Vue component created hook):
```
data () {
    return {
      users: []
    }
  },
created () {
    this.$watch('currentUser', (currentUser) => {
      if (currentUser) {
        firebase.database().ref('users').once('value').catch(error => {
          console.log(error)
        })
        this.$bindAsArray('users', firebase.database().ref('users'))
      }
    }, {
      immediate: true
    })
  }
```

`firebase.database().ref('users').once('value')` displays an error in my console :
```
Error: permission_denied at /users: Client doesn't have permission to access the desired data.
    at Object.exports.errorForServerCode (webpack-internal:///./node_modules/@firebase/database/dist/cjs/src/core/util/util.js:513)
    at onComplete (webpack-internal:///./node_modules/@firebase/database/dist/cjs/src/core/SyncTree.js:538)
    at Object.eval [as onComplete] (webpack-internal:///./node_modules/@firebase/database/dist/cjs/src/core/Repo.js:115)
    at eval (PersistentConnection.js?2227:180)
    at PersistentConnection.onDataMessage_ (PersistentConnection.js?2227:435)
    at Connection.onDataMessage_ (Connection.js?da35:262)
    at Connection.onPrimaryMessageReceived_ (Connection.js?da35:256)
    at WebSocketConnection.eval [as onMessage] (Connection.js?da35:157)
    at WebSocketConnection.appendFrame_ (WebSocketConnection.js?1357:197)
    at WebSocketConnection.handleIncomingFrame (WebSocketConnection.js?1357:247)
```

It's normal, cause I set my Firebase rules ".write" and ".read" to "false" for this path ("/users").

So, I should not be able to retrieve the data, right ?

But `this.$bindAsArray('users', firebase.database().ref('users'))` retrieve the data, so it doesn't care about Firebase Security rules. I checked the Vuefire source code, and the only solution I found was to use the cancelCallback as following :

```
this.$bindAsArray('users', firebase.database().ref('users'), () => {
     this.$unbind('users')
     this.users = []
   })
```

But it can't be right, cause there is like one or less than one second where the data is retrieved and bound to "users" (The "users" array backs to an empty array only when the cancelCallback is called), so if I display the "users" property of my Vue instance, there is a time where the users are displayed, even if the current user logged in ( using Firebase Auth) doesn't have permission to retrieve data from the "/users" path of my Firebase RealTime Database.

Is there any fix to never retrieve the data if the client doesn't have permission to access the desired data ?

Thanks in advance.

**Comment by posva** [comment]
The data should never be retrieved, but if it happens, that's a bug that must be fixed in Firebase end, not vuefire's.

Are you saying that the `users` property is set to an empty array even though there's no data retrieved? If it is, then I agree we could not set it to an array if it fails but I would have to check what impact does it have

**Comment by kevinmarrec** [comment]
Here is my Firebase rules :
```
{
  "rules": {
    "users": {
      "$id": {
        ".validate": "newData.hasChildren(['email', 'firstName', 'lastName', 'photoURL'])",
        "email": {
          ".validate": "newData.isString()"
        },
        "firstName": {
          ".validate": "newData.isString()"
        },
        "lastName": {
          ".validate": "newData.isString()"
        },
        "photoURL": {
          ".validate": "newData.isString()"
        },
        "$other": {
          ".validate": "false"
        },
        ".read": "auth != null && auth.uid == $id",
        ".write": "auth != null && auth.uid == $id"
      }
    }
  }
}
```
The client should be only able to only read/write on "/users/{his_id}"

I tested and the results are :
Using Firebase Rules Simulation on "/users" -> Not permitted
In my app : the data is retrieved -> Users are displayed

With the following rules (Default private database rules)
```
{
  "rules": {
    ".read": false,
    ".write": false
  }
}
```
-> No data is retrieved at all -> Empty "users" Array

Can we conclude that there is an issue with Firebase Rules check ?

**Comment by kevinmarrec** [comment]
But using
`firebase.database().ref('users').once('value')`

I correctly can see that the client is not able to get the data, so it should be an issue with the firebase.database().ref('users').on('child_added') binding which doesn't check permissions

**Comment by kevinmarrec** [comment]
OK ! I solved the issue by myself, testing with the two following rules and 2 users in my Database :
```
{
  "rules": {
    "users": {
      ".read": false,
      ".write": false,
      "$uid": {
        ".read": true,
        ".write": true
      }
    }
  }
}
```
-> Result : users are retrieved but only with one user, the current user loggend in (checked iwth uid) !

```
{
  "rules": {
    "users": {
      ".read": true, // ALLOWS TO GET ALL USERS
      ".write": false,
      "$uid": {
        ".read": true,
        ".write": true
      }
    }
  }
}
```

-> Result : all users are retrieved

So : I didn't know that using "$uid" with Firebase rules automatically bound a new rule which allows to get his parent ('/users') data, even if ".read" is set to false, but only for itself (only User 1 if $uid = 1)

**Comment by posva** [comment]
Thanks for posting back your results 😉
