### ISSUE TITLE
(Feature) Better readyCallback

### ISSUE THREAD

**Issue by kevinmarrec** [vuejs/vuefire#169]
It would be cool if the readyCallback passed to the "$bindAsArray" and "$bindAsObject" functions fires when any event triggers, to know when the data is updated via VueFire.

Cause actually, the readyCallback is weird, using "ref.once('value')", so if a readyCallback is passed to "$bindAsObject",  2 requests are sent to Firebase and readyCallback is triggered only once BTW.

I know how to do it, but before code it and do a Pull-request, I prefer know if some people would be interested.

Kevin.

**Comment by kevinmarrec** [comment]
We can also still keep the readyCallback as it actually works, and do what I suggested with a new callback named like "updateCallback" or any other name, which will be passed as the fifth parameter (after the readyCallback one) of $bindAsObject and $bindAsArray, and eventually in the "bind" (see Source code "bind" method) getting it from the source parameter, as cancelCallback and readyCallback.

**Comment by posva** [comment]
I don't get what is missing, could you provide a simple repro in a fiddle please?

**Comment by kevinmarrec** [comment]
I probably didn't well described what the new feature is but I'll provide a fiddle after my daily job.

The idea : call a callBack everytime data is updated. the readyCallback doesn't do it, it only fires once, when object bound ("bind" function).

**Comment by posva** [comment]
There's no need for such a callback as you can just watch the data instead

**Comment by kevinmarrec** [comment]
That's right, but by convenience It would be cleaner to not to have to watch each object we bound, and add a simply optional callBack to the $bind method.

**Comment by posva** [comment]
A watch is really the simplest way 😄 It's there for that kind of things so I really recommend you to use it 👍

**Comment by kevinmarrec** [comment]
I totally agree but I think there will be cases where the watched property will be updated elsewhere in the code and not getting data from Firebase , so the watcher won't be able to know if the value has been updated fetching Firebase data or has just been hard set by the application 😀

**Comment by posva** [comment]
You shouldn't manually update the data that comes from Firebase. As that is a very specific use case, you will have to create some listeners on the reference and listen to them

**Comment by kevinmarrec** [comment]
Ok, that makes sense, It's a very specific use case as you said.

Anyway, Thanks for your time, I'm now no longer confused :)
