### ISSUE TITLE
Firestore & props?

### ISSUE THREAD

**Issue by palaima** [vuejs/vuefire#171]
Hey,
Consider such example
```
export default {
  name: "View",
  props: {
    todoName: String
  },
  firestore: {
    todos: db.collection("todos").where("name", "==", this.todoName)
  }
}
```
Error is thrown that `todoName` is undefined even though I'm passing prop, same happens with computed props. Any ideas how to achieve sure functionality?

**Comment by posva** [comment]
Use a function instead of an object if you need access to props 🙂

**Comment by foufrix** [comment]
In case someone is looking for answer : 
https://stackoverflow.com/questions/46259685/how-can-i-use-a-prop-as-part-of-the-firebase-path-using-vuefire

You need to create a hook : 
```javascript
import db from '@/firebase'

export default {
    name: 'meal',
   data() {
      return {
        meal: '',
      };
    },
    props: {
        id: {
            type: String,
            required: true
        }
    },
   created() {
        this.$bindAsObject('meal', db.ref('meals').child(this.id))
    }
}
```

**Comment by charles-allen** [comment]
@foufrix - Err... the code in that StackOverflow answer is this, which is suspect is also wrong since shouldn't it be `firestore()` not `firebase()`???
```
import db from '@/firebase'

export default {
    name: 'meal',
    props: {
        id: {
            type: String,
            required: true
        }
    },
    firebase() {
        const id = this.$props.id // Pass the reference instead of the prop directly
        return {
          meals: db.ref('meals').child(id)
        }
    }
}
```
