### ISSUE TITLE
$bindAsArray undefined in watcher

### ISSUE THREAD

**Issue by coolhand79** [vuejs/vuefire#172]
I'm having a hard time getting $bindAsArray to work in a watcher:

`export default {
        name: 'Notifications',

        data: () => ({
            notifications: []
        }),

        watch: {
            currentApp: function (newApp, oldApp) {
                if (newApp.id && newApp != oldApp) {
                    this.$bindAsArray('notifications', db.collection('outcomes').where('app_id', '==', newApp.id));
                }
            }
        },

        computed: {
            ...mapGetters(['currentApp'])
        }
    }`

No matter what I do, currentApp watcher runs, this.$bindAsArray is undefined. Is there something I'm doing wrong?

**Comment by posva** [comment]
It looks like you're using Firestore, you don't need to specify it is an array anymore, `$bind` will do 🙂

**Comment by coolhand79** [comment]
Awesome, thanks!
