### ISSUE TITLE
Using Realtime DB and Firestore Refs together

### ISSUE THREAD

**Issue by Reiss-Cashmore** [vuejs/vuefire#188]
Hi,

I'm trying to use both Firestore and RealtimeDB refs in my app simulataneously.

However when I initialise my Firebase Refs in the Firestore object on the Vue component I get an error.
```

export default {
    name: 'Summary',
    firestore:function(){
      return {
        posts: Firebase.firestore.collection('posts'),
        users: Firebase.realtimedb.ref('/users')
      }
   },
}
```

The error:
```
vuefire.esm.js?bbf5:334 Uncaught (in promise) TypeError: document.onSnapshot is not a function
    at bindDocument (vuefire.esm.js?bbf5:334)
    at eval (vuefire.esm.js?bbf5:371)
    at new Promise (<anonymous>)
    at bind (vuefire.esm.js?bbf5:360)
    at VueComponent.Vue.$bind (vuefire.esm.js?bbf5:420)
    at eval (vuefire.esm.js?bbf5:400)
    at Array.forEach (<anonymous>)
    at VueComponent.created (vuefire.esm.js?bbf5:399)
    at callHook (vue.esm.js?65d7:2921)
    at VueComponent.Vue._init (vue.esm.js?65d7:4630)
```

I also tried manually binding the refs in the vue component created() function like so:

```
created() {
   this.$bind('users', Firebase.realtimedb.ref('/users'))
}
```

Which results in the same error.

Am I doing something wrong? I'm just replicating the setup I had before using the Firestore branch of VueFire and beginning the migration of some of my Realtime DB calls.

Thanks

FYI if the naming of my Firebase objects is confusing. This is how my Firebase object is initialised:

```
  import _firebase from 'firebase'

  let config = {
     ...{{PROJECT SPECIFIC CONFIG}}
  };

let settings = {timestampsInSnapshots: true};

  let app = _firebase.initializeApp(config)
  let realtimedb = app.database();
  let firestore = app.firestore();
  firestore.settings(settings)

  var _signOut = function() {
    app.auth().signOut().then(function() {
      // Sign-out successful.
    }).catch(function(error) {
      // An error happened.
    });
  }

  export const Firebase = {
    app: app,
    realtimedb: realtimedb,
    firestore: firestore,
    instance: _firebase,
    signOut:_signOut

  };

```

**Comment by posva** [comment]
if you manage to include both versions of vuefire (latest and next at the moment), you have to use `firebase` along with `$bindAs*` functions for the RTDB.

I'm interested in why would somebody use both at the same time as you can only have one database per project

**Comment by Reiss-Cashmore** [comment]
By the way I did manage to solve registering both package versions in the same app with some pretty small and simple changes. I can create a PR if you would like to review.

**Comment by posva** [comment]
I would be interested in seeing the changes yes, although the code base is going through deep changes in order to combine with vuexfire but still, could learn a thing or two 🙂

**Comment by posva** [comment]
Now that the code is organised in a mono repo with multiple packages, this should be doable in vuefire-core and added to both vuefire and vuexfire while being tree-shakable. It will probably need an API redesign

**Comment by posva** [comment]
I added RTDB support for vuefire and still need to add it to vuexfire.
*I will like to get others opinion on API*. Currently my plans (some are already done) are

- Replace `default` export from Vuefire to `firestorePlugin`
- Export `rtdbPlugin` for the RTDB
- Keep `$bind` for Firestore but make it configurable with options when installing `firestorePlugin`
- Use `$rtdbBind` for RTDB but make it configurable with options when installing `rtdbPlugin`
- same for `$unbind` / `$rtdbUnbind`. _The reasoning behind this is: I want to make it simpler by default for Firestore users as that database is more likely to be used
- Give access to used refs through `$firebaseRefs` / `$firestoreRefs`

This makes it possible to use only a fraction of Vuefire/Vuexfire as well as use them both:

```js
import { firestorePlugin, rtdbPlugin } from 'vuefire'

// rename $bind -> $fsBind, $unbind -> $fsUnbind
Vue.use(firestorePlugin, { bindFnName: '$fsBind', unbindFnName: '$fsUnbind' })
// rename $rtdbBind -> $bind, $rtdbUnbind -> $unbind
Vue.use(rtdbPlugin, { bindFnName: '$bind', unbindFnName: '$unbind' })

new Vue({
  // for the RTDB, it is mandatory to use an array so binding binds as an array
  // Firestore doesn't need that because there is a clear difference between
  // documents and collections
  data: { items: [], item: null, fsItems: null, fsItem: null },
  firebase: { items: db.child('items'), item: db.child('item') },
  firestore: { items: fsdb.collection('items'), item: fsdb.collection('data').doc('item') },
})
```

**Comment by posva** [comment]
this has been fully implemented in the branch named feat/rtdb. As it involves breaking changes, I will make sure to provide documentation before releasing a new version. And after some time that will also mean it's time to release as regular versions

**Comment by cairinmichie** [comment]
@posva for clarification is the vuexfire@next branch capable of handling both? Or does this only work on the feat/rtdb branch still?

**Comment by posva** [comment]
It hasn't been released yet because I have been working in docs and haven't been able to work on it since Jan. There are some breaking changes, that's why I want docs to be up to date before releasing.
It will still be in `next` tag of npm and the branch is indeed feat/rtdb (you can always get it yourself locally)

**Comment by ryanpaulfyfe** [comment]
Hi @posva Is RTDB supported now in vuexfire?

**Comment by posva** [comment]
As stated on this pr and the docs, yes, Vuexfire supports rtdb

**Comment by ryanpaulfyfe** [comment]
Thanks for quick response. I didn't find the docs clear in this regard. Will work to figure it out now :+1:
