### ISSUE TITLE
How can I mock firebase for unit testing?

### ISSUE THREAD

**Issue by fmontes** [vuejs/vuefire#189]
Hi guys,

I'm using ```VueFire``` but I can't find a way to unit test the component where I use ```this.$firestoreRefs``` or even

```javascript
    firestore() {
        return {
            inventory: fs.collection('inventories').doc(this.$route.params.id)
        };
    },
```

My only kind of solution is do a mock when I shallowMount my component like:

```javascript
        wrapper = shallowMount(InventoryDetail, {
            localVue,
            router,
            mocks: {
                $firestoreRefs: {
                    inventory: {
                        get() {
                            return Promise.resolve({
                                ref: {
                                    collection() {
                                        return {
                                            onSnapshot() {
                                                return {
                                                    docs: [
                                                        {
                                                            data() {
                                                                return {
                                                                    content: []
                                                                };
                                                            }
                                                        }
                                                    ]
                                                };
                                            }
                                        };
                                    }
                                }
                            });
                        }
                    }
                }
            }
        });
    });
```

But I think this is a wrong way of doing it.

Any help will be welcome.

Regards.

**Comment by posva** [comment]
Google Firebase mock. There is a package for that :)

**Comment by Plinpod** [comment]
@fmontes Did you find a solution for this. I attempted using this package 
https://github.com/soumak77/firebase-mock 
But was unable to get it integrated properly with the `this.$firebaseDB` scenario

**Comment by did** [comment]
hi @posva, first of all, thanks for your work on this amazing plugin!
There is indeed a package for that and it's called `firebase-mock` (you seem to use it for your own tests). 
Unfortunately, it doesn't work out of the box with vuefire (a cryptic error pops up, `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined` when binding a collection in a vue component). 
By digging in your code, I've seen that you used an internal package called `vuefire-test-helpers` which would be super useful. However I can't use as it in my **non typescript** project. 

In my Jest file, I've got a simple call to your lib:
```
import utils from '@posva/vuefire-test-helpers'
```

Running the test outputs this: 
```
    /Users/didier/Documents/NoCoffee/XXXX/YYYYY/node_modules/@posva/vuefire-test-helpers/src/index.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vue from 'vue'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Any idea?

Thanks for your help!
