### ISSUE TITLE
pass firebase ref item to child component as a prop

### ISSUE THREAD

**Issue by GiovanniCardamone** [vuejs/vuefire#190]
i have this component:
```js
export default {
  name: 'AComponent',
  data () {
    return {
      selected_user: null
    }
  },
  firebase () {
    return {
      users: {
        source: firebase.database().ref('/users/')
      }
    }
  }
}
```

now, if i connect to some user
es:
```js
this.selected_user = this.users[someIndex]
```

```html
<template>
  <div>
    <AChildComponent :user="selected_user" />
  </div>
</template>
```

```js
export default {
  name: 'AChildComponent',
  props: ['user']
}
```

and i want to propagate to child component with props, i noticed the updates coming from firebase is not "captured" in childs.
So, if some data change, i don't know it.

i 'm missunderstanding something?

**Comment by posva** [comment]
It should work, you probably want to use a computed property though

**Comment by posva** [comment]
If you have a very minimal repro (eg:based on the jsfiddle demo), I can take a look

**Comment by trevorgreenleaf** [comment]
I am having issues with this also. Do you have a working demo?

**Comment by posva** [comment]
no, but if you build a boiled down codepen or jsfiddle or even a simple html page (no github repo please) I will take a look 😉 (you can fork an existing one in the examples)
