### ISSUE TITLE
Firestore, getting current user

### ISSUE THREAD

**Issue by dennisjanssen** [vuejs/vuefire#193]
Hi,

I have a quick question. I'm in no way a programmer, so bear with me.

I'm trying to do this:
`firestore: {
      documents: db.collection('documents').orderBy('createdAt', 'desc'),
      users: db.collection('users'),
      user: db.collection("users").doc(firebase.auth().currentUser.uid),
  },`

Sadly, I'm getting this error, since I'm guessing the code above is called before the user is fully authenticated with firebase.

`Uncaught TypeError: Cannot read property 'uid' of null`

I've worked around this by querying the current user later on in the code, but somehow it loses reactivity that way. But maybe I've made mistakes there as well.

Any pointers on how to do this would be very welcome!

**Comment by posva** [comment]
Hello!
Unfortunately we keep issues for bug reports and feature requests. You should try StackOverflow to seek help.
In your case I would say the user is not logged in yet, you will need to use `onAuthStateChanged` and then $bind or set the user with the callback value (https://firebase.google.com/docs/reference/js/firebase.auth.Auth)
