### ISSUE TITLE
Need help with simple joins

### ISSUE THREAD

**Issue by fergardi** [vuejs/vuefire#196]
Hello!

I love your project, and use it in almost any VueJS project I made.

But usually I find myself struggling in a (maybe not so) simple case like this one:

Say we have a collection A, with books:

```json
{
  "bookRef1": {
    "name": "book1",
    "authorRef": "authorRef1",
    "price": 30
  },
  "bookRef2": {
    "name": "book2",
    "authorRef": "authorRef1",
    "price": 20
  }
}
```

A collection B with authors of those books:

```json
{
  "authorRef1": {
    "name": "John Doe"
  }
}
```

And a collection C, with comments of those books:

```json
{
  "commentRef1": {
    "text": "comment about book1",
    "timestamp": 0,
    "bookRef": "bookRef1"
  }
}
```

And I need this result, in a single query to the books collection:

```json
{
  "bookRef1": {
    "ref": "bookRef1",
    "name": "book1",
    "author": {
      "ref": "authorRef1",
      "name": "John Doe"
    },
    "price": 30,
    "comments": [
      {
        "ref": "commentRef1",
        "text": "comment about book1",
        "timestamp": 0
      }
    ]
  },
  "bookRef2": {
    "ref": "bookRef2",
    "name": "book2",
    "author": {
      "ref": "authorRef1",
      "name": "John Doe"
    },
    "price": 20,
    "comments": []
  }
}
```

I know I can make individual queries to fit my needs, but how can I achieve this results with firebase + vue reactivity to maintain my data updated at all times, and with nesting data complexity?

I've read many tutorials on flatting data using firebase to use references for joins as in SQL, and even duplicate data in the collections to ensure fast results and batch updating all collections that share the data at the same time (which for me it seems a little bit troubleing and hard to maintain if the structure changes on time).

Which way should be the best for achieveing this result?

Thanks in advance.

**Comment by posva** [comment]
Hello, I'm glad you like the project :slightly_smiling_face: 
The thing is it doesn't matter you are using Vue :smile: . This is actually a firebase question but I don't have the bandwidth to help out with Firebase questions sorry.
Once you get the query working with Firebase, feed that to vuefire and it will work :slightly_smiling_face:
