### ISSUE TITLE
Catching error if user does not have permissions

### ISSUE THREAD

**Issue by Johnhhorton** [vuejs/vuefire#197]
Using 2.0.0-alpha.12

```
{
...
firestore(){
    return {
      site: this.$firestore.collection('sites').doc(this.id + 'd')
    }
  },
...
```

I'm trying to get a document by ID, but with the code above I've forced a failure condition. I want to be able to capture whether or not there's an error, within the component where this is referenced, and display some general error to the user as a result. Currently the only thing I get back is an empty array, and while can show an error condition as a result of that (on a single document), I'd love a clearer method.

Do you have any recommendations?

**Comment by posva** [comment]
Use the $bind method that returns a promise and catch it. It should contain the error
