### ISSUE TITLE
unsupported or error to firestore ref type

### ISSUE THREAD

**Issue by OsirisFrik** [vuejs/vuefire#198]
i tried to save reference to another document, but, when i use
```
this.$firestoreRefs['VALUE'].doc('DOC').update({
    refTo: db.collections('COLL').doc('DOC')
})
```

thrown error to the console with this message

> Function CollectionReference.doc() requires its first argument to be of type string, but it was: undefined

**Comment by posva** [comment]
The code looks correct, but cannot help you at all without a repro.
In any case, it's an error coming from the firebase SDK, not vuefire 🙂

**Comment by OsirisFrik** [comment]
@posva when i use only firebase sdk, working correctly, but when i use the plugin show the error... so... im not sure from where is the error

**Comment by posva** [comment]
Well, I will need a boiled down repro in a jsfiddle to check it
