### ISSUE TITLE
 how to use vuex in a query?

### ISSUE THREAD

**Issue by welitonjose** [vuejs/vuefire#199]
Hello
I'm new to vuejs and I'm delighted.
I have a question about how I can use a state vuex in a query ..

I'm trying

`firebase: {
      articles: {source: db.ref('articles/'+ this.$store.state.articleId), asObject: true}
    }`

return this
> Cannot read property '$store' of undefined

I may be wrong because I do not understand so much about you.
but it looks like the vuefire is ridden before the vuex.
someone help me please

**Comment by posva** [comment]
I recommend you to use a watcher for that store property or a computed value returning that value and call the bindAsObject function inside Of the watcher
