### ISSUE TITLE
src folder is missing after npm install

### ISSUE THREAD

**Issue by patrikengborg** [vuejs/vuefire#2]
For some reason the src folder is missing after 'npm install vuefire', which causes:
`Module not found: Error: Cannot resolve module 'vuefire' ` in webpack

**Comment by jwngr** [comment]
Thanks for reporting! It looks like the [`package.json`'s `"main"` key](https://github.com/vuejs/vuefire/blob/c692c4a1d7a4b87906a2241a641fce12c5dc56bd/package.json#L5) points to `"src/vuefire.js"` when it should really be `"dist/vuefire.js"`. I'll put together a fix and we can cut a new release.

**Comment by jwngr** [comment]
Also, the reason using `"src/vuefire.js"` doesn't work is because it's not actually packaged up in the npm package itself. We only include [the files mentioned in `package.json`'s `"files"` key](https://github.com/vuejs/vuefire/blob/c692c4a1d7a4b87906a2241a641fce12c5dc56bd/package.json#L6-L10).

**Comment by Saqib-diar** [comment]
sir,
I did not got exactly what you are saying.
src folder is missing when i install npm like
npx creat-react-app uet
it does not create src folder!!

**Comment by Saqib-diar** [comment]
sir it just created folder for me like node_module and packages
