### ISSUE TITLE
Could I use `Vuefire` for large app such as `Mongo, MySQL...` (Loan, Accounting, POS ... Systems)

### ISSUE THREAD

**Issue by thearabbit** [vuejs/vuefire#200]
I base on `Meteor + Mongodb` to create app such as: Loan, Accounting, POS, ....
Could I use `Vue+Firebase` for large app like this?

**Comment by posva** [comment]
yes, I don't see why not :)

**Comment by thearabbit** [comment]
Thanks for your reply, but I found the blog
```
MongoDB can be run locally, or hosted on many different cloud based providers. Firebase, in my opinion is great for smaller apps, very quick to get up and running. MongoDB is ideal for more robust larger apps, real-time integration is possible but it takes a bit more work.
```

**Comment by posva** [comment]
You mean you found a blog 😄
Firebase can be used for larger apps, specially real-time ones. I don't work for Firebase tho
