### ISSUE TITLE
How to use Nuxt with VueFire and SSR

### ISSUE THREAD

**Issue by ReeVicente** [vuejs/vuefire#203]
I dont understand how that works, please add to dock or give me a example

**Comment by posva** [comment]
It is indeed missing the docs. The whole idea goes around `$bind` returning a promise that resolves once the data is ready. So you can wait for it in `asyncData`:


```js
data: () => ({ items: [] }), // initialise items
async asyncData () {
  await this.$bind('items', db.collection('items')
  // no need to return the data as it is bound in data  
  return {}
}
```

**Comment by dac3971** [comment]
@posva you don't have access to `this` from asyncData https://nuxtjs.org/api/

**Comment by posva** [comment]
Forgot about that! With vuexfire you can still access the store from the context passed to asyncdata but with vuefire it's a bit different. It should be possible to call $bind through the Vue constructor with something like Vue.prototype.$bind.call({}) and await that promise in one asyncdata property but I need to check a bit more since the whole point of using bind was to make it work both on client and on server

**Comment by max8hine** [comment]
Hi All,

I could not find `this.$bind` in Nuxt's `asyncData()`, but I could find `this.$nuxt.$bind` in Nuxt's `asyncData`.

I tried something below and no success
``` javascript
data: () => ({ text: '' }), // initialise items
async asyncData () {
  await this.$nuxt.$bind('text', db.collection('text').doc('text'))
  return
}
```

I use Nuxt plugin to add `vue-fire`

**Comment by posva** [comment]
This is not yet supported on vuefire package. It's only supported by vuefire since you can await an action in fetch or asyncdata. I need to find a way to fix hydration and will expose a nuxt plugin or module in the future to enable ssr wot vuefire.

**Comment by agcty** [comment]
> This is not yet supported on vuefire package. It's only supported by vuexfire since you can await an action in fetch or asyncdata. I need to find a way to fix hydration and will expose a nuxt plugin or module in the future to enable ssr wot vuefire.

Is there any update on this? Would be really awesome

**Comment by posva** [comment]
No updates no. For the moment use vuexfire, it's more adapted to bigger apps anyway :). When you are doing SSR, your app isn't that simple anymore.

**Comment by chasebank** [comment]
@posva I understand the vuexfire repo has now been archived, but is there any chance you could take another look at https://github.com/posva/vuexfire/issues/124#issuecomment-469146657 and address it here?

I linked to a (not working) [demo repo](https://github.com/chasebank/nuxt-firebase-vuexfire) in that thread. Someone just commented on the demo, also looking for help with Nuxt and vuexfire, but I still haven't figured it out.

Thanks so much for your hard work!

**Comment by posva** [comment]
vuexfire is now here, that's why it got archived. I'll paste the example I put there about how to use Vuexfire with Nuxt:

```js
// firebase/index.js
import { firebase } from '@firebase/app'
import 'firebase/firestore'
import 'firebase/auth'

const config = {
  apiKey: '...',
  authDomain: '...',
  projectId: '...',
}

export const db = firebase.initializeApp(config).firestore()


// Export utility functions
export const { Timestamp } = firebase.firestore
```

```js
// firebase/collections.js
import { db } from './index'

export const users = db.collection('users')
export const matches = db.collection('matches')
// store/index.js
import { vuexfireMutations as mutations } from 'vuexfire'

export const state = () => ({})

export { mutations }
```

```js
// store/matches.js
import { firestoreAction } from 'vuexfire'
import { matches, users } from '../firebase/collections'

// omitting state, mutations, getters

const actions = {
  subscribeToAllMatches: firestoreAction(({ bindFirestoreRef }) => {
    return bindFirestoreRef('matches', matches)
  }),
  // async version
  subscribeToMatch: firebasestore(async ({ bindFirestoreRef }, { matchRef ) => {
    await bindFirestoreRef('match', matchRef)
  }),
}
```

pages/matches.vue
```vue
<template>
  <div>
    <ul>
      <li v-for="match in matches">{{ match }}</li>
    </ul>
  </div>
</template>

<script>
import { mapActions, mapState } from 'vuex'

export default {
  methods: mapActions('matches', ['subscribeToAllMatches']),
  computed: mapState('matches', ['matches']),

  // return a promise
  fetch() {
    return this.subscribetoAllMatches()
  },
}
</script>
```

**Comment by krisztianodor** [comment]
@posva That's not working for me! I got 'this. subscribetoAllMatches is not a function' error at the fetch hook. But in the create hook it works.

**Comment by trickstival** [comment]
@posva is the nuxt plugin going to be another package?

**Comment by posva** [comment]
a plugin would be part of the package, but not sure yet of the features to add yet

**Comment by lupas** [comment]
I played around with vuexfire and nuxt when testing if vuexfire works with nuxt-fire ([this issue](https://github.com/lupas/nuxt-fire/issues/30)), and I got it to work just fine.

Without using fetch() but using the created() hook.

I created this example repository for vuexfire with nuxt-fire, I hope it helps someone:
[https://github.com/lupas/nuxt-fire-vuexfire-example](https://github.com/lupas/nuxt-fire-vuexfire-example)

The examples uses SSR (resp. nuxt generate) and not SPA mode.

**Comment by posva** [comment]
but using the `created` hook instead of `fetch` doesn't wait for it before rendering on SSR, waiting for the action is the whole point. @krisztianodor let me update the comment, I'm using a method but they are not accessible in `fetch`

**Comment by krisztianodor** [comment]
How to make it reactive while ssr? After the first load i have content, but it's not reactive, only after i bind again on client side. But when i bind, it automatically unbinds the previously bound property, which means that the property is reseted  (null / [] / ...) and there is a flash on the site before the client subscribe ending.

[https://vuefire.vuejs.org/api/vuefire.html#bind](url)

**Comment by posva** [comment]
@krisztianodor that is something being tracked at https://github.com/vuejs/vuefire/issues/83

**Comment by lupas** [comment]
If anyone is still stumbling on this, I made vuexfire work in a Nuxt SSR app with using `async/await` and the new `wait: true` option by binding **once in fetch (for server-side)** and once in **mounted (for client-side)**:

See comment: https://github.com/lupas/nuxt-fire-vuexfire-example/issues/1#issuecomment-560206034 
Entire example: [lupas/nuxt-fire-vuexfire-example](https://github.com/lupas/nuxt-fire-vuexfire-example)

Example is with nuxt-fire, but that shouldn't make a difference.

Only thing that I would like to improve now is **find a way to only need to call the binding action once** and have it automatically be bound on server and client side, anyone an idea?

**Comment by fergusmeiklejohn** [comment]
@lupas Would we want to bind on the server? Maybe the server is just a simple query, get the data we need to render html, then we bind on the client?

**Comment by lupas** [comment]
@fergusmeiklejohn 
Binding on a server does per se not make sense, you are right. Doing a single call on the server and then only binding on the client is for sure the safest way to do it.

But if we want to keep our code simple and make use of vuefire (-> not having to write all the mutations and all that ourselves), this could be an option to save us some lines of code.

My thinking here is that on the server the process could be like so:

1) Do the binding
2) Initial data gets loaded
3) Unbind again
4) Data gets rendered to client

-> probably a bit less performant

Unbinding (e.g. in the destroyed() hook) might be important though to avoid memory leaks. Not sure, I haven't tested it.

**Comment by dosstx** [comment]
Hi guys, something has changed and I am getting a console error on page refresh:

https://i.stack.imgur.com/lISRW.png

Here is my stackoverflow question with details:
https://stackoverflow.com/questions/63827895/vuefire-and-async-fetch-in-nuxtjs-fails-on-page-refresh

Anyone know how to fix?

**Comment by dosstx** [comment]
Please, can someone add an updated guide on how to use Nuxt 2.14 and VueFire? Specifically in light of the new fetch() api? Thank you.

**Comment by dosstx** [comment]
Anyone have thoughts on the above question? Updated documentation for Nuxt would be greatly appreciated!

**Comment by kraeki** [comment]
Hi all, nuxt `2.12` introduced a new `fetch()` hook that triggers on the server-side and on the client-side and has access to component/page data. [Specs](https://nuxtjs.org/docs/components-glossary/fetch/)

IMHO `fetch()` is the best place to bind vuexfire . Would you agree?
However I encounter this issue:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render
```

Here how I use `trainings` (computed property) to print list of trainings inside `<template>`
```
   23       <v-list-item
   24         v-for="(t, idx) in trainings"
   25         v-else
   26         :key="idx"
   27         :to="'dashboard/' + t.id + '/' + todayStr"
   28         class="mb-3"
   29       >
```

Here how I bind in my page inside `<script>`
```
  65 export default Vue.extend({
   66   name: 'YourComponent',
   67   layout: 'DashboardLayout',
   68   data() {
   69     return {
   73       date: moment(),
   74     }
   75   },
   76   async fetch() {
-- 77     // Fetch has access to this. I need that to pass this.weekday to the bind action
   78     await administraStore.initTrainingByWeekday(this.weekday)
   79   },
   80   computed: {
~  81     trainings(): Training[] {
   82       return administraStore.trainingsByWeekday
   83     },
```

Here how `initTrainingByWeekday(this.weekday)` looks like in `store`. 
```
  178   @Action({ rawError: true })
  179   initTrainingByWeekday(weekday: string) {
  180     const action = firestoreAction(({ bindFirestoreRef }) => {  
  181       return Promise.all([
  182         bindFirestoreRef(    
  183           'trainingsByWeekday',
--184           firebase
  185             .firestore()
  186             .collection('trainings')
  187             .where('weekday', '==', weekday),
  188           { wait: true }
  189         ),
  190       ])
  191     }) as Function
  192     return action(this.context)                                                                                                
  193   }                                                                                                                            
```

Does anyone know why I get the hydration mismatch when loading the page? 
Help would be appreciated.

**Comment by posva** [comment]
This is currently being tracked at https://github.com/vuejs/vuefire/issues/1241

For those adventurous enough to try the current nuxt module (Nuxt 3 only although it should work with Bridge too):

- WIP docs: https://vuefire.vuejs.org/nuxt/getting-started.html#nuxt-js
- Working playground:
  - https://github.com/vuejs/vuefire/blob/main/packages/nuxt/playground/nuxt.config.ts#L38-L53
  - https://github.com/posva/nuxt-vuefire-example

Some notes: AppCheck is still a work in progress for SSR. I recommend only prerendering routes and not doing SSR yet when the app is deployed. Refer to Firebase docs for information about AppCheck. The docs will also be updated I added this to [the roadmap](https://github.com/vuejs/vuefire/issues/1241)

**Comment by posva** [comment]
Thanks, that's interesting! It seems that the firebase sdk is not ready yet to run on the edge though. AppCheck and SSR are working better now, still need to update the docs and create some extra playgrounds
