### ISSUE TITLE
firestore.Query type declaration is missing in vue.d.ts

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vuefire#209]
Consider the following TypeScript example

``` typescript
import { Component, Vue } from "vue-property-decorator";
import { db } from "@/utils/firebase-client";

const entries = db.collection("dashboard-entries");

@Component({
  firestore: {
    entries: entries, // returns firestore.CollectionReference
    publishedEntries: entries.where("status", "==", "published") // returns firestore.Query
  }
})
export default class Home extends Vue {
  entries = [];
  publishedEntries = [];
}
```

In such case the TypeScript compiler complains that:

> Argument of type '{ firestore: { entries: CollectionReference; publishedEntries: Query; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, and 'firestore' does not exist in type 'VueClass<Vue>'.

It happens because `publishedEntries` returns `firestore.Query` which is not defined in types delcaration.  Types declaration in `vue.d.ts` looks as follows:

``` typescript
type VueFirestoreObject = Record<
  string,
  firestore.DocumentReference | firestore.CollectionReference
>
```

It should be:

``` typescript
type VueFirestoreObject = Record<
  string,
  firestore.DocumentReference | firestore.CollectionReference | firestore.Query
>
```

**Comment by posva** [comment]
oh right, this is a good first contribution :)

**Comment by pongstr** [comment]
@posva it seems that this line is not in the release tag:

**vuefire@2.0.0-alpha.15** 8a41868b80924d8a5667a1d7222e1a94d7d99482<br>[`packages/vuefire/types/vue.d.ts`](https://github.com/vuejs/vuefire/blob/8a41868b80924d8a5667a1d7222e1a94d7d99482/packages/vuefire/types/vue.d.ts#L30)

**--vs--**

**Lerna Branch** <br>[`packages/vuefire/types/vue.d.ts`](https://github.com/vuejs/vuefire/blob/lerna/packages/vuefire/types/vue.d.ts#L30)

Thanks!

**Comment by posva** [comment]
Published!

**Comment by TP18** [comment]
ERROR in /Users/xx/xxx/node_modules/vuefire/types/vue.d.ts
13:28 Namespace '"firebase"' has no exported member 'Query'.
    11 |     $bind(
    12 |       name: string,
  > 13 |       reference: firestore.Query
       |                            ^
    14 |     ): Promise<firestore.DocumentData[]>
    15 |     $bind(
    16 |       name: string,







  "dependencies": {
    "firebase": "^5.9.2",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vuefire": "^2.0.0-alpha.21"
  },
