### ISSUE TITLE
Change the way how the reference data type is handled or make it configurable

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vuefire#215]
In Firestore there's a [Reference data type](https://firebase.google.com/docs/firestore/manage-data/data-types). When a document that contains references fields is bound by Vuefire, then Vuefire, under the hood, queries all referenced documents and converts referencecs into actual data. This is a nice feature but it has some negative implications:
- The reference is lost. We no longer have an access to it. 
- It performs additional queries, that might be inefficient when large collections are queried.

So it would be great if this behaviour could be configured, or at least if references were not lost - maybe refernces could be added as an non-enumerable properties (the same way as documents' ids are added to objects)?

**Comment by posva** [comment]
Check #153
By default it binds 2 level nested references but you can set it to 0
