### ISSUE TITLE
Could not find a declaration file for module 'vuefire'

### ISSUE THREAD

**Issue by yu-jinm** [vuejs/vuefire#219]
Please take a look at the attached screenshot as I cannot copy the error message (it disappears).

http://prntscr.com/l8pia2

I tried:

```
import VueFire from 'vuefire'
```
and 

```
let VueFire = require('vuefire')
```

The same message appears.

PS: This is the same issue with #218 but was closed for not providing the details (Return key was accidentally pressed)

**Comment by posva** [comment]
if you are using the v1 of vuefire, it doesn't contain typescript typings. Although I would accept a PR for it. I will focus on adding support for RTDB to v2 instead and support typings in v1

**Comment by yu-jinm** [comment]
> if you are using the v1 of vuefire, it doesn't contain typescript typings. Although I would accept a PR for it. I will focus on adding support for RTDB to v2 instead and support typings in v1

Thanks!

**Comment by AaronWoods** [comment]
I am experiencing the same issue, 
How can I resolve this? I updated package version to 2.0.0 alpha from 1.4.5 and am still see the import issue

**Comment by OTANatio** [comment]
Alright so whatss the solution here?
i am also encountering the same problems

**Comment by posva** [comment]
using the `next` tag which has been stable for almost a year and  will be published as the latest tag soon. The typings problem was fixed some time ago
