### ISSUE TITLE
Vuexfire: Typescript support

### ISSUE THREAD

**Issue by nomadoda** [vuejs/vuefire#224]
I can see that typescript support has been added for `vuexfire` but there seems to be no typedefinition files included in the `node_module`. Am I missing something?

**Comment by posva** [comment]
I haven't added types to vuexfire yet

**Comment by kaorun343** [comment]
Shall I make a PR?

**Comment by posva** [comment]
oh, if you want, that would be 💯

**Comment by alexeigs** [comment]
Is there any way to use Vuefire + Typescript (class-style components) by now? I haven't found any documentation nor examples out there.

**Comment by posva** [comment]
It works out of the box. This lib is written in ts

**Comment by alexeigs** [comment]
I haven't found any example showing the right implementation for class-style Vue components. How would the following need to look like in a class-style component?

```
export default {
  name: 'Comics',
  data () {
    return {
      comics: [],
    }
  },
  firestore () {
    return {
      comics: db.collection('comics')
    }
  }
}
```

**Comment by posva** [comment]
it's like this:

```ts
@Component({
  firestore() {
    return {}
  },
})
export default Page extends Vue {}
```

For some reason typings do not work when using `@Component` but they do for regular components. I will have to ask them

BTW, any extra option created by plugins go there (see 5. https://github.com/vuejs/vue-class-component#usage)

**Comment by alexeigs** [comment]
I guess I'm missing the logical understanding of something here (sorry for that).

```
<script lang="ts">
import Vue from 'vue'
import { Component } from 'vue-property-decorator'

@Component({
  firestore() {
    return {}
  }
})
export default class Home extends Vue {}
</script>
```

First, I get the following error (which I may ignore):
`(method) firestore(): {}
Argument of type '{ firestore(): {}; }' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, and 'firestore' does not exist in type 'VueClass<Vue>'.Vetur(2345)`

Second, where do I need to put `db.collection('sample-collection') and how would I now access that data within the script and template of my Vue component?
