### ISSUE TITLE
.key property missing on Firestore queries

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [vuejs/vuefire#234]
Hi,
the plugin works great with the Firebase Realtime DB. I recently tried it with Cloud Firestore. When I bind to a reference query the ids of the documents are not accessible. 
In the version with the Realtime DB it will always add a .key entry to the object. In firestore entries with "." are not correctly supported and a key is not added to the object. This makes it difficult to access objects by their id. 

It would be great if the document id could be added to the object. 

Example query: 
```javascript
bindFirebaseRef('venues', db_module.firestoreQueryRef("venues").where('valuex', "==", true), options);  
```

Reference: 
https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference

Kind regards, 
Alex

**Comment by posva** [comment]
Access them through the id property. It's non enumerable to be avoided on copies so it doesn't print on logs

**Comment by Sn0wfreezeDev** [comment]
Yes I agree this is how it is specified in the firestore documentation. 

Okay I checked the store with the vue dev tools for Chrome and it did not show any id key. But accessing it is possible. 

Thank you for the quick response

**Comment by ydennisy** [comment]
Sorry to bring up a closed thread - but I am having a similar issue and did not get the above solution.

I am accessing a collection with `db.collection('name')`

This returns an array without the `firestore` generated `_key` property, could you let me know how I can access this?

**Comment by ydennisy** [comment]
My bad, it is just a case of using `.id` in the template
