### ISSUE TITLE
Binding as Object

### ISSUE THREAD

**Issue by esezen** [vuejs/vuefire#235]
Hello,

Thanks for this awesome tool. I am using Vuex with modules. I want to bind "inventory" as an object but it binds as an array. Read the documentation and examples but couldn't figure out why. Here is the code.

```javascript
import { db } from '@/db.js'
import { firebaseAction } from 'vuexfire'
const inventory = {
  state: {
    inventory: null,
    inventoryRef: null
  },
  mutations: {
    SET_INVENTORY_REF: (state, ref) => {
      state.inventoryRef = ref
    }
  },
  actions: {
    bindInventoryRef: firebaseAction(({ bindFirebaseRef }, { name, ref }) => {
      bindFirebaseRef(name, ref)
    }),
    setInventoryRef({ rootState, commit, dispatch }) {
      const ref = db.collection(`users/${rootState.uid}/inventory`)
      dispatch('bindInventoryRef', { name: 'inventory', ref })
      commit('SET_INVENTORY_REF', ref)
    }
  }
}

export default inventory
```

Thanks in advance.

**Comment by posva** [comment]
Collections are always bound as arrays, documents are bound as objects :)

**Comment by dnhyde** [comment]
I have a similar issue, where would be the place to insert a converter? And perform operations to convert the collection array to an object to pass to a mutation that will commit the object as state?
