### ISSUE TITLE
startAt/startAfter/etc Vuefire(firestore) + Nuxt (help)

### ISSUE THREAD

**Issue by lucasnsa** [vuejs/vuefire#238]
Hello guys,

I am doing results pagination and I have had issues with startAt in all collections.
startAt, startAfter, endAt, endBefore return wrong results. No matter what the start or end of the query, it returns wrong results.

For exemple
The data set(orderby asc)
```
"Alternativa Esportes Webrádio"
BDUIx2vVjxMUQm0yPMOe

"Atitude Popular"
wPAC9MGe67zWKsfU7z3R

"Bons Tempos FM"
uTDMzx7uDE8esdO1PT5J

"Radio CBN Grandes Lagos 90.9 FM"
twYOkYeb0AGKYJKSTBlX

"Rádio 96 FM Arapiraca"
QaZO7YIbFvnfEFhHUmpw

"Rádio Brasil Hits"
XlPbY80g5tVwviOxzTL7

"Rádio CB FM 92.5"
OPFXrsY0LsiHzOSPrlgk

"Rádio Capital 95.9 FM"
yAjHGUqgpkjXuDFOkIU7
```
after that query
`db.collection("radios").orderBy("nome", "asc").startAfter("BDUIx2vVjxMUQm0yPMOe").limit(2)`

result
```
"Bons Tempos FM"
uTDMzx7uDE8esdO1PT5J

"Radio CBN Grandes Lagos 90.9 FM"
twYOkYeb0AGKYJKSTBlX
```
expected 
```
"Atitude Popular"
wPAC9MGe67zWKsfU7z3R

"Bons Tempos FM"
uTDMzx7uDE8esdO1PT5J
```

This query returns the wrong data set.

Greetings from Brazil.

**Comment by posva** [comment]
hey, this is the repository for vuefire, not Firebase 😄
