### ISSUE TITLE
Allow customizing how the data is stored (id, adding properties, transforming them)

### ISSUE THREAD

**Issue by posva** [vuejs/vuefire#240]
Right now the data is created using https://github.com/vuejs/vuefire/blob/master/packages/%40posva/vuefire-core/src/utils.js#L9-L14

Looking at Firestore extensions like [Geofirestore](https://github.com/geofirestore/geofirestore-js/) that add a `distance` property that is lost upon binding with Vuefire. This would allow adding the `distance` to the object bound.
It would also allow customizing the `key`/`id` attribute although I still feel that having a simple string field is nice.

## API

The api would be the same for firebase and firestore

```js
Vue.use(firestorePlugin, {
  // override createsnapshot
  createSnapshot (doc) {
	return Object.defineProperty(doc.data(), 'id', {
      value: doc.id
	})
  }
})
```

```js
this.$bind('item', { createSnapshot })
bindFirestoreRef('item', { createSnapshot })
```

It will also be nice to provide a way to override globally for vuexfire

**Comment by posva** [comment]
Closed in #302 
This is now possible thanks to: https://vuefire.vuejs.org/api/vuefire.html#options-serialize

**Comment by mfissehaye** [comment]
How can I use this option in [@nuxtjs/firebase](https://firebase.nuxtjs.org/)

**Comment by posva** [comment]
that module is a different package, it doesn't seem to use vuefire at all

**Comment by mfissehaye** [comment]
It says it plays well with vuexfire in their [docs](https://firebase.nuxtjs.org/tutorials/vuexfire/). I was hoping if there was a way to pass some configuration options to vuexfire. And how do you import firestorePlugin in vuexfire as compared to vuefire.

**Comment by posva** [comment]
But you need to ask there on how to pass options to Vuefire

**Comment by mfissehaye** [comment]
Yes you are right. Thank you. However does this configuration work in vuexfire too because I couldn't `import firestorePlugin` form vuexfire. Isn't vuexfire the same thing as vuefire?

**Comment by mfissehaye** [comment]
I was able to pass the serialize option as described [here](https://vuefire.vuejs.org/api/vuefire.html#firestoreplugin) to my vuexfire binding.

```
await bindFirestoreRef('products', products, {
      wait: true,
      serialize: snapshot => {
        // eslint-disable-next-line no-console
        console.log('serializing products')
        return Object.defineProperty(snapshot.data(), 'id', {
          value: snapshot.id
        })
      }
    })
```

or globally by defining a nuxt plugin with the following content:

```
import { firestoreOptions } from 'vuexfire'

firestoreOptions.serialize = doc => {
  return Object.defineProperty(doc.data(), 'id', { value: doc.id })
}
```

**Comment by mfissehaye** [comment]
When I pass an async function as serialize, it assigns nothing to the bound object.

```
serialize: async snapshot => {
        // add rooms to conversations
        const rooms = []

        // the conversation object has messages and we can fetch rooms using those ids
        const room_ids = _get(snapshot.data(), 'messages', [])
        for (let i = 0; i < room_ids.length; i++) {
          const messages = await this.$fireStore
            .collection(`rooms/${room_ids[i]}/messages`)
            .limit(10)
            .get()

          rooms.push({
            id: room_ids[i],
            messages: messages.docs.map(m => m.data())
          })
        }

        // eslint-disable-next-line no-console
        console.log({
          id: snapshot.id,
          rooms,
          ...snapshot.data()
        })

        return {
          id: snapshot.id,
          rooms,
          ...snapshot.data()
        }
      }
```

Is there a workaround?
