### ISSUE TITLE
Sorting array

### ISSUE THREAD

**Issue by daphen** [vuejs/vuefire#244]
Hey, I'm ripping my hair out, am I missing something?
I'm getting an array back, store it in my state, using a getter to sort it the way I want it and it's displaying fine, but whenever I try to remove or update an item, I get very strange results. Some items duplicate and more often than not, another item than the one I actually click to modify is being changed.

I'm just using a simple Array.sort in the getter and it's working perfectly if I swap out Firebase for a local array. Any thoughts?

Edit: Just to clarify, it's working as intended if I don't do a sort on the array, and it's working as intended if I make a local mock copy of the array AND do a sort on it, but then I miss out on Firebase, obviously and I've built the app around Firebase.

**Comment by posva** [comment]
Array.sort modifies the array, create a copy first with `slice`

**Comment by daphen** [comment]
Haha, that was simple enough.. Thanks.
