### ISSUE TITLE
[Question] Promise is returned after vuefire mutates data

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vuefire#247]
This is more of a question related to vuefire, rather than a problem in vuefire.

I'm trying to add an item to a collection, and immediately select the new item in the UI. The problem in this case, is that vuefire mutates the array, before the promise from `Firestore.CollectionReferecen.add()` is resolved. This results in a variable delay between the new item appearing in the interface and it being selected.

The question is, how/why does vuefire have access to the new item before the promise from firestore is resolved?

Code sample:
```javascript
db.collection('items')
  .add(newItem(this.uid))
  .then(item => {
    this.currentItemId = item.id
  })
``` 

Thanks for the help!

**Comment by posva** [comment]
I imagine this was intentionally made in Firebase so that the promise is resolved after local bindings have been updated
