### ISSUE TITLE
No data being read from firebase

### ISSUE THREAD

**Issue by pacific202** [vuejs/vuefire#251]
I believe I have everything set up properly, but I'm not getting any data read into my component.  There are no errors in the console, just a warning from the firebase library that "it is advisable to only import the individual SDK components you intend to use"

Here is my component:

```
<template lang='pug'>
  div
    h3 Locations
    ul
      li(v-for='location in locations' :key='location.id') {{location.name}}
</template>
<script>

  import { db } from '@/firebase';

  export default {
    name: 'Locations',
    data: function() {
      return {
        locations: [],
        newLocation: {}
      };
    },
    firebase: {
      locations: db.collection('locations')
    }
  }
</script>
```

Here is my firebase.js file (with certain strings in the config object replaced with ...):

```
import * as firebase from "firebase";

const config = {
  apiKey: "...",
  authDomain: "....firebaseapp.com",
  databaseURL: "https://....firebaseio.com",
  projectId: "...",
  storageBucket: "....appspot.com",
  messagingSenderId: "..."
};

// Get a Firestore instance
export const db = firebase
  .initializeApp(config)
  .firestore();
```

I installed vuefire@next using npm, here is the relevant section from package.json:

```
  "dependencies": {
    "firebase": "^5.9.2",
    "vue": "^2.6.6",
    "vue-router": "^3.0.2",
    "vuefire": "^2.0.0-alpha.21",
    "vuetify": "^1.5.5"
  },
```

I have installed the plugin in main.js as follows:

```
import Vue from 'vue';
import App from './App.vue';

import Router from './router';

import './plugins/vuetify';

import { firestorePlugin } from 'vuefire'
Vue.use(firestorePlugin)

Vue.config.productionTip = false;

new Vue({
  "router": Router,
  "render": h => h(App),
}).$mount('#app');
```
There are three locations in the database:

![image](https://user-images.githubusercontent.com/2893279/55394743-e2508200-5537-11e9-9287-6e443cc6a609.png)

The locations array remains empty:

![image](https://user-images.githubusercontent.com/2893279/55394960-7884a800-5538-11e9-879d-0fb942fbcbcd.png)

**Comment by pacific202** [comment]
Moving to StackOverflow as this isn't really an issue (yet)

**Comment by themindstorm** [comment]
@pacific202 Can you share the Stackoverflow link? Have you solved the issue?
