### ISSUE TITLE
No data received

### ISSUE THREAD

**Issue by pacific202** [vuejs/vuefire#253]
I also asked about this on StackOverflow [here](https://stackoverflow.com/questions/55472616/vuefire-no-data-being-read-from-cloud-firestore).

I believe I have everything set up properly (following the [new vuefire docs site][1]), but I'm not getting any data read into my component from Cloud Firestore.

The server compiles and runs, the page renders in the browser, there are no errors in the console, and the "No Locations are available" message is displayed based on the `v-if` statement checking the length of `locations` and finding zero.  Querying individual documents either by id or with a query also returns no results.

How can I debug this to see where the problem lies?  The Firestore Web SDK seems to be behaving normally when I write out to console.log from firestore.js.

Here is my component, with a query added into the newLocation element for testing purposes:

```
<template lang='pug'>
  div
    h3 Locations
    ul(v-if='locations.length > 0')
      li(v-for='location in locations' :key='location.id') {{location.name}}
    p(v-else) No Locations are available.
</template>
<script>

  import { db } from '@/firebase';

  export default {
    name: 'StaffingManagerLocations',
    data: function() {
      return {
        locations: [],
        newLocation: {}
      };
    },
    firebase: {
      locations: db.collection('locations'),
      newLocation: db.collection('locations').where('name', '==', 'Victoria')
    }
  }
</script>
```

Here is my firebase.js file (with certain strings in the config object replaced with `...`):

```
import * as firebase from "firebase";

const config = {
  apiKey: "...",
  authDomain: "....firebaseapp.com",
  databaseURL: "https://....firebaseio.com",
  projectId: "...",
  storageBucket: "....appspot.com",
  messagingSenderId: "..."
};

// Get a Firestore instance
export const db = firebase
  .initializeApp(config)
  .firestore();
```

I installed vuefire@next using npm, here is the relevant section from package.json:

```
  "dependencies": {
    "firebase": "^5.9.2",
    "vue": "^2.6.6",
    "vue-router": "^3.0.2",
    "vuefire": "^2.0.0-alpha.21",
    "vuetify": "^1.5.5"
  },
```

I have installed the plugin in main.js as follows:

```
import Vue from 'vue';
import App from './App.vue';

import Router from './router';

import './plugins/vuetify';

import { firestorePlugin } from 'vuefire'
Vue.use(firestorePlugin)

Vue.config.productionTip = false;

new Vue({
  "router": Router,
  "render": h => h(App),
}).$mount('#app');
```
There are three locations in the database:

![image](https://user-images.githubusercontent.com/2893279/55394743-e2508200-5537-11e9-9287-6e443cc6a609.png)

However, the locations array remains empty:

![image](https://user-images.githubusercontent.com/2893279/55394960-7884a800-5538-11e9-879d-0fb942fbcbcd.png)

I know my Firestore config is correct as I can run this code in a standalone HTML page and see the three documents in the console:

      window.onload = function() {

        // Initialize Firebase
        var config = {
          apiKey: "...",
          authDomain: "....firebaseapp.com",
          databaseURL: "https://....firebaseio.com",
          projectId: "...",
          storageBucket: "....appspot.com",
          messagingSenderId: "..."
        };
        firebase.initializeApp(config);

        var db = firebase.firestore();

        db.collection('locations')
          .get().then(function(results){
            console.log('retrieved locations');
            results.forEach((doc) => {
              console.log(`${doc.id} => ${JSON.stringify(doc.data())}`);
            });       
          });

      }

This appears in the console a second or two after the page loads:

    retrieved locations
    4zMEt9s9PKIJ4WxXm63G => {"name":"Victoria"}
    IK11p3uI16S4vCXg8iia => {"name":"Paddington"}
    r6PGW3mf66KCw98v6Jsi => {"name":"Waterloo"}

My Database Rules are set to the "Test" setting:

```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}

```
  [1]: https://vuefire.netlify.com/vuefire/getting-started.html

**Comment by pacific202** [comment]
Update - calling Cloud Firestore directly in the created event works fine:

```
<template lang='pug'>
  div
    h3 Locations
    ul(v-if='locations.length > 0')
      li(v-for='location in locations' :key='location.id') {{JSON.stringify(location)}}
    p(v-else) No Locations are available.
</template>
<script>

  import { db } from './../../firebase';

  export default {
    name: 'StaffingManagerLocations',
    data: function() {
      return {
        locations: [],
        newLocation: {}
      };
    },
    created: function(){
      db.collection('locations').get().then((QuerySnapshot) => {
        QuerySnapshot.forEach( (QueryDocumentSnapshot) => {
          this.locations.push(QueryDocumentSnapshot.data());
        });
      });
    }
  }
</script>
```

![image](https://user-images.githubusercontent.com/2893279/55421152-83f3c580-5570-11e9-83af-22b0ec5bae1b.png)

**Comment by posva** [comment]
I don't see where the problem could be, if you have a boiled down repro I can take a look but there isn't much I can do with so much information

**Comment by pacific202** [comment]
Here is a push of my existing code, actual config is included (I'll take it down later).

https://github.com/pacific202/vuefire-issue-253

This is the URL to use to test:

http://localhost:8080/staffing-manager/locations

The component is at /src/components/staffing-manager/Locations.vue

**Comment by posva** [comment]
But coud you put something online like codesandbox? But please boil it down to the minimal, one component (app.vue) should be enough to show the problem without vuetify nor the router

**Comment by pacific202** [comment]
It would be great to have some troubleshooting steps added to the documentation :)

I've never used codesandbox, but I'll take a look now.

**Comment by pacific202** [comment]
https://codesandbox.io/s/mmmxonyovp

**Comment by posva** [comment]
okay, I didn't see it the first time, but it's just because you are using `firebase` option instead of `firestore`. Sorry, I didn' see it before 😬 
I'm going to update the docs and push, thanks

**Comment by pacific202** [comment]
For other users, the error was in the end component calling VueFire.  It needed to look like this instead:

```
<template lang='pug'>
  div
    h3 Locations
    ul(v-if='locations.length > 0')
      li(v-for='location in locations' :key='location.id') {{location.name}}
    p(v-else) No Locations are available.
</template>
<script>

  import { db } from '@/firebase';

  export default {
    name: 'StaffingManagerLocations',
    data: function() {
      return {
        locations: [],
        newLocation: {}
      };
    },
    firestore: {  // <- this needed to be changed from 'firebase' to 'firestore'
      locations: db.collection('locations'),
      newLocation: db.collection('locations').where('name', '==', 'Victoria')
    }
  }
</script>
```

**Comment by sath26** [comment]
> Update - calling Cloud Firestore directly in the created event works fine:
> 
> ```
> <template lang='pug'>
>   div
>     h3 Locations
>     ul(v-if='locations.length > 0')
>       li(v-for='location in locations' :key='location.id') {{JSON.stringify(location)}}
>     p(v-else) No Locations are available.
> </template>
> <script>
> 
>   import { db } from './../../firebase';
> 
>   export default {
>     name: 'StaffingManagerLocations',
>     data: function() {
>       return {
>         locations: [],
>         newLocation: {}
>       };
>     },
>     created: function(){
>       db.collection('locations').get().then((QuerySnapshot) => {
>         QuerySnapshot.forEach( (QueryDocumentSnapshot) => {
>           this.locations.push(QueryDocumentSnapshot.data());
>         });
>       });
>     }
>   }
> </script>
> ```
> 
> ![image](https://user-images.githubusercontent.com/2893279/55421152-83f3c580-5570-11e9-83af-22b0ec5bae1b.png)

it worked for me. i came across same problem and it hasnt been fixed yet
