### ISSUE TITLE
Inject firebase connections globally?

### ISSUE THREAD

**Issue by pacific202** [vuejs/vuefire#255]
Is there some way to inject the Firestore connections globally so instead of this:

```
  import { db } from '@/firebase';

  export default {
    name: 'StaffingManager_LocationController',
    data: function() {
      return {
        locations: []
      };
    },
    firestore: {
      locations: db.collection('locations')
    }
  }
```

we can write this instead?

```
  export default {
    name: 'StaffingManager_LocationController',
    data: function() {
      return {
        locations: []
      };
    },
    firestore: {
      locations: this.$db.collection('locations')
    }
  }
```

If we're adding the firestore plugin globally, wouldn't it make sense to also store the db connection globally too?  If we want to manually add the db connection to each component as it might not be needed everywhere, then wouldn't we want the same behavior from the plugin as well?

I'd like to propose that if this is possible the docs should show both plugin and db reference as globals.

**Comment by posva** [comment]
you have to inject it yourself in Vue with something like Vue.prototype.$db = db
This is intentionally left out

**Comment by thefoxie** [comment]
> you have to inject it yourself in Vue with something like Vue.prototype.$db = db
> This is intentionally left out

No this won't work because of the scope. `this` is not Vue instance and you cannot access it.

**Comment by thefoxie** [comment]
Possible solution for this is to use programmatic binding.
```js
export default {
    name: "Home",
    data() {
        return {
            users: [],
        };
    },
    watch: {
        watcher: {
            // call it upon creation too
            immediate: true,
            handler() {
                this.$bind("users", this.$db.collection("users"));
            },
        },
    },
};
```

**Comment by posva** [comment]
`this` has the right context when using the function version of `firestore`. Locking as this was solved and is quite old issue
