### ISSUE TITLE
Using $bind causes undefined error

### ISSUE THREAD

**Issue by ydennisy** [vuejs/vuefire#257]
I have been searching for hours how to best deal with this, I am trying to bind a firebase doc to a data property, the app actually works fine, but there are render errors in the console.

My template:

`<p>{{audience.status}}</p>`

My js:

```
import { db } from '@/firebase';
export default {
  data() {
    return {
      audience: [],
    }  
  },
created() {
    this.$bind('audience', db.collection('audiences').doc(this.id))
      .then(audience => {
        this.audience = audience;
      });
  },
}
```
My errors:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'status' of undefined"
found in
---> <Dash> at src/views/Dash.vue
       <App> at src/App.vue
         <Root>
```

I have also tried doing this with the the `firestore` object but it has no access to `this` as far as I can tell as that shows a `undefined`.

**Comment by posva** [comment]
You don't need the then. If it's undefined it may be that the doc doesn't exists. Also don't initialize the value to an array of it's not a collection. You can check https://vuefire.netlify.com

**Comment by ydennisy** [comment]
Sorry, why is this closed?

The document is defined as mentioned - this throws the error but the data reaches the UI.

It looks like an issue with the lifecycle, I have read the docs, and have tried to initialise with both an `[]` and `null` neither changes the outcome. 

I have also removed `then()` - yet the error remains, new code:

```
import { db } from '@/firebase';
export default {
data() {
return {
  audience: null,
}
}
created() {
  this.$bind('audience', db.collection('audiences').doc(this.id))
  },

}
```

**Comment by ydennisy** [comment]
@posva I have figured out the issue, but would like your advice on best practice.

The data structure of `audience` was nested and in my template I was accessing `{{ audience.stats.count }}` which was causing the error as `stats` was never defined.

**Comment by posva** [comment]
use a v-if to prevent access, the same as in a template with a fetch
