### ISSUE TITLE
Incompatible with Firebase 3.x.x!

### ISSUE THREAD

**Issue by wpaix** [vuejs/vuefire#26]
It seems vuefire is no longer compatible with firebase since google took over firebase and moved it to 3.x.x?

What's the timeline on getting this fixed?

**Comment by posva** [comment]
vuefire supports firebase since v1.1.0.
Are you up to date? 😉

**Comment by wpaix** [comment]
Cool :)

I'm a it confused, though. I keep getting this error:

TypeError: e.key is not a function. (In 'e.key()', 'e.key' is "first-fish-slug")
FIREBASE WARNING: Exception was thrown by user callback.

and looking here, jwngr commented on jun 20 that a 3.1.0 releave supports firebase 3.x.x.?

https://github.com/vuejs/vuefire/issues/7

**Comment by posva** [comment]
@wpaix I think he was referring the Firebase SDK version.
If that's the case, can you provide a repro ?

**Comment by jwngr** [comment]
As the error suggests, `key` is not a method in the `3.x.x` SDKs; instead, it is a read-only property. So, you just need to replace all calls to `key()` in your code with `key`. This is noted in our JavaScript migration guide [here](https://firebase.google.com/support/guides/firebase-web#no-argument_getters_are_now_read-only_properties_numbered).
