### ISSUE TITLE
vuexfire with Chart

### ISSUE THREAD

**Issue by ozankonur** [vuejs/vuefire#262]
I am trying to sync my charts' array data with my firebase values. Chart getting arrays like [[a,b,c,d,e,f]] and I would like to bind these each values to my firebase objects. I dont think it is possible with vuefire so I am trying with vuexfire. Here is what I tried so far;

```
    data()
    {
    return {appScreenVisitorsChart: {data: {labels: ["A", "B", "C", "D", "E", "F",], series: [[]]}},}
    },
    computed: {
      getBasic: function () {
        return this.$store.getters.getMyObject;
      }
    },
    mounted()
     {
       let x = this.getBasic;
        this.appScreenVisitorsChart.data.series[0] = [2, 2, 2, x, 3, 3];
     }
```

As yu can see I am trying to sync only one value with my firebase object. And here is my store;

```
   export const store = new Vuex.Store({
    state: {
        bakim: null,
    },
    mutations: vuexfireMutations,
    actions: {
        bindTodos: firebaseAction(({bindFirebaseRef}) => {
            return bindFirebaseRef('bakim', db.database().ref("packages").child("0"));
        })
    },
   getters: {
        getMyObject: state => {
            return state.bakim.tik;
        }
    }
});
```

As you can see from store getter, I have an object which has value as "tik" and this tik is a number in firebase like this:

```
"packages" : [ {
    "services" : [ {
      ....
    } ],
    **"tik" : 20**
  },
```

Can you give advise how can I sync one of my chart value with "tik" in my firebase db ? Thanks

**Comment by posva** [comment]
Hey, I tried understanding what you want but I didn't realy get it, sorry.
As I don't have the bandwidth to deal with this, could you ask it in the forum or stackoverflow? maybe someone could help you there 🙂  Your problem may not even be related to vuefire.

BTW vuefire and vuexfire have almost the same set of features! SSR is only doable with vuexfire at the moment

**Comment by ozankonur** [comment]
@posva I want to bind firebase data with vuejs chart.. This is the summary
