### ISSUE TITLE
Uncaught (in promise) Error {code: "cancelled", name: "FirebaseError", toString: ƒ}

### ISSUE THREAD

**Issue by KEVGRU** [vuejs/vuefire#263]
``` "firebase": "^5.9.4" "vuexfire": "^3.0.0-alpha.16" "nuxt": "^2.6.2" ```

When trying to bind with firestore i get following error: ```Uncaught (in promise) Error {code: "cancelled", name: "FirebaseError", toString: ƒ}```

In vue debug tools i can see the ``vuexfire/ARRAY_ADD`` event and also the DELETE event. when there is an update on the DB. So DB is in sync but somehow i cant bind the array to the variable.

```javascript
export const state= () => {
  return {
    memberList: []
  };
};

export const mutations = {
  setClubs(state, payload) {
    state.clubs = payload;
  },
  setSelectedClub(state, payload) {
    state.selectedClub = payload;
  },
  addClub(state, payload) {
    state.clubs.push(payload);
  },
  ...vuexfireMutations
};

setMemberListRef: firestoreAction(({ bindFirestoreRef }, ref) => {
    console.log(ref);
    return bindFirestoreRef(
      "memberList",
      DB.collection("members")
        .doc(ref)
        .collection("members")
    );
  })


```

smth what im missing here?

**Comment by posva** [comment]
Vuexfire wise your code looks good. The error you have may be related to a rights problem. You should search the error in Firebase docs. Adding a catch to the promise returned by bind firestore ref could get you more info as well

**Comment by KEVGRU** [comment]
my security rules are ``if request.auth.uid != null;`` . im authenticated, since i can use other functions which also require auth. I can also see that inside the ``vuexfire/ARRAY_ADD`` the data from DB is written there.

i tried to throw a catch error but unfortunately ``next`` is triggered

```javascript
setMemberListRef: firestoreAction(async ({ bindFirestoreRef }, ref) => {
    console.log(ref);
    await bindFirestoreRef(
      "memberList",
      DB.collection("clubs")
        .doc(ref)
        .collection("members")
    )
      .then(() => {
        console.log("next");
      })
      .catch(err => {
        console.log(err);
      });
  })
```
since 2 days i try to fix this -.-

**Comment by posva** [comment]
okay, I honestly don't know what could be causing this, so if you can boil it down to the strict minimal I can take a look

the error is here https://firebase.google.com/docs/reference/android/com/google/firebase/functions/FirebaseFunctionsException.Code but it doesn't give more information apart from _interrupted by the caller_ which I don't know how could happen in vuefire/vuexfire

there is also this issue open: https://github.com/firebase/firebase-js-sdk/issues/1678

**Comment by ThomasKuhlmann** [comment]
@KEVGRU and @posva 

I had the same issue until a few days ago, here's what solved it for me:
-----
I found the solution. It had nothing to do with firebase in my case - The latest version of the vue devtools (something like 5.0.9 I think) seems to have caused a memory leak which impacted not just firebase (but the firebase errors where the first to pop up). Switching back to an older beta version of vue-devtools for Chrome solved the problem for me. 

Here's the older version in the chrome webstore:
[https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg?hl=en](url)

**Comment by posva** [comment]
ok, thanks for sharing

**Comment by KEVGRU** [comment]
@ThomasKuhlmann thanks for your clearification

**Comment by posva** [comment]
Closing as this doesn't seem to be related with Vuefire and I haven't been able to verify through a repro. If someone still has the issue, they can open a new issue with a boiled down repro and I will take a look!
