### ISSUE TITLE
Typo in the 'Writing Data' doc page for Vuexfire

### ISSUE THREAD

**Issue by ElBatanony** [vuejs/vuefire#265]
I believe that there is a typo in the [Writing to the database](https://vuefire.vuejs.org/vuexfire/writing-data.html#updates-to-collection-and-documents) documentation page for Vuexfire. It should give an example for using the update function, but instead it uses the set function.
```javascript
firestoreAction(({ state }) => {
  db.collection('users')
    .doc(state.user.id)
    .set({ lastName: newLastName }) // should be changed to update
    .then(() => {
      console.log('user updated!')
    })
})
```

**Comment by posva** [comment]
Yes you are right! You can send a PR if you want. Otherwise I will fix it once I am in the computer

**Comment by ElBatanony** [comment]
Created a pull request!
