### ISSUE TITLE
Model doesn't update firebase data

### ISSUE THREAD

**Issue by SteveEdson** [vuejs/vuefire#27]
My Firebase reference is pulling in changes, but when I update a property of the object using a v-model reference, it doesn't trigger the update in Firebase.

I'm using Vue 2.0.0-rc3 and vuefire 1.2.

Thanks

```
    var firebaseApp = firebase.initializeApp(config);

    var db = firebaseApp.database();

    Vue.use(VueFire);

    var app = new Vue({
      el: '#app',
      firebase: {
        test: {
          source: db.ref('test'),
          asObject: true
        }
      }
});

```

```html
    <input type="text" v-model="test.key">
```

**Comment by posva** [comment]
That's expected. You should add data using the firebase ref

**Comment by SteveEdson** [comment]
So I would still need a watcher with `db.ref('test').set(val)`?

Do I have the wrong idea for vuefire then? I thought it handled two way binding?

**Comment by posva** [comment]
Vuefire is going to update the data in your client whenever firebase data is updated from any client, but you still need to use the firebase Refs to add/update/delete data on your database:

As in the readme:
``` js
vm.$firebaseRefs.anArray.push({
  text: 'hello'
})
```
