### ISSUE TITLE
Is there a way to get a count of a collection?

### ISSUE THREAD

**Issue by codegrue** [vuejs/vuefire#271]
Something like:

`this.$firestoreRefs.myCollection.size`

or 

`this.$firestoreRefs.myCollection.length`

**Comment by posva** [comment]
Hey, I don't think there is a way for vuefire to have that information without triggering too many reads. I found this https://stackoverflow.com/questions/46554091/firebase-firestore-collection-count

**Comment by Soviut** [comment]
For posterity, Firebase now supports counting documents with an aggregate query.

https://firebase.google.com/docs/firestore/query-data/aggregation-queries
