### ISSUE TITLE
firestorePlugin Uncaught TypeError: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by clacdesdoigts** [vuejs/vuefire#273]
Hello,
The plugin is loading fine if we start it using 'vue ui' or else, but whenever we upload the application to the server compiled/packed using 'npm run build' it shows this error:

```
vue.runtime.esm.js:5083 Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.Er.t.use (vue.runtime.esm.js:5083)
    at Module.56d7 (main.js:9)
    at s (bootstrap:88)
    at Object.0 (bootstrap:262)
    at s (bootstrap:88)
    at t (bootstrap:45)
    at bootstrap:262
    at bootstrap:262
``` 

Where main.js line 9 is precisely:

```
...

Vue.use(firestorePlugin);
...
```

Any thoughts on what could be the issue ?

Thans!

**Comment by posva** [comment]
No idea where it may come from but it should be related to the webpack config and maybe some differences between the production built and the dev one. do you have any specific config for vue cli?
Maybe we are pointing at the wrong dist file in our package.json file

**Comment by clacdesdoigts** [comment]
Hi Eduardo,
Yes, it should be something related to webpack because the error shows that he can't find the correct library, although we see it in the vendors javascript, is there any configuration for webpack that we should be aware of? We just run 'npm run build' and this what we see:
```
 warning  in ./src/main.js

"export 'firestorePlugin' was not found in 'vuefire'
```
 The vue app has not been specifically configured, besides vue 3.0 cli standard config with javascript (no typescript), stylus and jest.

**Comment by posva** [comment]
Just tested with a vue 3 cli fresh project and it works both in dev and production mode. Make sure you are using the `next` tag from npm `npm i vuefire@next`. It will be released very soon as stable, so this won't be necessary in the future but it is now

**Comment by clacdesdoigts** [comment]
Thanks! For those with the same problem, finally solved the issue by rearranging the order when importing the library, when we moved Vuefire import statement just after Vue's and before Vuetify's, it started to work again.
