### ISSUE TITLE
this._firestoreUnbinds is undefined in Vue 2.6.0

### ISSUE THREAD

**Issue by maletor** [vuejs/vuefire#274]
When I create an immediate watcher with this.$bind I find that this._firestoreUnbinds is null.

I see that created() is called from the mixin first but for some reason `if (this._firestoreUnbinds[key]) {` throws an error because unbinds is undefined.

**Comment by maletor** [comment]
By the way, binding declaratively works as intended perhaps because that code path is different and doesn't depend on this._firestoreUnbinds being defined in the same way.

**Comment by posva** [comment]
Hi, I don't understand what you are trying to do, a code sample would help, a repro would be even better

**Comment by maletor** [comment]
So one thing I can do is move `this.$bind` code to `mounted` and remove the immediate from the watcher and rebind there when it changes. 

The reproduction is on an immediate watcher only.
