### ISSUE TITLE
Where to use it?

### ISSUE THREAD

**Issue by sandro-git** [vuejs/vuefire#276]
i'm trying to follow allong the docs but i've some error and i don't know where to put the files you talking about on the docs. i've created a project with vue cli 3. add vuex and vue router.

**Comment by posva** [comment]
the documentation talks about this at https://vuefire.vuejs.org/vuefire/getting-started.html#installation you put the files wherever it makes more sense for your project, importing `firebase` too

If you have an error but you don't share it, it's pretty much impossible for anybody to help you...

**Comment by sandro-git** [comment]
sorry my bad here is the link to the project. https://github.com/sandro-git/api-calls-vue

**Comment by posva** [comment]
hey sorry, but I cannot look at the project you are building. I could maybe have the solution if you give me the error stack trace (that's what I wanted you to share). It could be a vuefire bug or a missing point in docs
but please, if you want to get support, use the forum or discord chat

**Comment by sandro-git** [comment]
ok thanks i figure it out by myself but maybe can i suggest adding some changes to the docs ?

**Comment by posva** [comment]
of course, you can even write a pull request if the changes are small or you feel like it!

**Comment by sandro-git** [comment]
cool, it would be my fisrt pull request. don't judge my changes to hard 😄

**Comment by posva** [comment]
no judging 🙂 
Closing this as it doesn't contain any actionable information
