### ISSUE TITLE
Firestore get once

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vuefire#278]
This is a feature request for a convenient way of assigning the result of `query.get()` to a property in the data model. 

Similar to the `firestore` option or the the `vm.$bind` method, but without subscribing for updates. 

If I understand correctly, currently one has write the following achieve the described outcome?

```javascript
{
	async created () {
		const querySnapshot = db.collection('mydocs').get()
		this.mydocs = querySnapshot.docs.map(documentSnapshot =>
			Object.defineProperty(documentSnapshot.data(), 'id', {
				value: documentSnapshot.id,
				enumerable: false,
			})
		)

	}
}
```

**Comment by posva** [comment]
Right now this should be possible by awaiting a bind and then unbinding it. For Firestore, this benefits from fetching references. Maybe this could be added as a standalone function that is re exported by both vuefire and vuexfire

**Comment by patrickcorrigan** [comment]
Does awaiting bindFirestoreRef wait for references to be fetched?

**Comment by patrickcorrigan** [comment]
> Right now this should be possible by awaiting a bind and then unbinding it. For Firestore, this benefits from fetching references. Maybe this could be added as a standalone function that is re exported by both vuefire and vuexfire

I've tried this but I seem to have issues with wait when doing this repeatedly. Probably due to this behaviour https://github.com/vuejs/vuefire/issues/776. I've tried unbinding.

**Comment by dimavolo** [comment]
Any updates on this?

**Comment by posva** [comment]
there is an option `once` now:

```ts
useDocument(.., { once: true })
```

This option is forced to true during SSR
