### ISSUE TITLE
TODO make sure this is the right choice.

### ISSUE THREAD

**Issue by maletor** [vuejs/vuefire#282]
I think this is the wrong choice. Don't bind a reference because it's confusing and violates the principal of least astonishment.

**Comment by posva** [comment]
I forgot about that TODO. I removed it. I like that behaviour, it's very convenient and can be modified by passing `maxRefDepth` to 0

Please, next time when pointing a comment on a file, point to the file, that way anybody can understand what you are pointing to, it's more inclusive and I would appreciate it 🙂

**Comment by maletor** [comment]
No prob @posva.

Somehow I missed `maxRefDepth` when reading the src.

Is it documented?

**Comment by posva** [comment]
Yes

Eduardo San Martin Morote
