### ISSUE TITLE
Deleting a element in an array of references removes the last entry instead

### ISSUE THREAD

**Issue by hs-sundeep** [vuejs/vuefire#283]
If the document that is being bound to state variable has a field that is an array of other document references and if those references are not being bound, then that field is returned as an array of strings containing paths to those documents. If any one of the reference in that array is removed from firebase console then vuexfire removes the last value in that array irrespective of the actual reference removed from database.

**Comment by posva** [comment]
I need a boiled down repro to check this. That way it will be clearer

**Comment by hs-sundeep** [comment]
@posva I have made a [sample app](https://codesandbox.io/s/vuexfire-bug-gfg1d) to illustrate the issue. Try deleting any of the element and see what happens.

**Comment by posva** [comment]
Thanks! It seems that because it is a reference, it isn't handled correctly
