### ISSUE TITLE
Does vuefire work with Webpack Hot Module Replacement?

### ISSUE THREAD

**Issue by beebase** [vuejs/vuefire#29]
I'm trying to get vuefire to work with Quasar framework but I think Webpack Hot Module Replacement is wiping out firebase data fetched with vuefire.
A production build will probably work ok , but it's during development that firebase data seems to disappear after H.M.Replacement.

More info in this post 
https://github.com/rstoenescu/quasar-framework/issues/87

**Comment by posva** [comment]
I remember it worked well with a webpack project generated with vue-cli so, I don't know how I can help you...
Unfortunately, it's not something we can fix on vuefire end anyway.

**Comment by laurentpayot** [comment]
@posva was the webpack project working well with Vue 1.x or 2.x ? I'm experiencing the same issue as @beebase with Quasar (currently on Vue 1.x).

**Comment by posva** [comment]
@laurentpayot I just tested again on a fresh project using the official webpack template with Vue 2. I added some refs to the to the main App.vue file. Modifying the html or the CSS works just fine. The same goes for a child component. Modifying the js on app will reload the page (root component) but works fine without wiping data on the child component

**Comment by laurentpayot** [comment]
Thanks @posva, I will wait for Quasar 0.8 that will integrate Vue 2.x to see if the bug is still there.

**Comment by laurentpayot** [comment]
This issue was fixed in Quasar v0.8 (powered by Vue 2), released today, and amazing.

**Comment by posva** [comment]
@laurentpayot Thanks for letting me know! I'll close the other issue
