### ISSUE TITLE
Can't access nested keys.

### ISSUE THREAD

**Issue by sarguvlad** [vuejs/vuefire#294]
Hello guys and thank for this amazing tool! Still learning it, so here's my question.

I have the following structure in RTDB

![image](https://user-images.githubusercontent.com/1769791/60163344-11f3eb00-9804-11e9-9d68-603f6f58090f.png)

the following template.

```html
<div v-for="flow in flows">
  {{ flow['.key'] }} <!-- Prints the unique key -->
  <div v-for="category in flow.categories">
    {{ category.name }} <!-- Prints the category name -->
    {{ category['.key'] }} <!-- Prints nothing -->
  </div>
</div>
```
and the following script
```javascript
export default {
  data() {
    return {
      flows: []
    }
  },
  firebase: {
    flows: db.ref('flows')
  }
}
```

Why the nested key is missing? Please excuse my incompetence!

Thanks!

**Comment by posva** [comment]
I'm not sure as I cannot test right now but isn't categories an object? If that's the case, the key is also the document id:

```vue
<div v-for="flow in flows">
  {{ flow['.key'] }} <!-- Prints the unique key -->
  <div v-for="(category, key) in flow.categories">
    {{ category.name }} <!-- Prints the category name -->
    {{ key }} <!-- Prints nothing -->
  </div>
</div>
```

**Comment by sarguvlad** [comment]
@posva, thank you so much! You were right, it worked.

I thought when using the `.push()` method automatically an array is created.

```javascript
flowsRef.child(flow['.key']+'/categories').push({
  name: name
});
```

Seems that I was wrong. How do I create an array then?

I'm asking because before I've created the `flows` array using the same method. Looks like there's a difference I don't see.

```javascript
flowsRef.push({
  name: this.name
});
```

Thank you!

**Comment by posva** [comment]
Only top level can be arrays with the RTDB. There are no arrays in reality, only in Firestore 

Eduardo San Martin Morote

**Comment by sarguvlad** [comment]
Things start to make sense now. I'm very thankful @posva!
