### ISSUE TITLE
Watch for empty array property.

### ISSUE THREAD

**Issue by sarguvlad** [vuejs/vuefire#296]
Hello guys, looking around for a solution for my problem!

I try to make Vue.Draggable work with VueFire. I have a few lists with cards that can be dragged between them, sorted, cloned and so on. While the lists are populated with cards Vue.Draggable works perfectly, it watches for changes, triggers events like magic.

This is the working JSON:
```javascript
categories: [{
  name: "todo",
  cards: ["second","first","second"]
},{
  name: "doing"
  cards: ["first","fourth","second"]
},{
  name: "done",
  cards: ["second", "fourth","first","third"]
}]
```
The problem comes when one o the lists is empty. We all know that Firebase doesn't store empty properties that's why Vue.Draggable can't watch for a property that doesn't exist. For example like this:
```javascript
categories: [{
  name: "todo",
  cards: ["second","first","second"]
},{
  name: "doing"
  // missing cards property because it's empty
},{
  name: "done",
  cards: ["second", "fourth","first","third"]
}]
```
The `cards` property should be filled with values by dragging items to the list, but because `cards` doesn't exist Vue.Draggable can't watch for changes in that list and can't trigger events.

Is there a way to create some kind of placeholder or middleware to simulate that empty array? Or what are other possible solutions in this case?

Here's a small [JSFiddle](https://jsfiddle.net/L8kqysof/34/).

Thank you!

**Comment by trickstival** [comment]
If I understand it right you can probably solve it with a computed property that maps your categories array and adds the empty array when "cards" isn't filled.
