### ISSUE TITLE
can't access to https://vuefire.vuejs.org/ in china

### ISSUE THREAD

**Issue by SilverLeaves** [vuejs/vuefire#297]
![图片](https://user-images.githubusercontent.com/31165554/60638896-cae4a600-9e52-11e9-896f-3982898372e8.png)

**Comment by posva** [comment]
Apparently some services were down but it should be good now. The site is hosted on Netlify. I cannot check if it works or not and I don't know if I can do something to change that without changing the host (Netlify), which I won't change but AFAIK is available in China.

What is funny to me is that I thought Firebase wasn't available in China 😆
