### ISSUE TITLE
Managing component dependencies

### ISSUE THREAD

**Issue by niallobrien** [vuejs/vuefire#30]
Hi, I'm just wondering what's the recommend method for importing Firebase, calling `.initializeApp` and `firebaseApp.database()` etc.? Do you generally use these at the top root App component level and pass them down as props to all nested child components or is it just easier to call all of these within each component?
If so, could you please provide an example which could be added to the documentation?

Thanks in advance.

**Comment by microcipcip** [comment]
I found a [good example](https://github.com/jacobwise/vuex-firebase), although there's the extra complexity of vuex. I think the docs for vuefire are very limited, I have no idea how to get started without at least some basic examples.

**Comment by niallobrien** [comment]
@microcipcip I see that that project is using an older version of the Firebase sdk, but from looking at the code, it seems that what I'm doing is right. Ie. initialise Firebase in each component where it's needed, then pass the props down to any child components that need the data - so the parent component is the one doing the heavy-lifting (with Firebase) so to speak.

**Comment by microcipcip** [comment]
@niallobrien glad it helped, but I wouldn't close this issue, I think the docs needs these basic examples for beginners.

**Comment by niallobrien** [comment]
@microcipcip Agreed - this is also an issue I raised for VuexFire and I'm attempting to put together a demo project for that. What I have done so far works, but I still have a lot of questions for @posva. See https://github.com/posva/vuexfire/pull/5

I'll re-open this issue, but honestly, it's pretty straight-forward to do a demo app for VueFire. I recommend you use Vue-CLI with the Webpack template (for Vue 2.0, do `vue init webpack#2.0 my-project` as the 2.0 branch hasn't been merged yet) and let us know how you get on. :)

**Comment by microcipcip** [comment]
Thanks, I will, a lot of new concepts! I'll gladly wait for more docs/examples though :)

**Comment by niallobrien** [comment]
Here's what I did - install Vue-CLI. Use the Webpack 2.0 template: `vue init webpack#2.0 my-project`. That will give you a full Vue 2.0 setup with Webpack etc.
@posva just recently merged my PR which includes a more complete example to the Readme. See the examples towards the bottom of [this section](https://github.com/vuejs/vuefire#usage). That's exactly what I did to integrate the two. Hope that helps @microcipcip

**Comment by microcipcip** [comment]
Thanks a lot, how do I use `anArray` and `anObject` inside a component? Am I supposed to specifically include them inside the component? Do I have to import firebase on every component I guess?

```
var projectsRef = new Firebase('https://myproject.firebaseio.com')
import Firebase from 'firebase'
```

**Comment by posva** [comment]
It's indeed better to handle one single sync for a given dataset. With vuex you always have one single entry point: your store. Passing data through props with vuefire is good.
If you have vuex + firebase, I recommend you using [vuexfire](https://github.com/posva/vuexfire)

**Comment by niallobrien** [comment]
@microcipcip That's the old way of doing it with the old Firebase sdk afaik.
I do it like so:
```js
  import Firebase from 'firebase'

  const firebaseApp = Firebase.initializeApp({ databaseURL: '<YOUR-FIREBASE_URL>' })
  const db = firebaseApp.database()
  const messagesRef = db.ref('messages')

  export default {
    data () {
      return {
        newMessage: ''
      }
    },
    firebase: {
      messages: messagesRef
    },
    etc.
    etc.
```

I hope that makes sense? Also, be sure to check your Firebase rules.

**Comment by microcipcip** [comment]
Yeah it does make sense, I was afraid of doing so in each component thinking it would be bad for the performance because I am inizializing the firebaseApp in each component. Dunno if Webpack takes care of that. If I use vuexfire I inizialize it only once and then pass the firebase objects via props?

**Comment by niallobrien** [comment]
@microcipcip Yeah, I was worried about the same, but then think about it - you're essentially initialising a Firebase instance per component with the data only that component cares about. Trying to pass Firebase instances around could get messy really fast. The Webpack production build seems to be quite efficient.

**Comment by microcipcip** [comment]
So for example if I have a `SaveList.vue`, `EditList.vue` and `List.vue` components and I need to get `firebaseApp.database().ref('myList')` I'll just have to require this in all components right?
```
  import Firebase from 'firebase'

  const firebaseApp = Firebase.initializeApp({ databaseURL: '<YOUR-FIREBASE_URL>' })
  const db = firebaseApp.database()
  const messagesRef = db.ref('myList')
```

**Comment by niallobrien** [comment]
@microcipcip Yup, or if you prefer, you could do it in a parent component and pass that instance down to the child components. Entirely up to yourself. I'm honestly not sure which one is more efficient though, hence the reason why I opened this issue. ;)

**Comment by microcipcip** [comment]
Ok, thanks a lot, I'll try to follow your suggested approach. Thanks a lot for your help!

**Comment by niallobrien** [comment]
@microcipcip No worries - please keep us posted on your progress - hit me up on Twitter: [@niall_obrien](https://twitter.com/niall_obrien)

**Comment by microcipcip** [comment]
I will :)

**Comment by quicksilversangkyu** [comment]
I tried as microcipcip mentioned; call Firebase.initializeApp in every component that use firebase, but it looks like not working.

**Comment by ronyef** [comment]
I found the solution here: https://alligator.io/vuejs/vuefire-firebase/
