### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by Hazeman27** [vuejs/vuefire#301]
![vuexfire_typo](https://user-images.githubusercontent.com/13175359/61239767-f2cfe580-a73f-11e9-82fc-af4f3e5d3a8a.png)

**Comment by posva** [comment]
Thank you. You can also send a PR next time, it's super easy with the edit button at the bottom!

**Comment by Hazeman27** [comment]
Hi, I know about that button, but when I clicked it gave me this:

![image](https://user-images.githubusercontent.com/13175359/61290133-6b2fb880-a7cb-11e9-803a-6ae3ff958378.png)

**Comment by posva** [comment]
Oh, you should have told me too! I fixed the links, they all should work now!

**Comment by Hazeman27** [comment]
Great, everything works now 😃
