### ISSUE TITLE
Add document ref as readonly to document

### ISSUE THREAD

**Issue by magpiedigital** [vuejs/vuefire#324]
You can use `this.$firestoreRefs` to get the refs of documents.

I think it would be cleaner to use ref as a non-enumerable, read-only property like the ID. I would suggest that using the dollar syntax would avoid conflicts.

So then you can access the ref by doc.$ref

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vuefire/issues/180

**Comment by posva** [comment]
FYI this can be achieved already in userland, as commented in the issue
