### ISSUE TITLE
References in arrays and non-existent are lost when updating any field in a document

### ISSUE THREAD

**Issue by romirez** [vuejs/vuefire#325]
Thanks for making Vuefire, it's great!

I have a bound object that has an array of references as one of the fields:
![image](https://user-images.githubusercontent.com/6787260/62334631-4bf88280-b47d-11e9-8c23-6aae664a292e.png)

For existing references in the array everything works well, however thing break when I add a new entry into that array with  
```
firestore.collection("logs").doc(this.log.id)
    .update({
        photos: 
            firebase.firestore.FieldValue.arrayUnion(doc.ref)
    });
});
```

I end up with the right data inside firestore, but in Vue, the new entry in the array is loaded as a string instead of an Object:
![image](https://user-images.githubusercontent.com/6787260/62334743-b7425480-b47d-11e9-946b-36c4d04c3160.png)

If I re-bind the object, everything is fine.

**Comment by posva** [comment]
I tested a bit more and it turns out to happen no matter what field is updated

**Comment by mahapo** [comment]
I have the same issue with vuexfire. When i add a new reference to array of references (for example with cloud functions), only the last added reference will be a object.

**Comment by raphaelmollon** [comment]
I have the exact same problem to deal with.
Does anybody have a workaround or the correct way to manipulate the data?

**Comment by miyaoka** [comment]
https://github.com/vuejs/vuefire/blob/a1c45de6dd7c15577c01edadb70968da9f4e835f/packages/%40posva/vuefire-core/src/firestore/index.ts#L147-L152

I rewrite this code to
```
if (sub) sub.unsub()
```

It's works for me.

**Comment by aspecker** [comment]
Any official word on this? I am encountering the same issue and am interested in a fix or the proper way to manipulate the data without calling .update on the document directly.

**Comment by nwwondrous** [comment]
I am also encountering this issue. Any news on this?

**Comment by aspecker** [comment]
We were actually able to solve this issue by rebinding to the collection after calling update.

`db.collection('users').doc(this.user.username).update({
            viewedCompanyProfileIds: currentViewedCompanyProfileIds
          })
          .then(() => {
            // re-bind to get around vuefire bug where schedule reference data breaks after db update
            // see: https://github.com/vuejs/vuefire/issues/325
            this.bindUserDoc()
          })`

and

`bindUserDoc: firestoreAction(
      ({bindFirestoreRef, state, commit}) => {
        return bindFirestoreRef('userDoc', db.collection('users').doc(state.user.username)).then(
          () => {
          commit('setViewedCompanyProfileIds', state.userDoc.viewedCompanyProfileIds || [])
        })
      }
    ),`

**Comment by aspecker** [comment]
We were actually able to solve this issue by rebinding to the collection after calling update.

`db.collection('users').doc(this.user.username).update({ 
viewedCompanyProfileIds: currentViewedCompanyProfileIds }) 
.then(() => {  this.bindUserDoc() })`

and

`bindUserDoc: firestoreAction( 
({bindFirestoreRef, state, commit}) => { 
return bindFirestoreRef('userDoc', db.collection('users').doc(state.user.username)).then( 
() => { 
commit('setViewedCompanyProfileIds', state.userDoc.viewedCompanyProfileIds || []) }) } )`

This may be overly tedious if you're using this pattern a lot, and it may have problems that I'm not aware of, but it did resolve our issue without having to make changes to the library.

**Comment by marco-quintella** [comment]
> We were actually able to solve this issue by rebinding to the collection after calling update.
> 
> `db.collection('users').doc(this.user.username).update({ viewedCompanyProfileIds: currentViewedCompanyProfileIds }) .then(() => { this.bindUserDoc() })`
> 
> and
> 
> `bindUserDoc: firestoreAction( ({bindFirestoreRef, state, commit}) => { return bindFirestoreRef('userDoc', db.collection('users').doc(state.user.username)).then( () => { commit('setViewedCompanyProfileIds', state.userDoc.viewedCompanyProfileIds || []) }) } )`
> 
> This may be overly tedious if you're using this pattern a lot, and it may have problems that I'm not aware of, but it did resolve our issue without having to make changes to the library.

In my case, the binding is coming from a higher component. Not connected with the one that do the changes. To implement your solution I would need to use Vuex Store or a chain of events.

The solution from the library would be great! Since it`s already incredible the quality of the work done.

**Comment by marco-quintella** [comment]
Doing some tests in a possible solution

**Comment by posva** [comment]
@marco-quintella Unfortunately I haven't been able to take a look so I don't have a clue beyond of where the problem is beyond the ref diffing you mentioned. So I think you are on a good track!

**Comment by MorisseJarnas** [comment]
@posva & @marco-quintella  I am also encountering this issue. Any news on this?

**Comment by posva** [comment]
I found the problem and a solution. I need to refactor some of the code and write unit tests before releasing a new version. I will probably be able to in a week or so 🙂
