### ISSUE TITLE
this is undefined when binding

### ISSUE THREAD

**Issue by haymh** [vuejs/vuefire#33]
```
props: ['roomId'],
firebase: {
    messageList: db.ref('/room/${this.roomId}/messages'),
    user: {
      source: userRef,
      asObject: true,
    },
  },
```
I got `roomId of undefined` error.
How can I use `this` when binding?

**Comment by posva** [comment]
Use the `$bindAsObject` or `$bindAsArray` method. You can find an example on the [Usage Section](https://github.com/vuejs/vuefire#usage)
