### ISSUE TITLE
Array fill ES6 (IE 11)

### ISSUE THREAD

**Issue by JFGHT** [vuejs/vuefire#332]
I'm still working with cross browser compatibility and there's an error in IE 11 with this line of code:

https://github.com/vuejs/vuefire/blob/2ebb67b3d3655043729a4abf266b5da1c0037aad/packages/%40posva/vuefire-core/src/firestore/utils.ts#L40

`Object doesn't support property or method 'fill'`

**Comment by posva** [comment]
Thanks for checking. I removed the fill as it shouldn't be necessary and published a new version
