### ISSUE TITLE
Request for complete example in VuexFire docs

### ISSUE THREAD

**Issue by comfytoday** [vuejs/vuefire#341]
I had trouble getting VuexFire working, and I don't think the docs were very helpful.

For example: 

In the VuexFire [Docs](https://vuefire.vuejs.org/vuexfire/binding-subscriptions.html#binding-in-actions)
 under **Bindings in actions** example the `state` property is called `documents`, then in the action the first parameter is called 'todos', the ref is 'documents'... 

```javascript
// store.js
import Vuex from 'vuex'
import { vuexfireMutations, firestoreAction } from 'vuexfire'
import { db } from './db'

export default new Vuex.Store({
  state: {
    documents: []
  },

  mutations: vuexfireMutations,

  actions: {
    bindTodos: firestoreAction(({ bindFirestoreRef }) => {
      // return the promise returned by `bindFirestoreRef`
      return bindFirestoreRef('todos', db.collection('documents'))
    })
  }
}
```

The API for the bindFirestoreRef is says:
`bindFirestoreRef(key: string, ref: Query, options?): Promise<Object[]>`

It's unclear what the `key` and the `ref` actually are.

Perhaps a straightforward example would clear things up.

**Comment by posva** [comment]
Thanks, it should have been `todos` in the state and the collection. It's been fixed on 9277cfecead0e2ead3b7747f057cb5b2a5ac00c0 and I added another clarification.
If you ever found improvements, you can click on the _Edit this page_ button at the end of the page to help us improve it!
