### ISSUE TITLE
Vue Typescript with Firestore decorator

### ISSUE THREAD

**Issue by webcoderkz** [vuejs/vuefire#356]
If i use:

```
@Component({
  firestore() {
    return {
      linksArray: db.collection('links').orderBy('created', 'desc')
    }
  }
})
```

It is fetching data from firestore, but is it possible to use it in a `created()` lifecycle, so i could show up a loader for example?

**Comment by posva** [comment]
Yes, use `this.$bind` (https://vuefire.vuejs.org/vuefire/binding-subscriptions.html#programmatic-binding)
