### ISSUE TITLE
error when binding

### ISSUE THREAD

**Issue by sacrosanctic** [vuejs/vuefire#372]
i get this error but the binding works
it seems like during the binding the data reloads for a brief moment and thus the error

is there a way to structure it differently so the error doesnt come up 

`[Vue warn]: Error in render: "TypeError: Cannot read property 'name' of undefined"`

store.js
```
  actions: {
    init: firebaseAction(function(context) {
      context.commit('setLoading',true)
      context.bindFirebaseRef('names', db.ref(ref))
      context.commit('setLoading',false)
    }),
...
```

main.js
```
new Vue({
  router,
  store,
  vuetify,
  render: h => h(App),
  created () {
    this.$store.dispatch('init')
  }
}).$mount('#app')

```

**Comment by posva** [comment]
you are probably trying to access the array `names` before it is accessible. The same as when fetching data, there is a moment the local variable is empty and you need to guard against it using `v-if` or waiting for the data to be present to render
