### ISSUE TITLE
Accessing .key values

### ISSUE THREAD

**Issue by SonarBeserk** [vuejs/vuefire#38]
What is the syntax to get a data value's .key value? Neither {{ obj.key }} nor {{ obj.'.key' }} work for me.

**Comment by romines** [comment]
To retrieve the key when you have a reference to the object, try `obj['.key']`

I am having trouble referencing the firebase item after I have determined the key.

From inside the component where the ref is setup, `this.$firebaseRefs.myRoot.child(key)` seems like it should work, but no luck so far. It gives me back something that looks like this:

![screen shot 2016-10-21 at 12 06 14 am](https://cloud.githubusercontent.com/assets/1072819/19588359/62b34e40-9722-11e6-9d1f-9ab5fe57508b.png)

**Comment by posva** [comment]
It's what @romines said
If you can share some code I may help you. Ideally a repro on a fiddle would make things faster

**Comment by PedroFelipe** [comment]
try this:
`v-for="(item, key, index) in items"`

and `{{ key }}` 👍

**Comment by jamesxv7** [comment]
@PedroFelipe In your example the key value will be the number (position) of the array and not the value of the .key item. In that case you need to use the method that @romines mention. Using your example it will be something like: `{{ item['.key'] }}`
