### ISSUE TITLE
Can't access $route params in .vue component

### ISSUE THREAD

**Issue by srobertson421** [vuejs/vuefire#39]
Currently I'm having difficulty accessing any $route params from vue-router in order to utilize the params for vuefire queries. It seems like the vuefire property is tied to to a different context rather than the VueComponent context that other component hooks utilize.

Here is some code to explain:

My view component that needs access to the $route.params. This is what I'd hoped to use:
```html
<template>
  <h1>{{job.title}}</h1>
</template>

<script>
  import db from '../services/firebase-service.js';
  
  export default {
    data() {
      return {
        
      }
    },
    firebase: {
      job: {
        source: db.ref('jobs/' + this.$route.params.id),
        asObject: true
      }
    }
  }
</script>

<style></style>
```

While currently I am doing this as a workaround, utilizing the global location object:

```html
<template>
  <h1>{{job.title}}</h1>
</template>

<script>
  import db from '../services/firebase-service.js';
  
  export default {
    data() {
      return {
        
      }
    },
    firebase: {
      job: {
        source: db.ref('jobs/' + location.pathname.substring(5, location.pathname.length)),
        asObject: true
      }
    }
  }
</script>

<style></style>
```

Since the "firebase" property is applied on the component level I assumed it would also be referencing the VueComponent context but instead it references a different context like this:

```json
"{
  "default":{
    "firebase":{
      "job":{"asObject":true}},
      "__file":"/Users/seanrobertson/Projects/vue-spa/src/pages/JobShow.vue",
      "staticRenderFns":[],
      "beforeCreate":[null],
      "beforeDestroy":[null]
    }
}"
```

Is there a way to reference the current component context from within the firebase property? I have looked at #10 but I'm not sure it's applicable as I am using npm and webpack. Any help would be appreciated as I'm not too keen on the location hackery.

**Comment by DaBs** [comment]
Take a look at whether [#25](https://github.com/vuejs/vuefire/pull/25) fixes your problem. I believe it should.

**Comment by posva** [comment]
Doing this out of a function refers to the window object.
As @DaBs said, you can use a function instead of an object to access the vm

**Comment by srobertson421** [comment]
Ah awesome, I guess I misunderstood. Thanks @posva and @DaBs !!!

**Comment by Kimeiga** [comment]
Hey all! Sorry I might be missing something but when trying this I am just left with an empty object:

```vue
<template>
  <div>
    {{ $route.params.id }}
    {{ firebase().eventData }}
  </div>
</template>

<script>
import { db } from "../db";

export default {
  data() {
    return {
      eventData: {},
    };
  },
  firebase() {
    return {
      eventData: {
        source: db.collection("events").doc(this.$route.params.id),
      },
    };
  },
};
</script>
```

Is there a different way that we are supposed to be getting the data when its coming from `firebase()`?

**Comment by Kimeiga** [comment]
Ok I think what fixed it was to use the following instead of `firebase()`
```vue
  firestore() {
    return {
      eventData: db.collection("events").doc(this.$route.params.id),
    };
  },
```
