### ISSUE TITLE
Wrong type of 'this' inside firestore() context

### ISSUE THREAD

**Issue by ebeloded** [vuejs/vuefire#399]
I am getting typing errors when trying to access props/methods of Vue instance inside of `firestore` function. In the example below, `uid` is a prop and I get no typing errors when accessing from `created` lifecycle hook, but it is not defined inside firestore function.

```ts
export default Vue.extend({

  props: ['uid'],

  created() {
    console.log({ uid: this.uid }) // this.uid is fine
  },

  firestore() {
    // Error: "Property 'uid' doesn't exist on type Vue"
    const uid = this.uid 
    return {
      user: db.doc(`users/${uid}`),
    }
  },
})
```

This can resolve the issue, but shouldn't be necessary:
```ts
const uid = (this as any).uid 
```

**Comment by posva** [comment]
Types are not added to the options of `Vue.extend`. This should be added to firebase as well

**Comment by posva** [comment]
Things have changed in v3 in order to support Vue 2 and Vue 3 at the same time so `this` will only be the component instance with loose typings
