### ISSUE TITLE
Docs: popup refresh box always there. Is this your code?

### ISSUE THREAD

**Issue by fergusmeiklejohn** [vuejs/vuefire#403]
I see a floating box in the bottom right corner of the window on all pages. Text: "New Content is Available" Button: "Refresh"

Only see this on desktop and on chrome.

Is this your code?  Thanks :-)

![Screenshot 2019-09-25 at 10 17 54](https://user-images.githubusercontent.com/11864025/65564042-359f0c80-df7e-11e9-8a9a-d1fa9b3bc516.png)

**Comment by posva** [comment]
yes, it's to update the content of the pwa
