### ISSUE TITLE
No data is being returned

### ISSUE THREAD

**Issue by jakeols** [vuejs/vuefire#41]
I've been playing around with vuefire for a bit now, and can't seem to get it to return any data. I thought it could be my database rules, so for testing I even opened them up completely, but still nothing. I tried both a regular environment and module environment using webpack. No errors are returned, and in the vue.js dev tools it just shows this:

![screen shot 2016-10-31 at 12 17 14 pm](https://cloud.githubusercontent.com/assets/3232346/19861717/0854a558-9f64-11e6-84ec-e52c388d4725.png)

this is my code:

```
var config = {
    apiKey: "...",
    authDomain: "...",
    databaseURL: "...",
    storageBucket: "...",
    messagingSenderId: "..."
  };

const firebaseApp = firebase.initializeApp(config)
 const db = firebaseApp.database()
 const usersRef = db.ref('Users')

export default {
data () {
  return {

  }
},
firebase: {
  users: usersRef
}
}
```

I've tried different references and everything, but nothing is returning. Any idea what could be going wrong?

**Comment by jwngr** [comment]
Can you please share your code which actually uses VueFire to bind the Firebase reference to Vue?

**Comment by jakeols** [comment]
What do you mean? I just have my app.js that just imports vue, vuefire and firebase like so: 

```
var Vue = require('vue')
var VueFire = require('vuefire')
var Firebase = require('firebase')
Vue.use(VueFire)
```

**Comment by jwngr** [comment]
I'm looking for the code that actually makes use of VueFire as shown in [the "Usage" section of the `README`](https://github.com/vuejs/vuefire#usage).

**Comment by chrisvfritz** [comment]
@jakeols You can check out [the example](https://github.com/vuejs/vuefire/blob/master/examples/todo-app/index.html) for a complete example. That may help you pinpoint what's going on. Perhaps `db.ref('Users')` should be `db.ref('users')`? Not sure if it's case-sensitive.

**Comment by jakeols** [comment]
@jwngr I was under the impression that `firebase: { users: usersRef }` would bind that array to the firebase ref?

**Comment by jakeols** [comment]
Here's a complete example of the problem not in a module envirnment:

```
<html>
<body>
  <div id="demo">
      <p>@{{ item }}</p>
  </div>
  <script src="https://cdn.jsdelivr.net/vue/1.0.24/vue.js"></script>
  <script src="https://gstatic.com/firebasejs/3.0.3/firebase.js"></script>
  <script src="https://cdn.jsdelivr.net/vuefire/1.1.0/vuefire.min.js"></script>
  <script>
  var config = {
      apiKey: "...",
      authDomain: "...",
      databaseURL: "..."
  };

var firebaseApp = firebase.initializeApp(config)
var db = firebaseApp.database()
var usersRef = db.ref('Users')

var vm = new Vue({
  el: '#demo',
  firebase: {
    users: usersRef
  }
})
  </script>
</body>
</html>
```

**Comment by jwngr** [comment]
Can you confirm that you have data in your Firebase Database at the top-level `Users` node? Can you share a screenshot? As @chrisvfritz mentioned, the string is case-sensitive, so maybe you want `"users"` instead of `"Users"`.

Also, what happens if you replace `{{ item }}` in your view with `{{ users }}` since your variable is called `users`, not `item`?

**Comment by jakeols** [comment]
Yes, here's a screenshot. 

![screen shot 2016-10-31 at 1 59 42 pm](https://cloud.githubusercontent.com/assets/3232346/19865366/557361cc-9f72-11e6-9c74-76e26e0eee52.png)

And sorry, I copied the above together- fixing it to `{{ users }} ` still has the described error.

**Comment by jwngr** [comment]
Do you have permission to read the data? By default, you need to be authenticated to read the data. Check the JavaScript console for any `PERMISSION DENIED` errors. If you have one, you need to either anonymously log in before reading data or update your Security Rules to be read / write `true`.

**Comment by jakeols** [comment]
Yes I have permission- I even set my database rules to allow anyone to read data just to see if that was the case. There are no errors in the console at all...

**Comment by jwngr** [comment]
Can you put together a JSFiddle or Plunker with a minimal repro? I'm unfortunately running out of ideas to be honest... Only other thing I can think of is that you are connecting to the wrong `databaseURL`.

**Comment by jakeols** [comment]
Sure- here's a JSFiddle.  https://jsfiddle.net/txb7hos1/4/

**Comment by jwngr** [comment]
Your dependencies are out of date. Upgrading Firebase and VueFire to the latest versions makes the JSFiddle work:

```
<script src="https://www.gstatic.com/firebasejs/3.5.2/firebase.js"></script>
<script src="https://cdn.jsdelivr.net/vuefire/1.3.0/vuefire.min.js"></script>
```

**Comment by valentinoper** [comment]
Hey guys even im facing a similar issue.. I'm following the tutorial on https://medium.com/codingthesmartway-com-blog/vue-js-2-firebase-e4b2479e35a8 , but i cant access the `firebase: {books: booksRef},` using `this.books` in any of my methods, and i get the console error _[Vue warn]: Property or method "books" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property._ Can someone post their working example of vuefire ? I am stuck

**Comment by mithun-sarkar** [comment]
Hey guys even im facing a similar issue.. I'm following the tutorial on https://medium.com/codingthesmartway-com-blog/vue-js-2-firebase-e4b2479e35a8 , but i cant access the firebase: {books: booksRef}, using this.books in any of my methods, and i get the console error [Vue warn]: Property or method "books" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. Can someone post their working example of vuefire ? I am stuck.

**Comment by posva** [comment]
@mithun-sarkar (even though you just copy pasted the previous message) this issue is for vuefire@1. We are now at vuefire@3. I recommend you checking out the documentation for up to dates instructions because the post is also outdated (https://medium.com/@posva/hello-for-anybody-coming-i-wanted-to-clarify-that-there-were-some-changes-in-the-latest-version-75249cf4ed18) You are probably missing the declaration of the property `books` in `data`

I'm locking this issue as it is very old, feel free to open a new issue with a small reproduction if you find something not working.
