### ISSUE TITLE
Binding classes rather than plain objects?

### ISSUE THREAD

**Issue by garyo** [vuejs/vuefire#416]
My vuex objects are typescript classes with methods as well as data. When I write out to Firestore, I have to serialize the objects (convert them to basic objects; I'm using https://github.com/typestack/class-transformer for that). 

So then vuexfire is reading them back as plain objects too, so they're not proper object instances. Is there any hook in vuexfire to convert the document(s) to classes (or any other transformation that may be needed)?

**Comment by posva** [comment]
Use `serialize`: https://vuefire.vuejs.org/api/vuexfire.html#firestoreaction
It can also be set globally by importing the options
