### ISSUE TITLE
Confusing use of firestoreAction in docs

### ISSUE THREAD

**Issue by kassuro** [vuejs/vuefire#419]
Hello,
I'm a little bit confused about the use of firestoreAction in the "writing to the database" part of the docs.
In the docs the examples are as the following:
```javascript
firestoreAction(({ state }) => {
  // we first create a copy that excludes `id`
  // this exclusion is automatic because `id` is non-enumerable
  const user = { ...state.user }
  user.lastName = newLastName

  // return the promise so we can await this action
  return db
    .collection('users')
    .doc(this.user.id)
    .set(user)
    .then(() => {
      console.log('user updated!')
    })
})
```

But in this case it seems it doesn't make sense to wrap the action in the firestoreAction as we don't bind or unbind here. The action works totally fine without being wrapped in the firestoreAction.

Is there any other reason than wanting to bind or unbind to wrap a action in a firestoreAction?

**Comment by posva** [comment]
It's indeed not necessary, it's there to show we are inside of an action. I'm open to PR improving it!

**Comment by kungpaogao** [comment]
I agree that this should be updated. I was pretty confused as to what this meant until I saw this issue. I'll see if I can think of a better way to write the documentation.
