### ISSUE TITLE
Is it possible to reject specific `ARRAY_ADD` mutations? 

### ISSUE THREAD

**Issue by zvadym** [vuejs/vuefire#442]
My case: 
I have action to create some object (called `card`)

```js
createCard({ commit, getters, dispatch }) {
    const card = { ... }
    commit(ADD_CARD, card)
    dispatch('firebaseSetCard', { card })
  },
```
The action adds card to vuex state and also dispatch `firebaseSetCard`

```js 
firebaseSetCard: firestoreAction((context, { card }) => {
    return cardsRef.doc(card.id).set(card)
  }),
```

It works great. 

Also I have binding between firebase and my state:

```js
firebaseBindCards: firestoreAction(({ bindFirestoreRef }) => {
    return bindFirestoreRef(
      'cards',
      cardsRef
    )
  })
```

And it dispatches `vuexfire/ARRAY_ADD` with the same "card" data. As result I have two identical cards! And I have to idea how to reject this action..

I undestand that I can skip my `commit(ADD_CARD, card)`, but I want to make my app works offline, so I have to add data to state at first and then update "firebase" in case if it's possible (app online)

**Comment by posva** [comment]
It's not possible to _reject_ specific mutations but more importantly, you shouldn't mutate the array bound by vuexfire, you should treat it as readonly. Regarding your situation, there is no need to do that workaround for offline as firebase already supports such feature and it doesn't require anything on vuefire side
