### ISSUE TITLE
vuexfire:  pagination

### ISSUE THREAD

**Issue by muhammedjenos** [vuejs/vuefire#476]
Getting frustrated to solve this since I am no JS expert. 😢

I just want some help to figure out how to get a doc ref which is already bound in the state using vuexfire and use a query cursor to get more data and append to the existing state. I am trying to implement an infinite scrolling to display a list of 1500 records fetching 40 at a time.

Any help will be highly appreciated. 🙏🏽

**Comment by muhammedjenos** [comment]
Any one?

**Comment by posva** [comment]
There is a request to document this at https://github.com/vuejs/vuefire/issues/145

**Comment by tohagan** [comment]
Posted this list of potential solutions ... https://stackoverflow.com/a/62650214/365261
