### ISSUE TITLE
Reconnecting to firebase after signin.

### ISSUE THREAD

**Issue by prenna** [vuejs/vuefire#48]
I am having signin and diplay of data in the same file.

Obviously the user cannot retrieve data when they are not signed in.
After a user is authenticated, how do I tell vue to refresh the firebase refs when the authentication state is changed without refreshing the page?

**Comment by prenna** [comment]
I just read through the readme again...

I think if I do manual bindings in my onAuthStateChanged callback this will solve my issue.

**Comment by prenna** [comment]
I am now getting this error in the console:

`vuefire.js:187 Uncaught TypeError: source.on is not a function(…)bindAsArray @ vuefire.js:187bind @ vuefire.js:155init @ vuefire.js:276callHook @ vue.js:1835Vue._init @ vue.js:2579Vue$3 @ vue.js:2626(anonymous function) @ index.html:120`

this is my code:

`auth.onAuthStateChanged(function(user) {
			if(user) {
				app.$bindAsArray('user', db.ref('users/' + auth.currentUser.uid));
				app.signedIn = true;
			} else {
				app.$firebaseRefs.user = {};
				app.signedIn = false;
			}
		});`

**Comment by posva** [comment]
Yes, you can do it that way although I'd recommend you to separate the views/partial views where the user has to be authenticated so you can decide not to display them when the user is not logged in yet

**Comment by prenna** [comment]
It worked... and I already thought of that, I am using v-if to display certain ui components dependent on whether a user is signed in or not.

**Comment by posva** [comment]
I mean that having the auth logic at a router level is better. Using v-ifs may not be the best solution
