### ISSUE TITLE
Question: config files best practice.

### ISSUE THREAD

**Issue by rstormsf** [vuejs/vuefire#50]
Lets say I'm using `vue-cli` to init my vue project. Where in that folder structure is the best place to define my config variables(firebase vars) so I don't have to include them in git repo. 
Just need some advice on that.

**Comment by chrisvfritz** [comment]
How about just in environment variables? Then in development, you can use something like [dotenv](https://www.npmjs.com/package/dotenv) to check in non-sensitive config for development and testing.

**Comment by rstormsf** [comment]
you are right.  I also looked how this person did it there: https://github.com/zerostatic/vuejs-firebase/blob/master/src/helpers/firebaseHelpers.js

I was trying to use `config/prod.env.js` file, but realized that it's only for build configs.

**Comment by chrisvfritz** [comment]
I also personally like to use separate dev databases for each developer, configured by reading each dev's username (e.g. with `whoami`). That way, devs can work at the same time without stepping on each other's toes.

**Comment by rstormsf** [comment]
Thanks @chrisvfritz great tips!
