### ISSUE TITLE
Question: Firebase 3 authentication model

### ISSUE THREAD

**Issue by dsl101** [vuejs/vuefire#51]
I'm currently using Vue 2 and Firebase separately, and struggling to get the app to manage authentication nicely - for example, the Vue `created()` method fires before the Firebase `auth()` object is created, which makes the Vue app think the user isn't logged in even if they are.

Do you have any plans to integrate authentication in vuefire to simplify this? It seemed from the examples that vuefire expects authentication to happen elsewhere, but that's exactly what I'm struggling with... I will keep at it, but I thought if you were heading in that direction anyway, it might help :)

**Comment by posva** [comment]
Authentication can be handled with the firebase sdk alone so it isn't worth adding an api layer with no extra functionality to vuefire. Using vue-router can simplify the task though because you can use a guard to redirect to different pages depending on the auth status.
