### ISSUE TITLE
How to listen to changes real-time without reloading the page when using VuexFire

### ISSUE THREAD

**Issue by peoray** [vuejs/vuefire#518]
On the `Querying the database` [page](https://vuefire.vuejs.org/vuexfire/querying.html#one-time-read), it shows how to retrieve a collection that is only used once but didn't show having the data updated in real-time whenever you modify the firestore DB

What do I do when I want my site updated whenever I make changes directly on the firestore DB without reloading the page

**Comment by posva** [comment]
https://vuefire.vuejs.org/vuexfire/binding-subscriptions.html#binding-in-actions
