### ISSUE TITLE
bindFirestoreRef fails to handle refs with .where() and .orderBy()

### ISSUE THREAD

**Issue by joemanfoo** [vuejs/vuefire#525]
In my state I have `postsToPublish: []`

In my bind action I've got a query such as:
`let ref = db.collection('posts')
  .where('published', '==', false)
  .orderBy('createdAt')`

and then bind with:
`return bindFirestoreRef('postsToPublish', ref)`

If the `.where('published', '==', false)` is on the collection query and the `.orderBy(...)` then the documents bound is only one when there ought to be more (in my testing case there are three).

If I remove the `.orderBy(...)` then the correct documents are bound but obviously not ordered.

Anyone bump into this? or is able to confirm this as a bug?

**Comment by posva** [comment]
Can you boil it down? You can use the example with the todos: https://github.com/vuejs/vuefire/blob/master/packages/vuexfire/examples/index.html

**Comment by joemanfoo** [comment]
I'll work on standing up a repo.

**Comment by joemanfoo** [comment]
So the issue was lack of indexes and firebase not writing to the console that there was a need to have an index like it usually does. While putting together the repo to isolate the problem firebase did correctly communicate the need for an index to run the queries. Once I added the indexes on the other database collection(s) things were correct.

The weird part is rather than sending error message to the console, firebase was letting one record "slip through"...

Thanks @posva for the work and time on this project and my error.

Merry Christmas!

**Comment by posva** [comment]
that's weird! I'm glad you found the culprit! Happy holidays to you too!
