### ISSUE TITLE
cancelCallback in object

### ISSUE THREAD

**Issue by rstormsf** [vuejs/vuefire#53]
I'm eager to know what do the cancelCallback should do when defining a data as an object

**Comment by posva** [comment]
Actually, you can use it with arrays too. The cancellCallback is more of an error handler, but that's the name given in firebase doc. Here's a quote from there:

> We can pass an optional cancel callback to our event subscription that will be called if the read is ever cancelled. A read would be cancelled if the app client doesn't have permission to read from that database reference. This callback will be passed an error object indicating why the failure occurred.

(it also works for write)

**Comment by rstormsf** [comment]
thank you @posva I wanted to ask of it's ok to get instance of my FBapp like this
https://github.com/rstormsf/friendsmap/blob/WIP-read-write/src/components/Auth.vue#L9

I'm afraid it instantiated every time I call it. But it doesn't happen so.

**Comment by posva** [comment]
It should be ok. You can also create a service to handle that. It's up to you
