### ISSUE TITLE
Firestore document delete is not observed

### ISSUE THREAD

**Issue by jmsuresh** [vuejs/vuefire#539]
If I bind a document using $bind, the changes to the field values are observed and updated in the value. But, if the document is deleted, the bound value is still referring to the last value just before the delete.

Versions:

```
`-- vuefire@2.2.0
`-- vue@2.6.10
`-- firebase@7.6.1
```

**Comment by posva** [comment]
this was indeed handled for collections but not for documents

**Comment by mfissehaye** [comment]
Do you plan to add support for listening document deletions?
