### ISSUE TITLE
Dont have uid

### ISSUE THREAD

**Issue by odranoelBR** [vuejs/vuefire#54]
How can i get uid like this example

  firebase: {
       anArray: db.ref('url/to/my/collection' + uid),
    
  }

Its hard because i store the logged user into Vuex, but i dont have access vue scope in firebase: {}

**Comment by odranoelBR** [comment]
Solved whit manual binding 
  mounted () {
      this.$bindAsObject('turmas', FirebaseApp.database().ref(`turmas/${FirebaseApp.auth().currentUser.uid}`))
    }

tks

**Comment by BernardMarieOnzo** [comment]
cool
