### ISSUE TITLE
No timeout when internet is down

### ISSUE THREAD

**Issue by diego-bevilaqua86** [vuejs/vuefire#551]
I'm using Vuefire to connect a website and store some clients' contact info. Everything works as planned - I can connect to the Firebase project, access a Firestore document collection, add() the data there, and even query it whenever necessary. I do so like this:

In a db.ts file:
```typescript
import firebase from "firebase/app";
import "firebase/firestore";
import Firestore = firebase.firestore.Firestore;

class FirestoreDB {
  private db = firebase
    .initializeApp({ projectId: MY-PROJECT-ID })
    .firestore();

  public getInstance(): Firestore {
    return this.db;
  }
}

export default new FirestoreDB();
```

Then, in my Vue component:
```typescript
db.getInstance()
  .collection(MY-COLLECTION)
  .add({
    property: INFO,
    ...
  })
  .then(() => { WHATEVER-I-DO-WHEN-SUCCESSFULL })
  .catch(() => { WHATEVER-I-DO-WHEN-FAILURE-HAPPENS });
```

Now, one clear example of a failure - at least in my understanding - is lack of Internet connection. I thought that some attempts to send the data would be made and, when a certain number of failures happened, the promise would reject so I could grab it on catch, but that doesn't happen. Not really sure if this is by design, if something is missing, or if I'm not doing it the right way, but I needed to know if that kind of thing happens so I can show something to the user.

**Comment by posva** [comment]
Hello, writing to the firebase database is part of the Firebase JS SDK, there isn't any code in vuefire for that 🙂 
You should probably contact them on their forum or Github issues. I also happen not to know the answer to your question!

**Comment by diego-bevilaqua86** [comment]
Well, searching in the right place (meaning Firebase / Firestore sources) led me to understand that this behavior is indeed a feature for Firebase's databases. They only reject the `add()` promise when there are problems with Firebase itself (I.E. inexistent collection or something like that), so i ended up building some helper functions in order to detect and correctly notify about internet connectivity. Thanks anyway, @posva =D

**Comment by posva** [comment]
Thanks for posting back what you found
