### ISSUE TITLE
Dynamic firebase configuration

### ISSUE THREAD

**Issue by srinivasdamam** [vuejs/vuefire#56]
I have a problem with initialising the firebase.
1. First when user provides credentials I make a rest api call to get the firebase configuration since our app has different clients with different firebase instances.
2. Now that I can't use variable `db` ( firebase.database() ) in components since I haven't initialised firebase because the user is not logged in yet. This throws an error saying firebase app is not initialised.

**Comment by posva** [comment]
Make sure the components using vuefire are on views that are available only when credentials are ready, or use some kind of content fallback
