### ISSUE TITLE
Reactivity of documents bound to parent object

### ISSUE THREAD

**Issue by stevenanton-bc** [vuejs/vuefire#575]
I'm still pretty new to Vue, so apologies if this is a trivial question. Basically, my use case is that I would like to bind an arbitrary number of Firestore documents to an object in Vue. My approach, as described in this [Stackoverflow ticket](https://stackoverflow.com/a/59957625/2708667), is something along these lines:

```javascript
export default {
    name: "component",
    data: function () {
        return {
            docs: {},
            indices: [],
        }
    },
    watch: {
        indices: function (value) {
            value.forEach(idx => this.$bind(`docs.${idx}`, db.doc(idx)))
        },
        docs: function () {
            // This never triggers
        }
    }
}
```

The reactivity works well for `docs`; its properties (e.g. `doc['abc']`) whenever the Firestore document changes. However, the _watcher_ for `docs` never seems to trigger. I'm assuming this is related to [Vue's reactivity model](https://vuejs.org/v2/guide/reactivity.html). My best guess as to the cause is related to [this line](https://github.com/vuejs/vuefire/blob/f90470babb2a10574a561c3d2924a6f8435c089d/packages/%40posva/vuefire-core/src/shared.ts#L48). Is there any chance that `target[key] = value` should be changed to `Vue.set(target, key, value)` so that Vue adds the correct getters?

**Comment by posva** [comment]
This is indeed a reactivity caveat: https://vuejs.org/v2/guide/list.html#Object-Change-Detection-Caveats

You need to manually call Vue.set yourself to make it work. Always calling Vue.set has a negative performance impact we want to avoid
