### ISSUE TITLE
detailed example - vue2 components

### ISSUE THREAD

**Issue by greatramu** [vuejs/vuefire#58]
Hello experts!

am a beginner with vuejs, and so far I absolutely love it. Does anyone have a example application with vuefire using the Vue2 components (.vue files). 

I was also thinking if there is a clever way of integrating the firebase library with Vuex. Then the developer have to update the structures in the state and it somehow asynchronous with the firebase db. That would be very interesting.

**Comment by posva** [comment]
The examples in the readme should be enough for that purpose. If you're wondering where to put the firebase information, you should put it in some other `js` file and import it in your entry point (`main.js`).
About Vuex, you should look at https://github.com/posva/vuexfire. The version 2, which has a much better API, is still being developed but the project is alive (I'm the maintainer of that too)
