### ISSUE TITLE
[DOCS] Inform user that the site is a PWA and can work offline

### ISSUE THREAD

**Issue by ghost** [vuejs/vuefire#601]
Little UX improvement

**Comment by posva** [comment]
Following the tip at the top should allow anybody to do a PR: https://v1.vuepress.vuejs.org/plugin/official/plugin-pwa.html

**Comment by nainardev** [comment]
@posva I had a doubt

**Comment by nainardev** [comment]
Will Vuex be updated for vue@3   ?
