### ISSUE TITLE
Specifiy a constructor to use when binding collections

### ISSUE THREAD

**Issue by Pitouli** [vuejs/vuefire#602]
I have a collection of contacts in firestore, with a firstname and a lastname. 

Thanks to vuexfire, I can easily sync this collection with my app , and vuexfire is doing intelligent "add / remove / update" operations without having to completely destroy and recreate the whole `dbContacts` array everytime.

But in my app, instead of accessing the raw `{firstname, lastname}` object, I would like to use a class `person`, so I can have access to the method `getFullName()` for example.

Today, I have a vuex getter which loops over the `dbContacts` array to populate and return the `classContacts` array. Thanks to vuex, the result is cached, but as far as I know, every time 1 contact is modified in the `dbContacts` array,  then the whole `classContacts` array is recomputed. 

Wouldn't be possible to specify to vuexfire that the synced array should create objects using a given constructor, so it can surgically add/remove/update only the contact that has been modified in the db?

**Comment by posva** [comment]
Checkout the serialize option: https://vuefire.vuejs.org/api/vuefire.html#options-serialize
