### ISSUE TITLE
When is binding completed?

### ISSUE THREAD

**Issue by gootyfer** [vuejs/vuefire#61]
Newbie here, hope it's a good question. 
When I bind an array to a server ref, I want to know when the binding is completed and the data available in the vue object. Is that somehow possible? 
Thanks for such a nice library!

**Comment by posva** [comment]
I may be missing something in Firebase but I don't think it's possible natively in Vuefire.
However, you can use the `once` listener on the ref to get the whole array, then in a watch, check if the array is the same as in your component (checking the present keys are the same is enough)
IMO you shouldn't rely on having the whole data in your vue object. It should be easy to manage an incomplete array state with Vue

Cheers!

**Comment by gootyfer** [comment]
Thanks for the answer. I re-phrase my question since I didn't explained myself well.

1. I'm binding an object (not array this case) using `app.$bindAsObject('profile', profileRef);`
2. I want to access `app.profile.courses` but it's not immediately accesible but when the object is filled with the server data. Can I do something like `app.$bind().then()` instead of retrieving the data manually with `once`?

Thank you, Eduardo!

**Comment by posva** [comment]
> Can I do something like app.$bind().then() instead of retrieving the data manually with once?

This is something I was thinking of implementing, at least for objects. But its purpose was to make SSR possible. I'm not sure if the `once` callback ensure that the data is available on the Vue instance. My advice would be to make it fault tolerant. eg: wrap the profile in a component and use a `v-if` to display it, passing down the profile as a prop. You can also display a fallback content with `v-else`
With this you can also implement some kind of timeout behaviour in the default component to display an error message like "no internet connection"

**Comment by dizid** [comment]
@gootyfer Hi Israel, have you found a solution for this?
I have not, after a day of searching and trying.

**Comment by gootyfer** [comment]
> @gootyfer Hi Israel, have you found a solution for this?
> I have not, after a day of searching and trying.

Nope, as far as I remember :) @dizid
