### ISSUE TITLE
Customizing behavior of binding resolutions

### ISSUE THREAD

**Issue by geraldbiggs** [vuejs/vuefire#622]
I'm curious if there is any direction towards allowing for customizing the resolution logic of a synced event. Adjunct to the process of how serialize allows for both a global, or per context modification of an individual document... could there be a way to create global / context-specific overrides for resolving the add / remove / set behavior?

I'm speaking from a vuex circumstance, but I imagine it could be implemented vue-side as well. Effectively using the binding / subscription logic to manage the document or collection subscription, detecting the event type - and allowing the userland's logic handle its resolution. In the case of vuex, it could be as direct as dispatching a different action. 

```
// passes array for collections or single doc object for a single doc binding.
bindFirestoreRef("data", db.firestore().collection("posts"), {
      add: docs => {
            dispatch('fancyAddPosts', docs)
            //additional user logic? 
      },
      set: docs => {
           dispatch('fancyUpdatePost', docs)
      }
});

Thank you

**Comment by trickstival** [comment]
I'm not sure if that makes much sense.

If you want to customize some behavior in the userland, you could make an abstraction in your app.
Vuefire is just a way of binding data from your firestore / rtdb to your local state.

If it's really a context-specific situation it would probably be easier to understand the code if you write it using the firebase sdk directly.

**Comment by posva** [comment]
This is indeed way too much for Vuefire. If you need that level of control to sync on events themselves, you probably be better implementing a custom logic similar to what vuefire-core does
Internally we use `@posva/vuefire-core` (https://github.com/vuejs/vuefire/blob/master/packages/%40posva/vuefire-core/src/shared.ts#L3-L7 and https://github.com/vuejs/vuefire/blob/master/packages/%40posva/vuefire-core/src/firestore/index.ts#L167) to expose that logic to both vuefire and vuexfire, but it's not public api.

There is a way to serialize documents to control how they are added to vue: https://vuefire.vuejs.org/api/vuefire.html#firestoreplugin
