### ISSUE TITLE
Nothing happens vuexfire?

### ISSUE THREAD

**Issue by fredriklugg** [vuejs/vuefire#626]
```
//store/modules/Event.js
import db from "../../config/firebaseInit";
import { firestoreAction } from "vuexfire";

//mutations is set in the root file
const state = {
  events: []
};
const actions = {
  setEventsRef: firestoreAction(({ bindFirestoreRef }) => {
    // return the promise returned by `bindFirestoreRef`
    return bindFirestoreRef("events", db.firestore().collection("Events"));
  })
};
export default {
  state,
  actions
};´
```
```
//dispatch in vue file
//template:
<ul>
    <li> 
         {{ events }}
   </li>
</ul>
//script:
computed: mapState(["events"]),
created() {
    this.$store.dispatch("setEventsRef", db.firestore().collection("Events"));
  }
```

trying to print and show the events in the vue file, logging that the setEventRef is being called but the events are still undefined when trying to render them in vue. is there anything i am doing wrong?

**Comment by posva** [comment]
They should appear as an empty array. The code seems good. Can you boil down a reproduction using one of our examples in the repo?

**Comment by fredriklugg** [comment]
Tried to make one here, hope it helps. Thank you.
https://codepen.io/frelu/pen/poJpvWy

**Comment by posva** [comment]
Can you make it runnable in codepen and add reproduction steps with expected vs actual behavior please

**Comment by fredriklugg** [comment]
I'm getting it to work in a codepen, so I will look over the structure of my code and see if I have done anything wrong.

https://codepen.io/frelu/pen/gOpopEg?editors=1111

**Comment by fredriklugg** [comment]
I have another question, it returns an empty array, but how do I use the data imported from a collection firestore?

**Comment by posva** [comment]
You need to add the data to the firebase database. Are you sure you don’t have a typo in the name of the collection? The array is empty if it doesn’t contain any elements or if doesn’t exist
