### ISSUE TITLE
Feature request to query documents based on geographic location.

### ISSUE THREAD

**Issue by rashidpathiyil** [vuejs/vuefire#633]
Please add a feature to query documents based on geographic location to retrieve documents within a given geographic area. So we can selectively load only the data near certain locations.

**Comment by posva** [comment]
See https://github.com/geofirestore/geofirestore-js. It works with vuefire

**Comment by rashidpathiyil** [comment]
How to configure Geofirestore with it?
Do you have any examples or documentation to help me please?

**Comment by posva** [comment]
Please check the documentation and examples I sent you, you can pass any reference generated by it to Vuefire

**Comment by wahmedswl** [comment]
Hi, can you plz share documentation and examples here.

Thanks
