### ISSUE TITLE
Can't access vuexfire store values in lifecycle hooks

### ISSUE THREAD

**Issue by jsonpoindexter** [vuejs/vuefire#639]
I am unable to figure out how to iterate a vuexfire binded collection in my store from a component's lifecycle hook.  Using the store value in a `v-for` does work. The example below I try to map over the `store.state.groups` array in the `mounted` lifecycle hook and I get an empty array back. 

Any guidance is greatly appreciated. Thank you.

src/store/index.js
``` 
import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)
import { vuexfireMutations, firestoreAction } from 'vuexfire'
import firebase from 'firebase/app'
import 'firebase/firestore'

const firebaseConfig = {
  apiKey: '...',
  authDomain: 'localhost',
  databaseURL: 'https://....com',
  projectId: '...',
  messagingSenderId: '...'
}

export const db = firebase.initializeApp(firebaseConfig).firestore()

export default new Vuex.Store({
  state: {
    groups: []
  },
  mutations: vuexfireMutations,
  actions: {
    bindGroupsRef: firestoreAction(context => {
      return context.bindFirestoreRef('groups', db.collection('groups'))
    }),
  },
})
```

src/components/HelloWorld.vue
```
<template>
    <div class="container">
      <p>Groups</p>
      <p :key="group.id" v-for="group in $store.state.groups">{{ group.name }} - {{ group.id }}</p>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  created() {
    this.$store.dispatch('bindGroupsRef');
  },
  mounted() {
    console.log(this.$store.state.groups); // [__ob__: Observer] w/ group objs inside
    console.log(this.$store.state.groups.map(group => group.name)); // []
  }
}
</script>
```

UI Result:
![image](https://user-images.githubusercontent.com/5003899/77017418-b04a5280-6937-11ea-9c39-9ce4ef6b8708.png)

Console Result:
![image](https://user-images.githubusercontent.com/5003899/77017434-bf310500-6937-11ea-89dd-0c39fbe45c0c.png)

Vue Debugger Store:
![image](https://user-images.githubusercontent.com/5003899/77017520-f30c2a80-6937-11ea-9430-1cfb9b7e5a5f.png)

**Comment by posva** [comment]
Since you are returning the promise in the action `bindGroupsRef`, you need to await it for data to be present on the state:

```js
async created() {
    await this.$store.dispatch('bindGroupsRef');
    this.$store.state.groups // now you can!
  },
```

You can also put it in a variable and then await the variable in `mounted`

```js
created() {
    this.promise = this.$store.dispatch('bindGroupsRef');
  },
  async mounted() {
    await this.promise
    console.log(this.$store.state.groups); // [__ob__: Observer] w/ group objs inside
    console.log(this.$store.state.groups.map(group => group.name)); // []
  }
```

If you don't await, the `mounted` hook runs before the array is populated. The same happen with any other asynchronous api like a REST call

**Comment by jsonpoindexter** [comment]
🤦‍♂  thank you for the quick and well written response @posva
