### ISSUE TITLE
[question] vuefire inside a vuex store.js file ?

### ISSUE THREAD

**Issue by beebase** [vuejs/vuefire#64]
Has anyone managed to set up a working solution with firebase and vuex?
I've managed to put something together with vuex and firebase.
- All calls (crud)  to firebase are done from within vuex actions.
- The firebase callbacks/listeners trigger the vuex mutations.
All works well, the vuex store always stays in sync with firebase. 
However, the view model (vue page) sometimes doesn't get updated anymore. The listener breaks for some reason.
Anyway, I wonder if vuefire would work well with vuex. From what I see in the examples, vuefire is linked directly to the view model of vue components. Would vuefire also be use useful in a vuex store.js file?

**Comment by posva** [comment]
I recommend you to take a loot at the v2 of vuexfire(https://github.com/posva/vuexfire/tree/v2). The doc isn't ready but tests show how to use it.
It's almost done but I'm missing some extensibility in vuex side to make it better (more specifically about the generated methods `bind` and `unbind`)

I don't know if we'll make vuefire compatible with vuex. I should discuss about this with Evan. We can also make vuexfire official
