### ISSUE TITLE
Chrome DevTools vuex state not reflecting vuexfire binding

### ISSUE THREAD

**Issue by jrhopkins83** [vuejs/vuefire#645]
I just started using vuexfire with Firestore and was pulling my hair out trying to figure out why the Vuex state was showing the loaded Firestore collection data in Chrom DevTools.

Once I inspected the component bound to the vuex getter I saw that the data was actually loaded.

Not sure if this is a Vue DevTools issue or Vuexfire issue, but It would be nice to be able to use the DevTools Vuex inspector with Vuexfire bound collections.

**Comment by jrhopkins83** [comment]
Correction to first paragraph, Vuex state **_wasn't_** showing the loaded Firestore collection data

**Comment by posva** [comment]
If you don't use the state in your page, tye devtools won't be able to show it. It's a technical limitation of the devtools
