### ISSUE TITLE
vuefire computed props issues, looking for guidance.

### ISSUE THREAD

**Issue by thedangler** [vuejs/vuefire#67]
Hello, I'm obviously doing this incorrect but I was wondering if you could give me some guidence.
Basically im trying to get the first place team by sorting an array but for some reason the array is empty in the computed prop.
in the console it shows that app.teams is an array but for some reason this.teams is undefined .

here is my code.

```js
                var playersRef = db.ref('players');
                var teamsRef = db.ref('teams');
                var eventsRef = db.ref('events');
            
                //sched_setup();
                
                var app = new Vue({
                      el: '#app',
                      data: function(){
                          return {
                            //default_events: default_events,
                            //firstPlaceTeam : {},
                            news : []
                          }
                      },
                      firebase : {

                              players: playersRef.limitToLast(30),
                              teams: teamsRef.limitToLast(7),
                              events: eventsRef.limitToLast(7)

                      },
                    computed: {
                        calculatePlace: function() {
                            return _.orderBy(this.teams, ['stats.P','stats.GP'], ['desc','asc'])
                        },
                        firstPlaceTeam : function(){
                            /* old code to find out first place team
                            firstplace = _.orderBy(this.teams, ['stats.P','stats.GP'], ['desc','asc'])[0];
                            if(this.firstPlace != firstplace.id && this.firstPlace != -1){
                                audio.play();
                                console.log("play");
                            }
                            this.firstPlace = firstplace.id;
                            */

                            return this.teams[0]; // undefined... why?

                        }
                    },
                    methods : {
                        testSelect: function (obj) {

                            console.log(obj.target.value);

                        },
                        eventWinner: function (event, match_index, winner, loser) {

                            logEvent(event, match_index, winner, loser);
                            console.log("winnnnneerrr");

                        }
                    }


                });
```

I'm really at a giving up point lol.
Any help would be appreciated.

**Comment by posva** [comment]
I honestly don't know. I tried it in a fiddle based on the demo and it just works fine: https://jsfiddle.net/posva/r3ab21nm/

Maybe you can try fiddling around to see where the issue is coming from. If you find a bug, please tell me here or better off, open a new issue with the repro

**Comment by thedangler** [comment]
I think I was able to reproduce it with simpler code.
HTML
`<div id="app">
            
            <ul>
            <li v-for="team in teams">{{ team.name }}</li>
            </ul>
            
            <pre>
            {{ firstPlaceTeam.name }}
            </pre>
        </div>`

JS

`      var teamsRef = db.ref('teams');
          
      var app = new Vue({
        
        el: '#app',
        data : function(){ return { news: [] }},
        firebase : {
        
            teams : teamsRef.limitToLast(7)
        
        },
        computed: {
            
            firstPlaceTeam  : function(){
                
                return this.teams[0];
                
            }
            
        }
        
        
        });`

when I run it the name prints out but I get errors.
Error when rendering root instance: 
Uncaught TypeError: Cannot read property 'name' of undefined

Since the errors happen it breaks the js and it stops working. I'm wondering if that is what is going on.

In your js fiddle example I did changed it to print filtered.text and the error console showed the same error.

**Comment by posva** [comment]
That's because of `{{ firstPlaceTeam.name }}` you need to check firstPlaceTeam first as it may be undefined: `{{ firstPlaceTeam && firstPlaceTeam.name }}`

**Comment by thedangler** [comment]
Thanks you.
Ill try my program tonight see if that's the culprit.

**Comment by greatramu** [comment]
@thedangler hi.. i think that is because the computed property is depending on the array populated by firebase. it looks like the computation is running too soon, before the firebase could finish fetching data. 

@posva is it possible to include a optional ```doneCallback()``` callback, similar to ```cancelCallback```? This ```doneCallback``` could be called after the async operations of firebase are completed and the properties in the vm are updated. This will be very useful to avoid issues like the above mentioned one. Also, it can be used to show status to user while loading the data from remote firebase server.

**Comment by posva** [comment]
> hi.. i think that is because the computed property is depending on the array populated by firebase. it looks like the computation is running too soon, before the firebase could finish fetching data.

The array is synchronously initialised to an empty array

About the doneCallback, I want to add something similar but not the for the same reasons.
