### ISSUE TITLE
Data must be an object, but it was: a custom Object object

### ISSUE THREAD

**Issue by dimavolo** [vuejs/vuefire#670]
I must be doing something wrong, and I'm getting the following error:

`
[FirebaseError]: Function DocumentReference.set() called with invalid data. Data must be an object, but it was: a custom Object object
`

I'm guessing this is because I'm setting an object where a value is an array?

In a Vuex `/store.js`:

```javascript
const bar = ['one', 'two', 'three']

this.$fireStore
          .collection('custom_cache')
          .doc('topShows')
          .set({ foo: bar })
```

Any insights on what's causing that `Data must be an object, but it was: a custom Object object` error?

Thanks!

**Comment by posva** [comment]
The error is coming from Firebase itself, not from vuefire so I would recommend looking for help there instead. I found this: https://stackoverflow.com/questions/48156234/function-documentreference-set-called-with-invalid-data-unsupported-field-val

**Comment by ServiceSector** [comment]
What worked for me was to wrap the element in JSON.parse(JSON.stringify(InsertElementHere))

**Comment by aniket-6234** [comment]
Yeah, I also get this type of error, but then I read firebase documentation and I get an idea about it. It's just a declaration problem. Initialize elements in a proper way.

**Comment by nguyenhoanganhtuan1206** [comment]
You can try it Object.fromEntries(formData)
