### ISSUE TITLE
[DOCS] Clarify loading data into state

### ISSUE THREAD

**Issue by traed** [vuejs/vuefire#671]
I just began looking into vuexfire and it seems really nice. The only issue I had was that the documentation tells us to create an action that will run context.bindFirestoreRef at some point, but it never tells us when (or even if) this action should be commited. It tells us how to get data but since it never mentions commiting the action to load the data no data will be displayed and I think that can confuse a lot of new users (myself includede).

Would it be possible to update the documentation with some best practices for this?

**Comment by posva** [comment]
I'm open to proposals as a pull request but Vuexfire assumes Vuex knowledge and therefore the need to dispatch an action for it to be executed
