### ISSUE TITLE
How to get .key/IDs of objects updated in store by VuexFire?

### ISSUE THREAD

**Issue by chadananda** [vuejs/vuefire#678]
I have a large list of complicated, keyed-objects in my store synced with Vuexfire. I need both sequential and random access, so I need them to all be in the store. This works very nicely -- so far as Vuex is concerned. 

When scrolling through these objects I use a virtual scroller and a computed list applying Object.freeze() to each -- otherwise the sheer number of DOM nodes and listeners immediately crashes the Chrome tab. (These are complicated objects, after all.)

This approach actually works just fine. The problem is very sluggish updating. It takes about two seconds for any reactive change to be applied because of the time required for the computed list to re-build the entire list of frozen objects after each change. This is very wasteful since I generally only have one object being updated. Thousands of objects have to be reprocessed to update just one.

I would like to build that list only once, and then update just one object when changes are detected from Vuex. The problem is, that a watcher returns the entire synced object or array -- so I have no idea which item was actually modified. 

When Vuexfire updates syncs objects, is there any way to watch for just .key(s) of objects changed?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can compare using the `id`s to extract what is removed/added or manually attach a firebase listener to detect changes for such a specific use case, giving up the convenience of Vuefire but gaining access to a lower level api
