### ISSUE TITLE
Serialize loses methods when storing in store

### ISSUE THREAD

**Issue by Pitouli** [vuejs/vuefire#683]
In my store I have this:
```
    bindContacts: firestoreAction(({ getters, bindFirestoreRef }) => {
      if (getters.user && getters.user.uid) {
        bindFirestoreRef('dbContacts', firebase
          .firestore()
          .collection(`users/${getters.user.uid}/contacts`), {
          serialize: snapshot => new Contact(snapshot.data(), snapshot.id),
        });
      }
    }),
```
And my "Contact" class is something like that:
```
export default class Contact extends DBObject {
  loadFromDB(contact = {}, id = null) {
    this.id = id || null;
    this.firstname = contact.firstname || null;
    this.lastname = contact.lastname || null;
  }

  exportToDB() {
    return {
      firstname: this.firstname,
      lastname: this.lastname,
    };
  }

  get name() {
    return `${this.firstname || ''} ${this.lastname || ''}`;
  }
}
```
I do not know why, but my getters (such as "name") or my methods (my real class is richer than this example) are not kept when the Contact is inserted in the store! 

Do you have any idea why?

Thanks.

**Comment by posva** [comment]
Can you provide a boiled down repro using the example at https://github.com/vuejs/vuefire/blob/master/packages/vuefire/examples/index.html (vuefire and vuexfire share the same code when it comes to binding so the problem will appear in both)

**Comment by Pitouli** [comment]
I cannot reproduce the issue anymore: I solved it by replacing vuefire by a custom solution. Sorry, I should have closed the issue.

**Comment by patrickcorrigan** [comment]
I have this issue too. The objects bound by serializer seem to lose their methods

**Comment by legislayer** [comment]
I also have the same issue here -_- 

```
 const serialize = (snapshot: firebase.firestore.DocumentSnapshot) => {
      const data = { ...snapshot.data() }
      data.blabla = "blabla"
      const user = plainToClass(User, data, { excludeExtraneousValues: true })
      if (user) console.log(user.constructor.name) // MyClass
      return user
    }

    return (firestoreAction(({ bindFirestoreRef }) => {
      return bindFirestoreRef(
        "user",
        db.collection(USER_DOCUMENT_PATH).doc(uid),
        { serialize: serialize },
      )
    }) as Function)(this.context)
```

In my serialize function everything looks good but once it is commited to the store, all typing informations are lost
