### ISSUE TITLE
Useing $route.params 

### ISSUE THREAD

**Issue by Shubedobedo** [vuejs/vuefire#698]
When trying to use vurfire with route params I get errors:  

"TypeError: Cannot read property '$route' of undefined"

Code causing error:

Export default {
  name: "Campaign",
  components: {},
  data() {
    return {
      town: null
    };
  },

  firestore: {
    town: db.collection("towns").doc(this.$route.params.id)
  }

**Comment by posva** [comment]
use the function syntax to get the right `this`:

```js
firestore() {
  return { town: ... }
}
```

---

Remember you can use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask quick questions!
