### ISSUE TITLE
[Question] access to firebase data through "created()" or "mounted()"

### ISSUE THREAD

**Issue by amranidev** [vuejs/vuefire#70]
Hi again!! :smile:

The VueFire just works perfectly in components template, all was reactive and evreything is allright, 

But there is ***One Thing*** that drives me crazy today. :thinking:

When I try to use firebase data through `created() or mounted()` methods in my component, it just become an empty Array.

```javascript
.
.
.
mounted(){
      console.log(this.messages) // [_obj_: Observer] => Array[0]
      // expected to be [Object, Object , _obj_ : Observer] => Array[n]
},
firebase(){
      return {
           messages: . . . .
      }
}

```

**Comment by posva** [comment]
It should not even exist in the `created` hook 😁
That's expected since Firebase populates it asynchronously. So there's no guarantee that your array is filled in any hook. You may look at #69 (in the so question) for some advice about getting when the array is ready

**Comment by amranidev** [comment]
@posva 

Basically, it's so important when we need some operation through `mounted()` while the component is created, these operations may be presented through a child component using it as an initial data.
for example : 
```html
<template>
   <div>
      <graph :values="ys" :labels:"xs"></graph>
   <div>
</template>
```

```javascript
mounted(){
      this.grahpdata.forEach(data =>{
           this.ys.push(data.y)
           this.xs.push(data.x)
      })
},
firebase(){
   return {
        graphdata: store.state.database.ref('graphdata')
     }
},
data(){
   return {
      xs: [],
      ys: [] 
  }
}
```
