### ISSUE TITLE
Being able to watch Firebase properties

### ISSUE THREAD

**Issue by KMolendijk** [vuejs/vuefire#71]
Watchers should get triggered when put on Firebase properties.

More info on:
https://forum.vuejs.org/t/watching-vuefire-properties/5832/2

**Comment by LinusBorg** [comment]
@KMolendijk  Please clearly state the issue here instead of just dropping a link. 

The easier you make it for maintainers to understand your problem, the faster they can help.

Also see the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) for opening issues.

**Comment by posva** [comment]
This happens because the property is added to the Vue instance after the watchers are created.
You have two options:

- Add the watch with `this.$watch` in the `created` hook
- Add a property to the `data` object with the same key you're using to bind the reference:
```js
data: { todos: [] }, firebase: { todos: todosRef }
```

**Comment by reddhouse** [comment]
Thanks for pointing out the two fixes @posva. Any ideas why this thread wouldn't show up in a Google search for vuefire, properties, watch, deep, etc.? I seriously hunted for this all morning, and finally just came here directly to browse closed issues. Surely the page has been archived by Google crawlers by now... Anyway, just wanted to point this out in case there are some "make searchable" settings for this repo, etc. I'm going to drop a link in the VueForum where @KMolendijk also asked this. Cheers.
