### ISSUE TITLE
Can't access/modify data from Console.

### ISSUE THREAD

**Issue by xerosanyam** [vuejs/vuefire#73]
So the best way for me to debug my vue app was by modifying the data values from console. But somehow with vuefire I can't access the data.
Am I doing something wrong ? If it is normal how do you debug ? 
Help required. Thanks

**Comment by posva** [comment]
Probably. You cannot directly modify the bound data. Please, follow [the example](https://github.com/vuejs/vuefire/blob/master/examples/todo-app/index.html) for more help. You should be able to get something similar to this:
<img width="1434" alt="screen shot 2017-02-07 at 09 19 55" src="https://cloud.githubusercontent.com/assets/664177/22683129/cb175874-ed16-11e6-8bbc-3de2f4f3afab.png">
