### ISSUE TITLE
Question: $firebaseRefs

### ISSUE THREAD

**Issue by thedangler** [vuejs/vuefire#74]
I'm using this for the first time and I was wondering when I should use this.$firebaseRefs.stuff apposed to this.stuff if i have the following?
var stuffRef = db.ref('stuff');
data :{
    something : null
    },
firebase :{

    stuff : db.stuffReff.limitToLast(4);
}

**Comment by posva** [comment]
You get access to the ref, so you can use it to push data to the firebase db. You can think of `this.$firebaseRefs.stuff` as where you write to `this.stuff` is where you read from
