### ISSUE TITLE
Is orderByKey with argument supported?

### ISSUE THREAD

**Issue by stursby** [vuejs/vuefire#75]
I'm trying to order by `name` on a collection of categories. (From the [Docs](https://firebase.google.com/docs/reference/js/firebase.database.Query#orderByKey))

Here's what the `/categories` ref looks like:

![image](https://cloud.githubusercontent.com/assets/527849/22791988/d192e8ee-eeb0-11e6-81f4-a26d3c444165.png)

...and in my Vue component

```javascript
export default {
  ...
  firebase: {
    categories: database.ref('categories').orderByKey('name')
  }
  ...
}
```

But I get the following Console Error

![image](https://cloud.githubusercontent.com/assets/527849/22792062/127deffc-eeb1-11e6-8b66-4b779024b796.png)

Maybe this just isn't supported by Vuefire? Maybe I'm just doing it wrong? ¯\_(ツ)_/¯

**Comment by posva** [comment]
What you want is orderByChild: https://firebase.google.com/docs/reference/js/firebase.database.Reference#orderByChild

It's supported, the error is actually a reminder from Firebase

**Comment by stursby** [comment]
Doh! Problem solved 👍 Thanks!
