### ISSUE TITLE
`this` is defined inside `firebase` function, but cannot access its props.

### ISSUE THREAD

**Issue by RobertAKARobin** [vuejs/vuefire#76]
Related to #66 

```html
<widget :fbid="myKey"></widget>
```

```js
var Widget = Vue.component('widget', {
	props: ['fbid'],
	firebase: function(){
		var widget = this;
		return {
			fbdata: {
				source: db.ref('/widgets').child(widget.fbid),
				asObject: true
			}
		}
	}
});
```

```
Error: Firebase.child failed: First argument was an invalid path: "undefined". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"
```

**Comment by posva** [comment]
It worked with my tests, can you provide a repro, please
You can use this as a starting point: https://jsfiddle.net/posva/wtyop5jy/

**Comment by RobertAKARobin** [comment]
@posva I think it's due to passing the key from a parent component's Firebase object to a child component, e.g.:

```html
<script>
Vue.component('objectShow', {
	template: '#objectShow',
	firebase: function(){
		return {
			shownObject: fb.ref('/objects').child('abc123')
		}
	}
});
</script>

<template id="objectShow">
	<div>
		<p>{{shownObject.title}}</p>
		<object-form :firebase-id="shownObject['.key']"></object-form>
	</div>
</template>

<script>
Vue.component('objectForm', {
	template: '#objectForm',
	props: ['firebaseId'],
	firebase: function(){
		var object = this;
		return {
			editingObject: fb.ref('/objects').child(object.firebaseId)
		}
	}
});
</script>

<template id="objectForm">
	<div>
		<input v-model="editingObject.title" />
		<button @click="save()">Save</button>
	</div>
</template>
```

I assume this is because the parent's`key` is loaded asynchronously, and hasn't been loaded by the time the child tries to load its Firebase objects. I worked around this by binding the Firebase object in the child's `created` function.

**Comment by posva** [comment]
> I assume this is because the parent'skey is loaded asynchronously, and hasn't been loaded by the time the child tries to load its Firebase objects. I worked around this by binding the Firebase object in the child's created function

Makes sense!

**Comment by joemanfoo** [comment]
I am sorry to post on a dead ticket - I don't mean to make zombies, but thought I'd post here in case future folks run into the same thing and also to try and get what the solution was to fix this issue

Here's a gist: https://gist.github.com/joemanfoo/5dd3ca9248840fafa58ef2e0ef3af422

Where I'm trying to show pending inventory that's secured down by a user's group id...the issue is the group id isn't getting defined in time.  I've tried to hook into beforeCreate, created, to no avail with my limited knowledge.  Hoping to get some help on what I'm doing wrong.

**Comment by RobertAKARobin** [comment]
@joemanfoo First thing I'd want to do is make sure `gid` can make it into the `PreviewInventory` component at all. Try changing `PreviewInventory.vue` to this:

```html
<template>
  <div>{{gid}}</div>
</template>
<script>
export default {
  props: ['gid']
}
</script>
```

Does the `gid` show up in the rendered view?

**Comment by joemanfoo** [comment]
Yes it does.

**Comment by RobertAKARobin** [comment]
OK. Switch back to what you had before and try using `mounted` instead of `created`. Does it `console.log` your `gid`?

**Comment by RobertAKARobin** [comment]
Actually, scratch that. Try this:

```html
<template>
  <div>{{gid}}</div>
</template>
<script>
export default {
  props: ['gid'],
  created: function(){
    console.log('created ' + this.gid);
  },
  mounted: function(){
    console.log('mounted ' + this.gid);
  }
}
</script>
```

**Comment by joemanfoo** [comment]
null in both places

**Comment by RobertAKARobin** [comment]
So it sounds like some kind of race condition, where that `profiles` Firebase object isn't loaded — and therefore `gid` doesn't exist — until after the `PreviewInventory` is already mounted.

I wonder if you might be able to "watch" for a change in `gid`?

```html
<template>
  <div>{{gid}}</div>
</template>
<script>
export default {
  props: ['gid'],
  watch: {
    gid: function(oldVal, newVal){
      console.log(oldVal + ' ' + newVal);
    }
  }
}
</script>
```

**Comment by joemanfoo** [comment]
`<template>
	<div>
	  <div>{{gid}}</div>
	</div>
</template>
<script>
export default {
  props: ['gid'],
  watch: {
    gid: function (oldVal, newVal) {
      console.log('watching gid: ' + oldVal + ' ' + newVal)
    }
  },
  created: function () {
    console.log('created ' + this.gid)
  },
  mounted: function () {
    console.log('mounted ' + this.gid)
  },
  updated: function () {
    console.log('updated ' + this.gid)
  }
}
</script>`

I'm seeing the GID on the updated function and with the watch
So, I guess my question is how to hook the fb.ref on the firebase: {} object.

**Comment by RobertAKARobin** [comment]
```js
watch: {
// or updated
  gid: function(nil, id){
    var vm = this;
    vm.$bindAsArray('pendingInventory', firebase.database().ref('temporary-inventory/').child(id).limitToFirst(10));
  }
}
```

**Comment by joemanfoo** [comment]
<template>
	<div>
	  <div>{{gid}}</div>
	  <div v-for="item in pendingInventory">
	  	<pre>{{item}}</pre>
	  </div>
	</div>
    </template>
    
    // and in watch:
    
    watch: {
      gid: function (nil, id) {
        let vm = this
        if (id) {
          vm.$bindAsArray('pendingInventory', firebase.database().ref('temporary-inventory/').child(id).limitToFirst(10))
          console.log('watching gid: ' + nil + ' ' + id)
        }
      }
    },

doesn't update pendingInventory or the view.

**Comment by RobertAKARobin** [comment]
At this point, I'd defer to @posva . It would be helpful if you could link to a complete repo, since that will be easier to test without so much back-end-forth.

**Comment by joemanfoo** [comment]
Thank you for all the help getting to this point, @RobertAKARobin greatly appreciated.

**Comment by joemanfoo** [comment]
watch: {
      gid: function (nil, id) {
        console.log('watching gid: ' + nil + ' ' + id)
      }
    },

is now outputting: `watching gid: 123456 null`

So that's what was keeping `pendingInventory` from getting updated...

crazy
