### ISSUE TITLE
Keep store in sync with local version

### ISSUE THREAD

**Issue by patrickcorrigan** [vuejs/vuefire#768]
Hi I'm trying to create an optimistic UI. I want to have in my vuex store the firestore bound array and a local copy that I can update.

I want the local copy to be synced if the firebase bound version changes. I'm thinking of using subscribe https://vuex.vuejs.org/api/#subscribe to watch for changes on the vuexfireMutations.

It seems to work but its fires for every value being set on the object being added to the array. I guess I can just watch for mutation types of ArrayAdd.

Here is my code. Is this a sensible way?

```
store.subscribe((mutation, state) => {
  if (mutation.payload.target === state.usersSamples) {
      // update state.localUsersSamples
  }
})
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
