### ISSUE TITLE
Why is SnapshotMetadata not exposed via the api?

### ISSUE THREAD

**Issue by Najtmare** [vuejs/vuefire#771]
Is there any particular reason why this isn't done? The hasPendingWrites is incredibly useful considering how firestore works and deals with for example: Timestamps.

https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotListenOptions
https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotMetadata

**Comment by posva** [comment]
Use the serialize option to customise the data that is set to the vue instance: https://vuefire.vuejs.org/api/vuefire.html#firestoreplugin
