### ISSUE TITLE
Any advice optimizing read count on Vuexfire firestore?

### ISSUE THREAD

**Issue by Arephan** [vuejs/vuefire#772]
<img width="935" alt="Screen Shot 2020-06-01 at 9 28 48 PM" src="https://user-images.githubusercontent.com/8092830/83469962-f7cc7f00-a44e-11ea-822a-d6227fa0d04e.png">
It's for a ticket management app. All tickets are stored under /tickets with only 2 boolean property & a string property for store name. I'm using manual bind like this: 

`bindTicketsRef: firestoreAction(context => {
      let storeName = context.state.user.data.displayName.toLowerCase()
      return context.bindFirestoreRef('tickets', db.collection('tickets').where("storeName", "==", storeName))
    }),`

There are only 4 tickets, but I'm getting ridiculously high read numbers compared to other operations. Should I scrap vuexfire all together and just use snapshot stuff?

**Comment by lsbyerley** [comment]
@Arephan did you figure out the best approach for this? I'm wondering this myself

**Comment by posva** [comment]
Vuefire already uses one single onSnapshot per document (plus per nested reference), using only onSnapshot would result in the same amount of reads. One of the reasons there are no write operations is to allow the user to control those by batches or anything they might need.

I know Firebase has docs to optimise the read/write number in their documentation, and following those would be the way to go
