### ISSUE TITLE
State not updating even if data, path and target are correct in SET_VALUE

### ISSUE THREAD

**Issue by NatanCieplinski** [vuejs/vuefire#774]
This is my state
```javascript
state: {
	party_code: 'asagdfvew' //A code that is the id of the document
	firebase_votes: {}
}
```
and this is my action
```javascript
bindFirebaseVotes: firestoreAction(async ({ bindFirestoreRef, state }) => {
	return bindFirestoreRef(
		'firebase_votes',
		db.collection('votes').doc(state.party_code)
	)
})
```
In my devTools i can see a `SET_VALUE` mutation that carry as payload the correct path, target and data, but the state is never modified. 
The `firebase_votes` object should look like this:
```javascript
{
	voters: 0,
	votes: {
		'sdfaskdfajsdf': 0, //The object properties are ids
		'sjsadfkajsdfk': 0,
		...
	}
}
```
I set `firebase_votes` as `{}` because in the doc is specified to set the initial value. I also tried to set it to `[]` and still it wasn't working.

**Comment by posva** [comment]
I can't tell what's wrong. I can take a look if you provide a boiled down reproduction using one of the `packages/vuefire/examples` folder (it's the same as using the `vuexfire` one but usually simpler)

**Comment by NatanCieplinski** [comment]
I tried to manually log the store and my code works but for some strange reason the Vue DevTools doesn't update correctly. Can i close the issue?
