### ISSUE TITLE
Vuefire bindings do not wait for references to resolve

### ISSUE THREAD

**Issue by fvanwijk** [vuejs/vuefire#776]
I created a [repo](https://github.com/fvanwijk/vuefiretest) and [demo](https://vuefire-testproject.web.app) to show the issue.

When you click [Add] on the location collection, a new location *with a reference to a building* is added. Firestore triggers an update, automatically updating the Vue binding that we set up using Vuefire.

In the log on the left - which is updated using a deep watch - we see two updates:
1. The building field is string `buildings/<someId>`
2. The building field is object `{ name: 'Building 1' }`

Since I set `{ wait: true }` on the binding and in the Vuefire global settings I expect update 1 not to happen.

**Comment by fvanwijk** [comment]
Although I can't reproduce it in this minimal example, in my original project repo it seems to be related to the fact that I fetch the [`buildings` collection before the `locations` collection](https://github.com/fvanwijk/vuefiretest/blob/master/src/components/Overview.vue#L74). There might be some caching involved when resolving references?

**Comment by posva** [comment]
This is expected `wait: true` waits for the first time only.
You can check if the document still contains references id where it should contain data in case you need to wait in watchers
