### ISSUE TITLE
Map data on $bind

### ISSUE THREAD

**Issue by Masterxhen** [vuejs/vuefire#777]
Is it possible to map data during binding like in sqls that gets a specific collumn/property of a firestore/realtime database document? Like the [array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) on querying

`this.$bind('documents', db.collection('documents').map(data => {
return {name: data.name, age: data.age})`

**Comment by fvanwijk** [comment]
Use a computed property to get derived data that updates automatically.
```js
computed: {
  mappedDocuments() {
    // Only get name and age keys
    return this.documents.map(({ name, age }) => ({ name, age }));
  }
}
```

In this particular case of a field mask you could use a [DataConverter](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter), but I think it is only supported when you do a one-time query.

**Comment by posva** [comment]
Use a computed property for the moment. See https://github.com/vuejs/vuefire/issues/608
