### ISSUE TITLE
Namespaced store case not well documented

### ISSUE THREAD

**Issue by tohagan** [vuejs/vuefire#781]
I found `vuexfire` documentation unclear when using stores with `namespace: true`.
Specifically I needed to know that the mutations need to be added to the root store.
Otherwise you invariably hit [this](https://github.com/vuejs/vuefire/issues/258) exception. 
Following the documentation and changelog as suggested in this exception issue did not help.

This is the example code I needed.  

2. Add to your **root** store  ...

import { vuexfireMutations } from "vuexfire";
import todos from "./todo.store"

```js
  modules: {
    todos
  }
  mutations: {
    ...vuexfireMutations
  }
```

2. Add to your namespaced store ..

```js
import { firestoreAction } from "vuexfire";

export default {
  namespaced: true,
  state: {
    todos: []
  },
  getters: {
    count: state => state.todos.length
  },
  actions: {
    bind: firestoreAction((context, { db }) => {
      return context.bindFirestoreRef(
        "todos",
        db.collection("todos").orderBy("task")
      );
    }),
    unbind: firestoreAction(context => {
      return context.unbindFirestoreRef("todos");
    })
  }
};

```

3. Add to your .vue file ...

```js
import { mapState, mapActions } from "vuex";

export default {
...
  computed: {
    ...mapState({
      todos: state => state.todos.todos
    }),
  },
  async mounted() {
    await this.bindTodos({ db: this.$db });
    this.loaded = true;
  },
  destroyed() {
    this.unbindTodos();
  },
  methods: {
    ...mapActions({
      bindTodos: "todos/bind",
      unbindTodos: "todos/unbind",
    }),
 }
}
```

**Comment by posva** [comment]
>  I needed to know that the mutations need to be added to the root store.

What documentation were you following? It was clearly stated in https://vuefire.vuejs.org/vuexfire/getting-started.html#adding-mutations. I added an extra note specific to Modules but the original message was already clear

**Comment by tohagan** [comment]
The examples show adding `vuexfireMutations` and `firestoreAction` to what appears to be the same root store. No example shows a store having `namespaced: true` so at first glance I thought the VuexFire mutations and binding actions needed to be added to each store.  Finally I figured our (after hitting the exception) that only `vuexfireMutations` belonged in the root store.

BTW ... Thanks enormously for VueFire and VuexFire.  They are invaluable in my current Quasar / Vue projects.
