### ISSUE TITLE
Vuexfire / bind collection directly to state in store-module

### ISSUE THREAD

**Issue by flomoto** [vuejs/vuefire#785]
I tried to bind a collection directly to a state in a Vuex-store via action-binding. The issue here: it creates a "sub"-state-field "state.news" instead of using the state directly. Is there any possibility using the state itself?

```javascript
const moduleNews = {
    namespaced: true,
    state: [],
    actions: {
        bindNewsRef: firestoreAction( (context) => {
            return context.bindFirestoreRef('news', db.collection('news'))
        }),
    }
}
```

**Comment by posva** [comment]
That's not possible in Vuex. You either have to put it at the parent (or root store) or add the `news` property to `state`
