### ISSUE TITLE
[Question] Cost of $bind on multiple components to same collection

### ISSUE THREAD

**Issue by Baralabite** [vuejs/vuefire#793]
Is there a cost to having multiple components subscribed to the same collection?

Example:
- I have 20 components who all $bind to firestore.collection('users')
- Let's say I update 1 document in firestore.collection('users')
- Do I get billed for 20 reads, or for 1 read.

Perhaps this is a question for the Firebase SDK onSnapshot. If I listened for changes 20 times using onSnapshot" instead of $bind, do I get charged once or 20 times. I assume vuefire uses onSnapshot under the hood.

The alternative of course is to set up vuex, and read from there. Or use an RxJS Observable.

**Comment by Baralabite** [comment]
This SO seems to have the answer - but I'd appreciate a confirmation in the vuefire context:

https://stackoverflow.com/questions/50130488/what-is-the-performance-cost-of-an-onsnapshot-in-firestore

**Comment by posva** [comment]
This is indeed a Firebase question related to how it’s pricing works. I’m not sure if having multiple onSnapshot calls instead of just one count as multiple requests so I won’t be able to help but the people over at Firebase probably can
