### ISSUE TITLE
Conditional bindings problem

### ISSUE THREAD

**Issue by JFGHT** [vuejs/vuefire#801]
### Steps to reproduce the behavior

1.- Create an array binding with a `where` clause, for example:

```typescript
firestore.collection('payments').where('total', '>', 0)
```

2.- Update one of the payments with `total = 0`.

That's it.

### Expected behavior

The array removes that document.

### Actual behavior

The document is still in the array (updated) unless you refresh and the query is retriggered.

**Comment by posva** [comment]
Please, provide the repro as said in the issue template

**Comment by JFGHT** [comment]
My bad, sorry for the annoyance.
