### ISSUE TITLE
Pivot datastructure not working / where clause for multiple ids

### ISSUE THREAD

**Issue by PascalHesselink** [vuejs/vuefire#804]
I'm trying to obtain user lists through a pivot table, because multiple users can have multiple lists.

I've tried two different obtaining methods, both methods won't work, is there a problem by obtaining collection items by id/key?

It doesn't obtain any item in the first method, in the second method I get an error "Uncaught (in promise) TypeError: document.onSnapshot is not a function".

Method 1:
```
db.collection('lists_participants').where('user_id', '==', this.user.uid)
  .get()
  .then(res => {
      const listIds = res.docs.map(doc => doc.id);

      this.$bind('lists', db.collection('lists').where('id', 'in', listIds));
  });
```

Method 2:
```
db.collection('lists_participants').where('user_id', '==', this.user.uid)
  .get()
  .then(res => {
      const listIds = res.docs.map(doc => doc.id);

      this.$bind('lists', listIds.map(id => {
          return db.collection('lists').doc(id);
      }));
  });
```

Is this is a bug or am I doing something wrong?

Help is appreciated.

**Comment by teschmitt** [comment]
Your first approach looks fine … assuming you have the `id` of each document saved in the document itself and are not running into [limitations of queries over array-membership](https://firebase.google.com/docs/firestore/query-data/queries#limitations).

**Comment by PascalHesselink** [comment]
> Your first approach looks fine … assuming you have the `id` of each document saved as a field in the document itself and are not running into [limitations of queries over array-membership](https://firebase.google.com/docs/firestore/query-data/queries#limitations)?

No I’m not storing any id as field because the ID is generated after the creation of a document. Any way to obtain the data by id without having it as field?

**Comment by teschmitt** [comment]
Ah ok, I think that could explain it. AFAIK, the `where` only searches fields of your document, of which the document ID is not a part of. In cases you need a document ID beforehand Firestore docs say to take this approach:

```javascript
// Add a new document with a generated id.
var newCityRef = db.collection("cities").doc();

// later...
newCityRef.set(data);
```
(see last example [here](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document)). But you'll have to research if this doesn't incur an extra read/write each time.

Or you could take an alternative route and use UUIDs in the documents to identify them and search over these.

**Comment by posva** [comment]
you cannot pass an array of refs to bind. You need to bind them individually:

```js
 listIds.forEach(id => {
    this.$bind('item_', + id, db.collection('lists').doc(id)
  });
```

---

Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
