### ISSUE TITLE
Vuexfire binding is gone after rehydrating state with vuex-persistedstate

### ISSUE THREAD

**Issue by teschmitt** [vuejs/vuefire#805]
### Reproduction

I am using `vuex-persistedstate` as a plugin to persist my state across page-reloads and back/forward-navigation, so somewhere in my store, I have

```javascript
import createPersistedState from "vuex-persistedstate";
…
plugins: [createPersistedState()],
…
```
This works just fine. Then I have a bound state object, lets call it `userProfile`, which I bind to a document reference like so:
```javascript
bindProfile: firestoreAction(({ bindFirestoreRef, state }) => {
    return bindFirestoreRef(
      "userProfile",
      profileCollection.doc(state.user.uid)
    ).then(() => {
      console.log("Profile now bound to db");
    });
```

Then I use the Firebase JS SDK to happily update the profile:

```javascript
  profileCollection
    .doc(state.user.uid)
    .update(updateStuff)
    .then(() => {
      console.log("Updated!");
    });
```

All of this works just great until I hit the back-button or refresh the page. The `update`-call goes through, my firestore console shows my data has updated but the binding to my `userProfile` object is defunct. It will not get the updates from the DB.

I have tested this on Firefox as well as Chromium and the behavior is the same.

### Additional information

Finding the source of this bug has been a harrowing experience.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If the data is not being updated anymore, it means the `bindFirestoreRef` didn't get properly called. On a side note, I wouldn't restore the data from local storage or at least make sure that `bindFirestoreRef` is executed **after** the data is restored.

**Comment by teschmitt** [comment]
Sorry, I legitimately thought I hit a bug. For anybody stumbling into this issue because they had the same problem: Use the power of the `rehydrated` option to rebind all your snychronized state after `vuex-persistedstate` has worked its magic.

```js
plugins: [
  createPersistedState({
    rehydrated({ dispatch, state }) {
      if (state.user) {
        dispatch("bindProfile").then(() => {
          console.log("Successfully re-bound");
        });
      }
    }
  })
]
```
Thanks also to @posva for the decisive hint!
