### ISSUE TITLE
Updating Source Via $Route Params

### ISSUE THREAD

**Issue by arpowers** [vuejs/vuefire#81]
I'm trying to update the paths of the Firebase references via a change in the route.. as in the example below: 

```javascript
firebase: function() {
return{
      meta: {
        source: api.fire.db.ref(`meta/` + this.$route.params.mid),
        asObject: true
      }
  }
}
```

However this has no effect... what is the appropriate way of doing this? Shouldn't this work?

I should note that this does work on page load, but not once the component itself is loaded and you want to change data based on user interaction.

**Comment by posva** [comment]
Yes, it should works: https://jsfiddle.net/bhvdymcj/
Can you provide a repro so I can look at it?

**Comment by arpowers** [comment]
The problem is when you don't actually change the component based on the $route ... in you're changing it from home to foo.... 

working on a reproduction now.

**Comment by arpowers** [comment]
here you go...

https://jsfiddle.net/npvxmL9b/14/

**Comment by arpowers** [comment]
I'm also aware that you're supposed to use a 'watch' when keeping the same components during a route change... however, i can't figure out an easy way to 'refresh' the vuefire stuff based on this.

(https://www.udemy.com/vuejs-2-the-complete-guide/learn/v4/t/lecture/5976606?start=0)

**Comment by posva** [comment]
Yeah, you can also use `beforeRouteUpdate` for params. What you need to do is `$unbind` and then `$bindAsObject` again in that hook (You can look them up on the Readme)
