### ISSUE TITLE
Can I use Vuefire in my Nuxt SSR app or not?

### ISSUE THREAD

**Issue by dosstx** [vuejs/vuefire#820]
Sorry for posting here, but I've tried in Stackoverflow and discord channels where I received no responses. 

I just wanted to ask a simple question that I could not find answered in the docs:

I am using Nuxt and Firebase. I want to use Vuefire for easy binding to data but also want to use asyncData() to help with rendering on the server side before hydration (for SEO purposes). 

Can I use Vuefire in my SSR app?

**Comment by posva** [comment]
Yes, you can. Please check existing issues, there is an open one with some examples

**Comment by dosstx** [comment]
I've seen Vuexfire, but not Vuefire. Can I use Vuefire only?
