### ISSUE TITLE
Empty data when accessing by key

### ISSUE THREAD

**Issue by TCMAD** [vuejs/vuefire#836]
I try to access in specify location with my RTBD on a monofile component but I have some strange results when I use the key `k` .

```javascript
Vue.use(Vuefire.rtdbPlugin)

const database = firebase.database();
const k = sessionStorage.getItem("keyEx");

export default {
    data : function(){
        return {
            key : k,
            exercice : []
        }
    },
    firebase : {
        exercice : database.ref('exercices/').child(k)
    }
}
```

Here is my template

```vue.js
<template>
    <p>
        {{ key || 'No key' }} <br>
        {{  exercice }} 
    </p>
</template>
```

And the result : 
![image](https://user-images.githubusercontent.com/40864981/89017913-5614c180-d31b-11ea-9822-633346dd1fa9.png)

I don't understand why my objects are empty. If I try to use childKey, it will just print an empty array.
But if I just define :  `firebase : {
        exercice : database.ref('exercices/')
    }`

It will give me my data : 
![image](https://user-images.githubusercontent.com/40864981/89018745-99236480-d31c-11ea-9496-74ff68407280.png)

How can I access to my child objects with the key `k` ?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Use the function version of `firebase` option and read the key right before binding. You probably will have to watch it as well
