### ISSUE TITLE
dist is not built up to latest version right now

### ISSUE THREAD

**Issue by elialbert** [vuejs/vuefire#85]
Looks like the src/ versions of vuefire have the readyCallback for bind(), but the dist versions do not. Just letting you know, took my 20 minutes to figure out why my readyCallback wasn't calling back.

**Comment by posva** [comment]
That's normal, I wanted to make sure it actually solves the SSR problem. I'll release a version after checking it

**Comment by elialbert** [comment]
Oh ok.

**Comment by posva** [comment]
Just updated 👍
