### ISSUE TITLE
How to change query without re-reading previously read documents?

### ISSUE THREAD

**Issue by pumpknhd** [vuejs/vuefire#857]
I am working on a calendar that binds a query, something like:
```
db.collection('documents')
  .where('month', '==', '2020-08')
```
Now when the user goes to the next month, I'd like to keep the previous data so that if the user goes back to 2020-08, it won't have to re-read all the documents again. Is there a way to query so that it doesn't re-read previously read documents?
```
db.collection('documents')
  .where('month', '>=', '2020-08')
  .where('month', '<=', '2020-09')
```
I think the above would re-read everything from 2020-08?

Thanks in advance for anyone's help.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I don't think that's possible as a new query will have to fetch again everything
