### ISSUE TITLE
Data loading events 

### ISSUE THREAD

**Issue by vanderlin** [vuejs/vuefire#86]
How about someway to know that the first data has loaded. 

```
this.$bindAsArray('tags', firebase.database().ref('/tags'), {
	onLoad: (data) => {
		// handle data
	},
	childAdded: (child) => {},
	childRemoved: (child) => {}
	childUpdated: (child) => {}
})
```

I have run into issues making sure the data is loaded.

**Comment by posva** [comment]
Use the `readyCallback`: https://github.com/vuejs/vuefire/blob/master/tests/vuefire.spec.js#L53
I'm against adding the other handlers though, because you can do that already by just using Firebase

**Comment by vanderlin** [comment]
agree I just noticed that was added in 1.4.0 Thanks :)

**Comment by victorleal** [comment]
@posva when you say that we can already do it by just using Firebase, I think on not using VueFire, right?

So if I need to know when data comes, I would have to write all code related with Firebase requests (which are abstracted by VueFire). 

I have a problem now that lies on this point: I have to instantiate a Google Maps component that waits for a parent component property. When it mounts, Firebase data has not arrived and I got an undefined map. 

What would be a solution for this? Maybe creating a component dynamically?

**Comment by posva** [comment]
Using the readyCallback should allow you to wait for data to be there.
If you need to know when data changes, just use a watcher on the data

**Comment by victorleal** [comment]
@posva thanks for your reply!

I used a watcher to handle this and it worked. Anyway, it's nice to have this answers here for people having the same problem!
