### ISSUE TITLE
Error with vuefire 1.4.1 (The "data" options should be a function that returns a per-instance value)

### ISSUE THREAD

**Issue by p4m** [vuejs/vuefire#87]
Vuefire 1.4.1 gives following error. I had to downgrade to 1.3.0 to solved this issue.

![image](https://cloud.githubusercontent.com/assets/1651685/24674397/80dcb9b6-197b-11e7-9ccd-30196d4d8313.png)

Some of the components do not even have a data attribute. And if I add one to a component, the error stays.

**Comment by posva** [comment]
mmh, that's weird, can you reproduce it here: https://jsfiddle.net/posva/wtyop5jy/ please?

**Comment by p4m** [comment]
In your example the issue does not occur.
In this simple example you can test it:
http://codepen.io/p4m/pen/afb664d6a71d6d6cf9f0715a9e1684e5?editors=0010
In the HTML view you can active 1.3.0 and you see it works. Version 1.4.1.
gives an error.


Kind Regards,

Frank Welten

: publishfor.me

Wildenborchallee 43
6921 JZ  Duiven
The Netherlands

+31 6 54970030
www.linkedin.com/in/frankwelten

2017-04-04 23:27 GMT+02:00 Eduardo San Martin Morote <
notifications@github.com>:

**Comment by posva** [comment]
mmh, I see I broke things in the last patch by updating the merge strats. The relevant line is https://github.com/vuejs/vuefire/blob/master/src/vuefire.js#L255 and if someone wants to fix it, there's more information at https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies

I'll take a look tomorrow if nobody has opened a PR in the meanwhile 🙂

**Comment by posva** [comment]
I reverted the previous release because I've been facing some issues when trying to make it work with functions
