### ISSUE TITLE
Vuexfire: Add includeMetadataChanges option to snapshot handling

### ISSUE THREAD

**Issue by flashfabrixx** [vuejs/vuefire#883]
### What problem is this solving

Related to https://github.com/firebase/firebase-js-sdk/issues/3661 this feature will enable listening to changes of the metadata to e.g. check for documents, which aren't synced with the server yet. 

At this time it's required to reload the data manually as the Vuex store is not notified about the changes for the metadata of the given query.

### Proposed solution

Extend [`FirestoreOptions`](https://github.com/vuejs/vuefire/blob/master/packages/%40posva/vuefire-core/src/firestore/index.ts#L5) with parameter [`IncludeMetadataChanges`](https://firebase.google.com/docs/firestore/query-data/listen#events-metadata-changes) and pass parameter to native Firebase handling.

_Example code_

```js
// ...
// Get `id`, `hasPendingWrites` and `fromCache` from snapshot data
const serialize = snapshot => {
      return Object.defineProperties(snapshot.data(), {
        id: {
          value: snapshot.id,
        },
        hasPendingWrites: {
          value: snapshot.metadata.hasPendingWrites,
        },
        fromCache: {
          value: snapshot.metadata.fromCache,
        },
      });
    };

    // Get ref with custom query
    const ref = db
      .collection("jobs")
      .where("userId", "==", user.uid)
      .limit(20)
      .orderBy("due");

     // Setup binding including metadata changes
     bindFirestoreRef("list", ref, {
      serialize: serialize,
      reset: false,
      includeMetadataChanges: true <-- NEW
    })
```

### Describe alternatives you've considered

I've tried to find other native methods or workarounds but did not find a solution yet.

**Comment by posva** [comment]
Yeah, we should definitely allow a way of passing https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotListenOptions, probably as a whole option named `snapshotListenOptions` even though I would really like to do it like you suggested: merging the types. I don't think we will have any overlap in naming properties but I think the other version will compress better if more options are added by the Firebase team later on

**Comment by posva** [comment]
This was implemented https://vuefire.vuejs.org/api/interfaces/UseDocumentOptions.html#snapshotlistenoptions
