### ISSUE TITLE
How to access global firebase instance through nested components?

### ISSUE THREAD

**Issue by f-k-z** [vuejs/vuefire#89]
Hi,

I try to access my firebase database reference in some nested components. 

Actually, I'd like to be able to access it with some kind of global variables.

I tried this solution, which looked to completely fits my expectations:
https://github.com/vuejs/vuefire/issues/21#issuecomment-251887922

```
//.db.js
import Firebase from 'firebase'
const firebaseApp = Firebase.initializeApp({ /*FIREBASE_CONFIG*/})
const db = firebaseApp.database()
export default db

// in your component:
import './db'

export default {
  firebase {
    example: db.ref('example')
  }
}
```
But it looks like @LinusBorg solution does not work anymore.
I now have this error in my nested component:

> [Vue warn]: Property or method "example" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

"example" is the variable name set in the component.

Any ideas?

Thanks

**Comment by posva** [comment]
Can you create a repro with https://jsfiddle.net/posva/wtyop5jy/ please?

**Comment by f-k-z** [comment]
Thanks for the quick reply.
Looks like I had an issue with ESlint finally. I initialized a new template and removed ESLint from it and now I can access the global variable.

**Comment by PierreDenisImie** [comment]
Did you try that 

export default {
 data(){
     return{
        example : null
    }  
}
  firebase {
    example: db.ref('example')
  }
}


?
