### ISSUE TITLE
Why not just use a route.param in my Firebase query?

### ISSUE THREAD

**Issue by p4m** [vuejs/vuefire#90]
Why can I not use a route.param to use in my Firebase Query?
Like shown in screenshot below:

![image](https://cloud.githubusercontent.com/assets/1651685/25217726/46d28956-25a8-11e7-8b54-c0de0bfc5f54.png)

Is this something for the future? Or is there another elegant way to do this?

And if this should work, I probably have to set watchers on the $route and refresh the data in my view (router-view). I need the watcher now too, because I want to see the details of the selected master in my router-view.

![image](https://cloud.githubusercontent.com/assets/1651685/25218391/f87c2c00-25aa-11e7-999a-271c3812bb0e.png)

**Comment by posva** [comment]
Use the function syntax for firebase. `this` isn't bound to the Vue instance otherwise

**Comment by p4m** [comment]
Great! Thanks for your quick reply!

This works! 👍 

![image](https://cloud.githubusercontent.com/assets/1651685/25220399/ed034816-25b1-11e7-9d5e-eac4c339d490.png)
