### ISSUE TITLE
with vue3 .. subscription is not happening

### ISSUE THREAD

**Issue by dev-kr2020** [vuejs/vuefire#900]
### Reproduction
create  vue 3 project using  CLI (add store with modules) , add vuexfire, and firebase/store for sure. create any reference binding - lets say to-do list. 
open the application and to-do list - keep the browser open
Go to firestore and change to-do name manually, It was reflecting earlier but looks like with vue3 it is not subscribing the changes.  
Lets try with delete in firestore.. to-do list item still shows..

**Comment by posva** [comment]
Vue 3 support is on its way 🙂

**Comment by dev-kr2020** [comment]
@posva is there any beta version to test?

**Comment by cainenielsen** [comment]
I would be **willing to donate** for the Vue3 support, very interested in using this library in single-file components and with Vue3 Vuex features. 

Thank you for all your hard work!

**Comment by replygirl** [comment]
I can also probably get my boss to sign off on a small donation!

**Comment by replygirl** [comment]
I can also probably get signoff from work on a small donation! (for vuexfire specifically)
