### ISSUE TITLE
Loading and storing references

### ISSUE THREAD

**Issue by BernhardSchlegel** [vuejs/vuefire#905]
### Reproduction

Given an object in the the database (e.g. `cars/pillar117`):

```
{
   name: "autumn",
   owner: "users/123" // reference, no string
}
```
Upon retrieval, the `owner` is automatically resolved. So the retrieved object looks like 

```
{
   name: "autumn",
   owner: {
      username: 'john117',
      hobbies: 'spartanlasertag',
      ...
   }
}
```
Which is **great** and one of THE reasons to use Vuefire. However, if I update the object by 

```
db.collection('cars').doc('pillar117').set(final_object)....
```
The `owner` field is no longer of type reference but a map that holds a copy of all values. Is this intended? What would be a workaround to keep the reference?

### Expected behavior

References are kept as references when an object is read and stored.

### Actual behavior

If an object is saved (unchanged) to the database, the reference property is overwritten as a map.

**Comment by posva** [comment]
This is a side effect of having the reference _unreferenced_ in the resulting object. I would say the proper approach would be to update only what you want to change using `update` or using the `merge` option in set (https://firebase.google.com/docs/reference/js/firebase.firestore.SetOptions). You can also extract everything but the owner: `const { owner, ...final_object }` and update that

**Comment by BernhardSchlegel** [comment]
Thanks for the blazing fast response! But in this case, I want to changed the "owner". E.g. ` owner: "users/123"` to ` owner: "users/117"`. Is there a way to "force" or "tell" vuefire to "re-unreference" the reference? I have to set it as `owner = db.collections('users').doc('117')` to be stored as a reference. But without reloading, "owner" will hold non JSON serializble data (and break my UI).

Thanks so much!

**Comment by posva** [comment]
You have to pass that reference to set it as a reference: `set({ ...finalObject, owner: db.collections('users').doc('117') })`

**Comment by BernhardSchlegel** [comment]
For everyone after me: My reference property was nested. To achieve a deep nested merge, I had to use lodash merge (`_.merge(object_ui, object_with_patched_references`). On `object_with_patched_references` only reference attributes are set, nothing else.
