### ISSUE TITLE
Firebase + VueFire + Nuxt.JS - Issue

### ISSUE THREAD

**Issue by mkharibalaji** [vuejs/vuefire#91]
Hi @posva ,
            First of all it's a great work.I was about to start the work using firebase + vuefire + nuxt.js and found a issue saying "vuefire not compatible with nuxt.js" ref :

https://github.com/nuxt/nuxt.js/issues/151

Is it possible to make it work witjh nuxt.js as the combination will rock together.

**Comment by posva** [comment]
It should now be possible using the `onReadyCallback` (similar to `cancelCallback`). I haven't implemented myself, but feel free to come back here with any extra information you find 🙂

**Comment by posva** [comment]
there's still no hydration in vuefire but I'm not sure of how to handle that, maybe I should delay writing to the array until the onReadyCallback

**Comment by ashersaupingomez** [comment]
+1

I've been looking all over to try find some guidance on integrating VueFire with Nuxt and haven't found anything. Any help?
