### ISSUE TITLE
options bind of doc does not work, while collections does.

### ISSUE THREAD

**Issue by zoranpopovic** [vuejs/vuefire#910]
### Reproduction
```
...
  data() {
    return {
      state: null, // loaded from firebase
      coll: [], //from firebase
    };
  },
  firestore: {
    state: db.collection("/coll").doc("state"),
    coll: db.collection("/coll"),
  },
  mounted() {
    console.log("state: ", this.state);
    console.log("coll: ", this.coll);
```
state is logged as null, while coll is logged an array that contains state doc.  Document bind just doesn't seem to happen at all, while collection bind works as expected.  A programmatic $bind of `/coll/state` doc works but not the options spec.  this
```
  firestore: {
    state: db.doc("/coll/state"),
```
also doesn't bind.

### Steps to reproduce the behavior

1. bind any existing doc in firestore options of a component
2. never gets bound

### Expected behavior

binds the same as collections.

### Additional information

latest firebase and vuefire.

**Comment by posva** [comment]
they are still asyncronous operations, you can await the promise returned by `$bind`: https://vuefire.vuejs.org/vuefire/binding-subscriptions.html#programmatic-binding
