### ISSUE TITLE
Only run a Vue Computed Component once data has been loaded from firebase? 

### ISSUE THREAD

**Issue by Snazzyham** [vuejs/vuefire#94]
Apologies if this is a little vague, but I was wondering if there would be a way to only have a vue computed function start running once the data from firebase has been loaded into the app? The reason I ask is because I have a computed function which determines the theme of my app based on the values in my firebase database, and it's trying to run that function before the data from firebase comes in, causing a TypeError that just leaves me with a blank screen. 

Thanks.

**Comment by Snazzyham** [comment]
Nvm, fixed by putting the call to my computed function in a span, and adding a v-if to check if the firebase data had come in yet.

**Comment by dizid** [comment]
> Nvm, fixed by putting the call to my computed function in a span, and adding a v-if to check if the firebase data had come in yet.
@Snazzyham Can i ask how you check if the firebase data had come in?
