### ISSUE TITLE
VuexFire: No reactivity on arrays added to the state by bindFirestoreRef

### ISSUE THREAD

**Issue by petertjmills** [vuejs/vuefire#941]
### Reproduction

Use one of the examples at https://github.com/vuejs/vuefire/tree/master/packages/vuefire/examples to boil down and reproduce the problem. If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look

### Steps to reproduce the behavior
When binding a firestore ref to array in state, with an action such as this:

`actions: {
    bindRef: firestoreAction(({bindFirestoreRef}, query) => {
      return bindFirestoreRef(query.parentId, db.collection(query.type).where(query.parent, '==', query.parentId))
    }),
  },
`

where the item in the store, is created by the action (query.parentId), a getter when computed such as this:

`getters: {
  	getObjectByVal: (state) => (parentId, type) => {
      return state[parentId].find(obj => obj.type == type)
    }
  }`

run in app with

`computed: {
    obj: function () {
       return this.$store.getters.getObjectByVal("top", "TopBar")
    }
  }`

will not automatically update on state change, unless the array already exists in the store.
 
### Expected behavior

Arrays created by the bindFirestoreRef should also be reactive, in that they reload the page on state update.

### Actual behavior

When the getter is first run after page has loaded, it errors to the console with "state[parentId] is undefined" and then doesn't run again, even after state has been updated.

### Additional information

I'd spent a fair few hours troubleshooting this, and I definitely may be misunderstanding things. But surely there should be some way to make the bound arrays generated by the action reactive?

**Comment by posva** [comment]
The array reactivity caveat you're experienced is described in Vuejs docs. You will find there help!

**Comment by petertjmills** [comment]
I've read through the caveats on the docs however I'm not sure this applies, as I'm not using any custom mutations. This is as a result of the vuexfireMutation. The solutions in the docs refer to using Vue.set, in mutations but I'm not using any, just the vuexfireMutation.
The issue arises from using defining a new array, when calling bindFirestoreRef(newStateObject, etc.). The new object in the state is created and stays updated however doesn't reload computed() values. 
Could there be any work around or are the caveats defined in the docs, inherent to vue/the vuexfireMutations?

**Comment by posva** [comment]
I would say it's the access via `[parentId]` (https://vuejs.org/v2/guide/reactivity.html#For-Arrays)
Remember we have the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) to ask questions. But feel free to come back and open an issue if it turns out to be a bug 🙂
