### ISSUE TITLE
Error thrown on app start after Firebase update to v8.0.2

### ISSUE THREAD

**Issue by 185driver** [vuejs/vuefire#943]
### Reproduction

Use one of the examples at https://github.com/vuejs/vuefire/tree/master/packages/vuefire/examples to boil down and reproduce the problem. If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look

### Steps to reproduce the behavior

1. Upgrade a vuejs (v2) app which uses vuexfire v3.2.3 from firebase v8.0.1 to v8.0.2
4. See error thrown in the browser dev console on app start.

![image](https://user-images.githubusercontent.com/1835454/99137550-27cca080-25f1-11eb-8229-7e1943d056b4.png)
### Expected behavior

No error should be thrown.

### Actual behavior

An error is thrown in the browser dev console.

### Additional information

Reverting to firebase v8.0.1 resolves the issue. I'm not suggesting vuexfire is causng an error, but something in vuexfire appears to not be working following the firebase upgrade.

**Comment by posva** [comment]
It's not supported yet, there is an open pull request
