### ISSUE TITLE
firestore subscription throwing error on change

### ISSUE THREAD

**Issue by magicseth** [vuejs/vuefire#944]
### Reproduction
<template>
  <div>
    Magician

    {{ spectators }}
  </div>
</template>

<script>
import { db } from "../db.js";
export default {
  data() {
    return {
      spectators: [],
    };
  },
  mounted() {
    db.collection("spectators")
      .get()
      .then(function (querySnapshot) {
        querySnapshot.forEach(function (doc) {
          console.log(doc);
        });
      });
  },

  firestore: {
    spectators: db.collection("spectators"),
  },
};
</script>

### Steps to reproduce the behavior

Open page
### Expected behavior
show the spectators loaded from firestore.

### Actual behavior

It throws an error:
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at extractRefs (vuefire.esm.js?0ff2:186)
    at Object.added (vuefire.esm.js?0ff2:354)
    at eval (vuefire.esm.js?0ff2:412)
    at Array.forEach (<anonymous>)
    at Array.eval (vuefire.esm.js?0ff2:411)
    at next (index.esm.js?c6c5:16645)
    at eval (index.esm.js?c6c5:13404)

**Comment by magicseth** [comment]
In  bindCollection(_a, extraOptions)

I am seeing that _a.newIndex == -1

Which means that subs ends up undefined.


    var change = {
        added: function (_a) {
            var newIndex = _a.newIndex, doc = _a.doc;
            arraySubs.splice(newIndex, 0, Object.create(null));
            var subs = arraySubs[newIndex];
            var _b = extractRefs(options.serialize(doc), undefined, subs), data = _b[0], refs = _b[1];
            ops.add(array, newIndex, data);
            subscribeToRefs(options, array, newIndex, subs, refs, ops, 0, resolve.bind(null, doc));
        },

**Comment by magicseth** [comment]
![image](https://user-images.githubusercontent.com/15504/99162048-af77e500-26ad-11eb-9e46-00d7bca45c55.png)

**Comment by magicseth** [comment]
It seems like it's a problem with the latest firebase.js 

Here's a repro:
https://jsfiddle.net/tsqvg9hf/2/

**Comment by khabali** [comment]
i'm getting the same issue with the latest versions:

```
"vuefire": "^2.2.4"
"firebase": "^8.0.2",
```

when fetching a collection
```
vuefire.esm.js?0ff2:186 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at extractRefs (vuefire.esm.js?0ff2:186)
    at Object.added (vuefire.esm.js?0ff2:354)
    at eval (vuefire.esm.js?0ff2:412)
    at Array.forEach (<anonymous>)
    at Array.eval (vuefire.esm.js?0ff2:411)
    at next (index.esm.js?c6c5:16645)
    at eval (index.esm.js?c6c5:13404)
````

**Comment by magicseth** [comment]
I moved back to 7. For firestore and it worked

**Comment by posva** [comment]
https://github.com/vuejs/vuefire/pull/940

I haven't been able to look at this yet. Help on reviewing what has broken, if a new major version of vuefire should be released, and reviewing the PR would be appreciated
