### ISSUE TITLE
vuefire.esm.js?0ff2:186 Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by slimack** [vuejs/vuefire#948]
**Uncaught TypeError: Cannot convert undefined or null to object**
I'm not sure this is a bug, but when I try to bind to property, the error I get is displayed. I have no idea why bind works with one document but not with the entire collection. Because the problem only affects the binding of the entire collection.

Error Message:
```
vuefire.esm.js?0ff2:186 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at extractRefs (vuefire.esm.js?0ff2:186)
    at Object.added (vuefire.esm.js?0ff2:354)
    at eval (vuefire.esm.js?0ff2:412)
    at Array.forEach (<anonymous>)
    at Array.eval (vuefire.esm.js?0ff2:411)
    at next (index.esm.js?c6c5:16645)
    at eval (index.esm.js?c6c5:13404)
```

Component script
```
<script>
import { db } from "../firebase";

export default {
  data() {
    return {
      documents: ["mis"],
      search: ""
    };
  },

  firestore: {
    documents: db.collection("items"),
  },
  },

</script>
```

**Comment by posva** [comment]
you probably need to use firebase 7. See https://github.com/vuejs/vuefire/pull/940
Please search existing issues before opening new ones, thank you 🙂
