### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jasmin92** [vuejs/vuefire#950]
![image](https://user-images.githubusercontent.com/28627630/99549356-d9851c00-29b9-11eb-8bb3-d244af722fc8.png)
Hey, i have faced this issue with when i tried to fetch from firestore.
I followed all instructions from docs.

Firestore database contains just one collection "users" with one document in it.

error occurred on: 
```
firestore: {
    users: db.collection('users')
},
```
However, if i try to fetch it manually, it'll be returned without errors
```
 async created() {
    let users = await db.collection('users').get();
    users.forEach(user => {
      console.log(user.data());
    })
  }

**Comment by stamler** [comment]
Same issue, specifically does not happen with @firebase/firestore 2.0 but DOES occur on @firebase/firestore 2.0.2

**Comment by amandine-trl** [comment]
Hi,
I have the exact same issue using firebase 8.0.2.
Downgrading to firebase 8.0.1 solved the issue.
Thank you @stamler !

**Comment by posva** [comment]
https://github.com/vuejs/vuefire/pull/940

Make sure to search existing issues and not to ignore the template when opening issue, please! It's important for open source maintainers
