### ISSUE TITLE
Error on binding

### ISSUE THREAD

**Issue by raphaelmollon** [vuejs/vuefire#952]
Hi,

I'm trying to bind an array in my store to a collection in firestore, but I get this error I don't understand:
```
Uncaught TypeError: can't convert undefined to object
    extractRefs vuexfire.esm.js:190
    added vuexfire.esm.js:358
    unbind vuexfire.esm.js:416
    unbind vuexfire.esm.js:415
    node_modules index.esm.js:16653
    node_modules index.esm.js:13412
```

here's the code of the store:

```javascript
import { vuexfireMutations, firestoreAction } from 'vuexfire'
import {db} from '@/plugins/vuefire.js'
Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    categories: [],
  },
  getters: {
    categories(state) {
      return state.categories;
    },
  },
  mutations: {
    ...vuexfireMutations,
    addToCategories(state, cat) {
      state.categories.push(cat);
    }
  },
  actions: {
    bindCategories: firestoreAction(({ commit, bindFirestoreRef }) => {
      // db.collection('categories').onSnapshot(snapshot=>{
      //   snapshot.forEach(snap=>{
      //       console.log(snap.id, snap.data());
      //       commit('addToCategories', {id:snap.id, ...snap.data()});
      //   })
      // });

      return bindFirestoreRef("categories", db.collection("categories")); // IF I COMMENT HERE, ERROR DISAPPEARS
    }),
  },
  modules: {
  }
})
```

Moreover, if I subscribe without using vuexfire it works (when commenting what's not and uncommenting what is in the code above)
So this means db.collection("categories") is reliable.

About plugin/vuefire.js, it's only the init of firebase, as you can see:
```javascript
import firebase from 'firebase/app';
import 'firebase/firestore';
// import 'firebase/auth';

var firebaseConfig = {
    apiKey: ...
    authDomain: ...
    databaseURL: ...
    projectId: ...
    storageBucket: ...
    messagingSenderId: ...
    appId: ...
  };

// Get a Firestore instance
const firebaseApp = firebase.initializeApp(firebaseConfig);
export const db = firebaseApp.firestore();
```

On the other hand, when I modify this codepen (used in an other issue): https://codepen.io/frelu/pen/gOpopEg?editors=1111 to reach my database, it works perfectly (meaning apply my firebaseConfig and rename events collection to categories)

I compared both codes and don't see what I'm doing wrong.

Would be anyone kind enough to give me a hand on this, please?

**Comment by posva** [comment]
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

This is because firebase 8 is yet not supported

**Comment by raphaelmollon** [comment]
Sorry I did search on google, but couldn't find the issue.
So the proper way to do it "for now" with firebase 8 is what is commented in my code?
Too bad this is not specified in the documentation.

**Comment by sudevn** [comment]
It would work with Firebase 7.x
