### ISSUE TITLE
Vuefire error Maximum call stack size exceeded when calling for collections that contains reference column inside the documents

### ISSUE THREAD

**Issue by verm024** [vuejs/vuefire#956]
I'm trying to bind vuefire to a collection that have reference column inside the documents, but it returned error maximung call stack size exceeded. Normally, i can do this and returned it well.

Here is the error
![image](https://user-images.githubusercontent.com/45099597/100242002-e334f380-2f66-11eb-82df-faefd5df4f94.png)

Here is my code
```
data() {
    return {
      daftar_kelas: []
    };
  },
watch: {
    get_daftar_kelas: {
      immediate: true,
      handler() {
        this.$bind("daftar_kelas", firebase.db
          .collection("kelas")
      )}
    }
  }
```

Here is my firestore structure
![image](https://user-images.githubusercontent.com/45099597/100242469-65bdb300-2f67-11eb-957e-b0155fa7be89.png)

### Expected behavior

Returned array of objects that contains all the documents in a collection

### Actual behavior

Returned error Maximum call stack size exceeded

**Comment by posva** [comment]
As said in the issue template, don't open issues without reproductions, thanks.
