### ISSUE TITLE
Access to doc.path (and perhaps renaming doc.id)

### ISSUE THREAD

**Issue by Towerful** [vuejs/vuefire#958]
### What problem is this solving

I find myself storing the path to a document in many of my documents, because I have a lot of polymorphic style data that can be nested under many different documents.  
This can get quite complicated, especially when using `collectionGroup`s.  
The firestore `onShapshot()` function returns the doc, which gives access to the `data()` `id` and `path`.  
It would be nice to access these in Vuexfire/Vuefire as well, without having to store additional information in firestore.

I realise it is an ambiguous implementation, however an `id` property in a firestore document is currently overwritten by the vuefire/vuexfire `id` of the document.  

Nesting these under their own object would hopefully reduce (if not remove) these collisions.

### Proposed solution

When loading in the data, adding a `$doc` property to each document that gives access to the `path` and `id` property.  
You could then use `this.myData[0].$doc.path` and `this.myData[0].$doc.id`.  

I feel the `$` prefix would show that this is an 'internal' property and is non-enumerable/read-only (as the `id` property is now).  
I believe the `$` is also an illegal character for a document field path, which would eliminate any chance of collisions.

I understand that removing the `id` property would be a breaking change that a lot of people rely on, so perhaps the `$doc` property could be added as non-breaking change, with a configuration option for the `id` field.   
The configuration for the `id` field could default to `true` with a depreciation warning with the intent of removing it in a few versions.

### Describe alternatives you've considered

`$doc` could also be `$fire`.  
However this might be confused with the `vm.$fire` or `this.$fire` properties.

Assigning an additional `path` property to the actual data increases that chance of collision with existing data.

An additional 'processing' function that is called for each document.  
This would allow the user to add these properties however they want to. It would also allow for mutating values (ie `serverTimestamp`s to `Date`s).  
However, I think the increase complexity would be detrimental to the ease of use.

Writing the document's path into firestore when creating documents is what I am currently doing, however reducing document size is always a win!

**Comment by posva** [comment]
You can already customize this with https://vuefire.vuejs.org/api/vuefire.html#firestoreplugin

**Comment by Towerful** [comment]
Ah, thats mega.  
I must've overlooked that!  
looks like the global firestoreOptions with a serialize is the way to go!
