### ISSUE TITLE
[Question] accessing default set of data, without "normalization"

### ISSUE THREAD

**Issue by Frondor** [vuejs/vuefire#97]
I have a reference to `products` like `products: db.ref('products')` which is the vuefire "normalized" set of data, with the `.key` included on each object. But I need to display the value on a table like `products[product['.key']]` which is not possible because vuefire removes each objects key.

How can I access the default set of data provided by firebase just before vuefire normalizes it, **without making a new request**?

Actually, if I do something like `$firebaseRefs.products.child(product['.key'])` it returns `"https://app-5437f.firebaseio.com/products/-KjicDLQQbz2SXxFs7Qk"` :confused:

**Comment by posva** [comment]
You can't. But you can bind it as an object instead of an array so it looks like:

```js
'key': {},
'key2': {}
```

Be aware, this will also include `.key` for the current element but will keep it out from children
