### ISSUE TITLE
Wait does not wait for referenced documents

### ISSUE THREAD

**Issue by legislayer** [vuejs/vuefire#978]
I'm using `vuex-module-decorators` in combination with `vuexfire`. Everything works great and I'm really thankful for this library. 

But I have one issue. I'm having the following store: 

```
@Module({ namespaced: true, name: "blueprints", store, dynamic: true })
export class Auth extends VuexModule {
  userDocument: UserDocument | null = null
  @Action({ rawError: true })
  async bindUserDocumentRef(): Promise<Function> {
    const db = firebase.firestore()
    const uid = firebase.auth().currentUser?.uid

    return (firestoreAction(({ bindFirestoreRef }) => {
      return bindFirestoreRef(
        "userDocument",
        db.collection(UserDocumentsPath).doc(uid),
        { wait: true, reset: false, maxRefDepth: 1 },
      )
    }) as Function)(this.context)
  }
}
```

The document `db.collection(UserDocumentsPath).doc(uid)` contains an array with referenced documents

![image](https://user-images.githubusercontent.com/75792391/103169184-d4797f00-4839-11eb-97aa-4e2916a87b3a.png)

Once I start binding the reference 

```
export default class Blueprints extends Vue {
  beforeMount() {
    store.bindUserDocumentRef()
  }

  get dataSource() {
    // const items = store.userDocument?.owned
    // return new DataSource(items ?? [])
    const items = store.userDocument?.owned ?? []
    console.log("items====>", items)

    return new DataSource([])
  }
}
```

For every referenced documents the binding returns which causes my ui to reload for every new document

![image](https://user-images.githubusercontent.com/75792391/103169210-0ee31c00-483a-11eb-80a5-95b13eae8bac.png)

**Comment by posva** [comment]
Hello, please follow the issue template and make sure to provide a boiled down reproduction. Open a new issue and read the provided instructions. Thank you!
