### ISSUE TITLE
vuexfire: Add support for dynamic bindings and properties' paths

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vuefire#988]
### What problem is this solving

`bindFirestoreRef` expects the first parameter to be a string, so the state property we want to bind needs to be pre-defined and known at store initialisation.

In order to bind dynamic properties I do the following:

``` js
const ref = db.collection('whatever');
const dynamicProperty = getPropertyName(); 

Vue.set(state, dynamicProperty, null);
bindFirestoreRef(dynamicProperty, ref);
```

### Proposed solution

- When calling `bindFirestoreRef(property, ref);` create `state.property` if it doesn't exist
-  Add support for nested properties: `bindFirestoreRef('some.nested.property')`

### Describe alternatives you've considered

I didn't find a solution for nested properties, but dynamic properties issue is solved by `Vue.set`

**Comment by sooand** [comment]
@wujekbogdan Have you found an alternative solution you use, until this feature (might) get implemented?

**Comment by posva** [comment]
Should be covered now https://vuefire.vuejs.org/cookbook/vuex.html https://vuefire.vuejs.org/cookbook/subscriptions-external.html
