### ISSUE TITLE
Uid as a key

### ISSUE THREAD

**Issue by jamesxv7** [vuejs/vuefire#99]
For example, I want to store the uid generated by Firebase Auth in the following path: root\users\

Can I use the uid as a key instead the key auto-generated by VueFire?

I want something like:
```
users
   mgNiGPl5efdWGCEaW8tw21ZzO2F3
     displayName: "Joe"
```
And not
```
users
  -KkEYrh9MO-Nr3nQ3uOh
    uid: "mgNiGPl5efdWGCEaW8tw21ZzO2F3"
    displayName: "Joe"
```

**Comment by posva** [comment]
It's Firebase that's generating the key 😄 
Yes, you can by doing `child(uuid).set` or something similar

**Comment by jamesxv7** [comment]
`this.$firebaseRefs.users.child( user.uid ).set( {displayName: user.displayName} )` did the trick, thanks @posva for the hint!
