### ISSUE TITLE
Vuexfire does not work with the new version of @nuxtjs/firebase ^7.3.0  module

### ISSUE THREAD

**Issue by GuasaPlay** [vuejs/vuefire#990]
I am following this example of vuexfire to implement in my project but I think that with the new version of @nuxtjs/firebase the implementation with vuexfire has broken.

![image](https://user-images.githubusercontent.com/45466316/104332576-51555b80-54be-11eb-8b71-68a6ca79bdca.png)
![image](https://user-images.githubusercontent.com/45466316/104332597-56b2a600-54be-11eb-9c4b-b0209c9efb92.png)

Any solution?

**Comment by posva** [comment]
You should open the issue on n that repository. Also please don't discard the issue template
